### ISSUE TITLE
AXUpload5 fileListLoad.php 매개변수 전달 방법 문의드립니다.

### ISSUE THREAD

**Issue by webgori** [axisj-com/axisj#378]
안녕하세요.
AXUpload5를 이용하여 개발 중 궁금한점이 있어 질문 남깁니다.

저는 fileUpload.php와 fileDelete.php 파일 참조시 Pars에 매개변수를 전달하여 경로로 사용하고 있습니다.
```uploadPars:{category:$( "#SelectMagnetCategory" ).val()},```
하지만 fileListLoad.php에는 매개변수 전달하는 방법이 없는것일까요?
$upload_dir에 경로설정을 할 때 필요하기 때문입니다.

아래는  http://dev.axisj.com/samples/AXUpload5/index.html 샘플 링크의 <script> 부분을 참조하였습니다.
```
			// 서버에 저장된 파일 목록을 불러와 업로드된 목록에 추가 합니다. ----------------------------- s
			var url = "./modules/atr/skins/default/axisj/fileListLoad.php";
			var pars = "dummy="+axf.timekey();

			new AXReq(url, {pars:pars, onsucc:function(res){
				if(!res.error){
					myUpload.setUploadedList(res);
				}else{
					alert(res.msg.dec());
				}
			}});
			// 서버에 저장된 파일 목록을 불러와 업로드된 목록에 추가 합니다. ----------------------------- e
```

**Comment by webgori** [comment]
생각해보니 저장된 파일 목록을 보여줄 필요가 없었습니다.
주석처리하여 해결했습니다.

**Comment by tom-axisj** [comment]
```
				// 서버에 저장된 파일 목록을 불러와 업로드된 목록에 추가 합니다. ----------------------------- s
				var url = "fileListLoad.php";
				var pars = "dummy="+axf.timekey();
				new AXReq(url, {pars:pars, onsucc:function(res){
					if(!res.error){
						myUpload.setUploadedList(res);
					}else{
						alert(res.msg.dec());
					}
				}});
				// 서버에 저장된 파일 목록을 불러와 업로드된 목록에 추가 합니다. ----------------------------- e
```

에서 pars에 파라미터를 주시면 됩니다. 참고하세요

**Comment by webgori** [comment]
```<script>``` 부분을 그냥 사용해서 아래 부분이 노출되지 않았었네요;;
```var pars = "dummy="+axf.timekey();```
이 부분을 보기는 봤습니다만, 실제로 fileListLoad.php 파일에서 dummy를 키로 사용하는 부분이 없어서 아닌줄 알았습니다.

답변 감사합니다.
