### ISSUE TITLE
AXUpload5 사용에 관한 몇가지 질문

### ISSUE THREAD

**Issue by webgori** [axisj-com/axisj#379]
안녕하세요.
AXUpload5 개발 중 궁금한점이 몇가지 있어 이슈 남깁니다.

01. ```<div id="uploadQueueBox" class="AXUpload5QueueBox_list allowDrop" style="height:188px;"></div>```에서 class는 AXISJ API 페이지의 어느 부분에서 확인 가능할까요? 제가 예제 페이지에서 확인한 바로는 allowDrop, AXUpload5QueueBox, AXUpload5QueueBox_list가 있는 것 같습니다. 혹시 제가 확인하지 못한 class가 더 있다면 알려주시면 감사하겠습니다.

02. AXUpload5QueueBox_list class를 사용할 경우 공식적으로 파일 전송 진행 상황를 보여주지 않는건가요? AXUpload5QueueBox class는 파일 전송 진행 상황을 확인 가능하였습니다.

03. AXUpload5QueueBox class를 사용할 경우 이미지 파일의 경우에는 썸내일이 표시되지만, txt나 기타 확장자의 경우에는 그냥 투명하게 나옵니다.(Console에 Resource interpreted as Image but transferred with MIME type text/html: "http://dev.axisj.com/samples/AXUpload5/files/AX_1091078370.html". 라는 메시지도 확인 가능합니다.) 해당 확장자에 맞게 아이콘이라도 보여줄 수 있게 설정이 가능한가요?

감사합니다.

**Comment by tom-axisj** [comment]
1. CSS 테마는 API에서 기술 하고 있지 않습니다. ui > arongi > AXUpoad5.less 파일을 열어보시면 알 수 있습니다.

2. 제가 만들기론 진행률 바가 있는데. 업로드가 너무 빨라서 안보이는게 아닐까 생각합니다. (그런데.. 오래되서 정확한 기억은 아닙니다.)

3. 서버측 리턴JSON에서 thumbUrl 값이 없으면 파일 확장자를 썸네일에 표시합니다. 확장자에 따른 썸네일을 확장 하시길 원한다면..
https://github.com/axisj-com/axisj/blob/master/lib/AXUpload5.js#L2455 이 부분에서 
```
jQuery("#" + cfg.queueBoxID).find("#"+itemID+" .AXUploadIcon").css({"background-image":"none"});
```
의 background-image 값을 사용자 함수로 빼내서 추가 해주면 되겠는데요. 당장 필요가 없어서.. 괜찬으시다면 님께서 한번 확장 해보시면 어떨까 합니다. 아이디어좀 내주세요.

**Comment by hyunjun19** [comment]
그냥 함수로 받는건 어떨까요?
그럼 많이 고민할 필요도 없고 자유도도 높아지고~

```js
myUpload.setConfig({
...
    thumbRender: function(qBox, file){
        var thumbHTML = '';
        switch(file[cfg.fileKeys.type]):
        case 'jpg':
        case 'png':
             thumbHTML = '<div>...</div>';
             break;
        default: 
            break;
    }
...
});
```

**Comment by tom-axisj** [comment]
thumbRender는 네이밍이 좀 이상한거 같은데요?

**Comment by hyunjun19** [comment]
``thumbRenderer`` 였는데... 오타에요.

**Comment by webgori** [comment]
두분 모두 답변 감사합니다.

1. @tom-axisj 님 bootstrap에서는 class별로 API에 설명이 되어있어서 axisj API에도 있을 줄 알았습니다. (저같은 사람이 있을지도 모르니 파일을 참조하라고 보충설명이 있었으면 좋을 것 같습니다., 아니면 API를 다른 사람도 수정이 가능한가요?)

2. 샘플페이지에서는 용량제한이 있으므로 큰 용량에 대해서 확인할 수 없었습니다만, 제가 개발하고 있는 환경에서는 진행 상태가 보이지 않았습니다. 진행 상태가 보이지 않는다면 버그인건가요?

3. @hyunjun19 님 말씀대로 함수를 구현한다고 해도 확장자에 대한 아이콘 리소스 파일들이 없으므로 구현이 힘들 것 같습니다. 그래도 감사합니다!

**Comment by tom-axisj** [comment]
@webgori 
https://github.com/axisj-com/axisj/wiki 위키 페이지에 상세 설명을 만들려고 계획하는데요. 주요 라이브러리 들에 대한 사용기를 정리해두면 사용자 분들이 편하실 것 같습니다. 혹시 생각 있으시면 클론하시고 풀 리퀘 해주시면 됩니다.
만약 쉽게 잘 안되신다면 저도 같이 방법을 찾아보도록 하겠습니다.

2. 용량을 크게 해서 제가 테스트 해보겠습니다.

**Comment by tom-axisj** [comment]
테마에 프로그레스바 위치가 문제였습니다. 보여지는 위치로 조정을 하였습니다. 
데브 브랜치에있는 ui > arongi > AXUpload5.css 또는 AXJ.min.css 파일을 적용해 보십시요.

**Comment by groovedk** [comment]
:+1:

**Comment by webgori** [comment]
GitHub은 사용해본적이 없어서, 적응되면 해보겠습니다.~

**Comment by hyunjun19** [comment]
:+1:

**Comment by tom-axisj** [comment]
장기적으로 볼때 적응 하셔야 합니다. 이번일을 계기로 해보세요. 돈 드는 일도 아닌데요

**Comment by webgori** [comment]
@tom-axisj 님 조언 감사합니다.
프로그레스바 진행 상황은 말씀해주신 파일을 적용하였지만 정상적으로 진행되지 않습니다.
http://meltyway.kr/uploadTest.avi

**Comment by tom-axisj** [comment]
파일명 위에 겹쳐 보이는게 문제 이신거죠?

**Comment by webgori** [comment]
네
제가 볼때는 문제인듯 합니다.

**Comment by tom-axisj** [comment]
네 개선 하도록 할게요 일단 개발 그대로 진행 하시면 될 것 같아요. ^^

**Comment by lhslive** [comment]
:+1:

**Comment by webgori** [comment]
이런 경우에는 이슈를 닫아야되나요? 아니면 놔둬야될까요?

**Comment by tom-axisj** [comment]
나두시면 되요

**Comment by tom-axisj** [comment]
폴더 선택은 웹브라우저에서 지원하는 파일 선택 창이 지원을 안해주더라구요. 노드웹킷 같은 커스텀에서는 되구요.
폴더선택이 지원된다면 개발은 가능 하겠습니다. 플래시 버전 말고. html5 버전일때.
아 그리고 진행바 위치 문제 해결 했습니다.
