### ISSUE TITLE
질문좀 '-'/ 새해복마니받으세요 ..

### ISSUE THREAD

**Issue by yongjun0213** [axisj-com/axisj#381]
달력 쓰는걸 두개했더니 한쪽만 나와서요!   한개더나오게하는방법좀 .. 

                        {key:"b1", label:"행정업무시작일", width:"80", align:"center",formatter:function(){
                            return '<input type="text" name="" id="AXdate_'+this.index+'" class="AXInput W100 AXdate" value="'+ this.value +'" />';
                        }}, 
                        {key:"b2", label:"행정업무종료일", width:"80", align:"center",formatter:function(){
                            return '<input type="text" name="" id="AXdate_'+this.index+'" class="AXInput W100 AXdate" value="'+ this.value +'" />';
                        }}

**Comment by tom-axisj** [comment]
id 가 같아지게 되면서 생기는 문제 이지요

**Comment by yongjun0213** [comment]
감사합니다 '-'/

**Comment by groovedk** [comment]
:+1:
