### ISSUE TITLE
AXReq로 ajax요청시 onsucc 이벤트 질문입니다

### ISSUE THREAD

**Issue by wakeup5** [axisj-com/axisj#382]
new AXReq(url, {pars:pars, onsucc:function(res){/*코드*/});

현재 AXISJ를 CDN으로 사용하고 있는데

ajax로 받아오려는데 onsucc 함수가 실행 되지 않는거 같은데 코드 업데이트 하면서 수정된 점이 있는지요..

**Comment by wakeup5** [comment]
확인해 보니 onsuss가 아닌 onerr함수가 실행되네요..

일단 onerr로 처리하도록 했는데..

뭐가 문제인가요

**Comment by tom-axisj** [comment]
http://dev.axisj.com/samples/AXCore/AXReq-cdn-test.html 
cdn파일로 샘플링 한 페이지 입니다.
참고 하세요.
```
		AXConfig.AXReq: {
			async: true, // AJAX 비동기 처리 여부
			okCode: "ok", // 통신 성공 코드
			responseType: "", // AJAX responseType
			dataType: "", // AJAX return Data type
			contentType: "application/x-www-form-urlencoded; charset=UTF-8", // AJAX contentType
			dataSendMethod: "parameter", // AJAX parameter send type
			crossDomain: false,
			resultFormatter: function () { // onsucc formatter
				return this;
			}
		}
```

여기가 문제 일 수 있으니. 체크 하시구요.

**Comment by tom-axisj** [comment]
onerr로 연결되면 onsucc에서 에러가 발생하는 경우 입니다. onsucc 구문안을 try catch 해보세요.

**Comment by wakeup5** [comment]
아 그렇군요!

감사합니다 간단히 해결했네요
