### ISSUE TITLE
AXCalendar 칼렌다 쓰는방식이좀 질문이요.

### ISSUE THREAD

**Issue by yongjun0213** [axisj-com/axisj#383]
$(function() {
	  $("#datepicker1").datepicker({
	    	dateFormat: 'yy-mm-dd',
	        changeMonth: true, 
	         dayNames: ['월요일', '화요일', '수요일', '목요일', '금요일', '토요일', '일요일'],
	         dayNamesMin: ['월', '화', '수', '목', '금', '토', '일'], 
	         monthNamesShort: ['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월'],
	         monthNames: ['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월']
	  
	  });
	});

제쿼리 달력같은경우 id 값만 datepiker1 해주면 사용가능한데..

AXCalendar 경우 .... 그리드에서는.. 작동된든거같은데....
일반 페이지에서.. jsp 작동시킬려는데 선언하는부분이랑 쓸려면.. 셋팅해주는부분이 예매모호해서
혹시 셋팅법좀알수있을까요?

**Comment by lhslive** [comment]
http://dev.axisj.com/samples/AXInput/calendar.html
http://jdoc.axisj.com/jQueryExtends.html#bindDate

axisj를 사용하시기 전에 위 사이트에 나와 있는 샘플 페이지에서 소스보기를 한번씩만 하셔도 
질문을 올리시고 질문을 기다리시고 하는 시간정돈 줄이실 수 있으리라 생각합니다.
저희는 github의 bot이 아닙니다. 항상 용준님의 답변에 번개처럼 코멘트를 달아 드릴수는 없지요.
사용하심에 있어 답답하신줄은 알고 있지만 답답하시다면 그 답답함을 줄일 방법도 찾아 보셔야겠죠.

**Comment by yongjun0213** [comment]
죄송합니다. 샘플을 못찾았었네요
