### ISSUE TITLE
AXGrid에서 editor사용시 restful한 url사용

### ISSUE THREAD

**Issue by uneast** [axisj-com/axisj#384]
안녕하세요~

AXGrid에서 아래와 같이 editor의 ajaxUrl을 지정할 때
```
editor: {
  request: {ajaxUrl: "..."
}
```
/foo/${id}/edit와 같은 restful한 url을 생성하고 싶은데 어떻게 하면 될까요?

**Comment by tom-axisj** [comment]
Url에 들어가는 값은 String이구요.
위와 같은 스타일을 적용하시려면 
```
function getRestUrl(){
   return "";
}
```
같은 url 용 함수를 만드셔서.

ajaxUrl: getRestUrl() 으로 하시는게 맞을 것 같습니다.
다면 현재 method에 대한 설정이 빠져 있을 수 있는데요. 그 부분은 확장 해드릴 수 있습니다.

**Comment by tom-axisj** [comment]
제 답변이 이상하네요..

https://github.com/axisj-com/axisj/blob/master/samples/AXGrid/passive.html#L183
이 부분 보시면  editor.request를 선언하지 않고 editor.response를 사용 하고 있습니다.
이렇게 하면 그리드 에디터에서 데이터 전송을 하지 않고 사용자가 직접 할 수 있게 지원합니다.

이런 경우엔 editor.response 에서 직접 데이터 전송을 구현 하시는 편이 편하시 겠습니다.

**Comment by uneast** [comment]
:+1:
