### ISSUE TITLE
AXUpload5 onFileDrop 문제.

### ISSUE THREAD

**Issue by toskysee** [axisj-com/axisj#385]
onFileSelect function은 정상적이나 onFileDrop function 의  uploadedCount++; 명령의 위치가
잘못되어있어서 uploadMaxFileCount 계산을 잘못하고 있습니다.

onFileSelect function과 같이 하단 if문 안으로 옮겨야 할것같습니다.
"if((uploadedCount+queueCount) < cfg.uploadMaxFileCount || cfg.uploadMaxFileCount == 0){"

![image](https://cloud.githubusercontent.com/assets/6175643/5674161/577c6f50-97e9-11e4-8828-061214c0ebce.png)

**Comment by tom-axisj** [comment]
:+1:

**Comment by toskysee** [comment]
^^
