### ISSUE TITLE
IE8 상에서의 AXNotification문제

### ISSUE THREAD

**Issue by lhslive** [axisj-com/axisj#386]
안녕하세요. ISSUE를 남기는건 오랜만인듯 합니다.
여기 환경상의 문제인지는 모르겠지만 IE8 상에서 AXNotification의 CONFIRM BUTTON이 존재 할 시 
AXNotificationTray div 는 닫히지만 button이 늦게 사라지는 현상이 발견되고 있습니다.
![k-16](https://cloud.githubusercontent.com/assets/7547764/5699429/028edbac-9a6b-11e4-832a-345ddbf7ddba.jpg)
![k-17](https://cloud.githubusercontent.com/assets/7547764/5699430/05b4fb18-9a6b-11e4-9ca5-3d9c429ede89.jpg)
![k-18](https://cloud.githubusercontent.com/assets/7547764/5699431/0b02c834-9a6b-11e4-8450-dc063e339e2e.jpg)
![k-20](https://cloud.githubusercontent.com/assets/7547764/5699432/0f3aeaa8-9a6b-11e4-94ea-c744557637e4.jpg)
일단 저는 급한대로 fadeOut시  하드코딩 신공으로 무시해 버렸습니다 ㅠㅠ..끝이 안보이네요

**Comment by tom-axisj** [comment]
재미 있는 현상 이네요 ^^

**Comment by lhslive** [comment]
걍 여기 설정상의 문제 때문이라면 차라리 좋겠네요. 해결 본듯 하거든요 ㅎㅎ

**Comment by hyunjun19** [comment]
IE11에서 IE8 에뮬레이트 모드로 해도 동일증상이 나타나네요.

**Comment by tom-axisj** [comment]
버그 해결 되었습니다.

**Comment by hyunjun19** [comment]
출시된지 6년이 다 되가는 브라우저를 지원하기 위해 추가되는 코드들...
마소가 정말 밉네요. =ㅅ=

**Comment by lhslive** [comment]
언제 어디서 어떤식으로든 통수를 칩니다 ..
버릴수가 없어요. ㅠㅠ 
빠른 해결 정말 감사합니다.
:+1: 
:100:

**Comment by hyunjun19** [comment]
:+1:
