### ISSUE TITLE
AXGrid에서 checkbox관련 문의

### ISSUE THREAD

**Issue by uneast** [axisj-com/axisj#387]
안녕하세요~
AXGrid사용시 checkbox관련 문제로 삽질 중인데 도움 부탁드립니다. ㅠ

1. 
head에서 colspan, rowspan을 쓰는데
checkbox를 사용하는 컬럼에서 displayLabel: true 옵션을 주어도 label에 checkbox가 나오네요
혹시 span이 들어가는 경우 사용법이 틀린지 확인 부탁드립니다. 

2. 
editor사용시 checkbox를 아래와 같이 설정했는데 
제대로 편집폼을 생성 못하고 중간에 멈추고 있는데 제대로 설정하는 방법이 어떤건가요? ㅠ
```
editor: {
    rows: [
        [
        	...
            {colSeq: 15, align: "left", valign: "middle", form: {type:"checkbox", value: "itemValue", options:[{optionValue:"true", optionText:""}]}},
```

**Comment by tom-axisj** [comment]
1. formatter 가 checkbox 이면 체크박스를 없앨수 없애 고정되어 있습니다. 다만
```
{key:"no", label:"no", width:"80", align:"center", formatter:"checkbox", formatterLabel:"전체선택"}
```
에서 처럼 formatterLabel 값으로 체크박스 옆에 라벨을 넣을 수는 있습니다.

2. 테스트 해본 결과로는
```
{
     colSeq:1, align:"center", valign:"middle",
     form:{
        type:"checkbox", value:"itemValue", options:[
	     {value:'장기영', text:''}
	]
     }
}
```
처럼 해보십시요.  제가. optionValue로는 처리를 안해놨네요. 일관성을 지키지 못했습니다.
좀더 노력해야 겠습니다. optionValue말고 value, text로 해보십시요. 불편을 드린것 같습니다.

**Comment by groovedk** [comment]
:+1:

**Comment by uneast** [comment]
:+1:

**Comment by uneast** [comment]
@tom-axisj 
2번 케이스는 여전히 안 되어서 AXGrid.getEditorFormValue함수에
아래와 같이 console.log를 찍으면 1번은 찍히나 2번로그가 안 찍히네요 
value의 값은 true인데 이 경우 desc()함수가 제대로 동작 안 하는 듯 한데 확인 부탁드리겠습니다. 
```
var getFormValue = function (formvalue, value) {
			if (formvalue == "itemValue" || formvalue == "itemText") {
				if (axdom.isArray(value)) {
					return value;
				} else {
                    1. console.log(formvalue, value)
                    2. console.log((value || "").dec())
					return (value || "").dec();
				}
```

**Comment by hyunjun19** [comment]
value가 String인지 Boolean인지 확인해 보셨나요?
아래처럼 사용해 보세요.
그리고 기왕이면 콘솔에 어떻게 찍혔는지 콘솔 내용도 같이 올려주시면 더 좋습니다. ^^

```
return String(value || "").dec();
```

**Comment by tom-axisj** [comment]
예외처리 한 버전을 커밋 했습니다.

https://github.com/axisj-com/axisj/blob/dev/lib/AXGrid.js

**Comment by uneast** [comment]
감사합니다.~

**Comment by hyunjun19** [comment]
아~ AXGrid에서 나는 오류였군요. ^^;;
:+1:

**Comment by tom-axisj** [comment]
grid 에 들어가는 list데이터에 boolean 이 있는데 editor에서 dec를 못하는 문제 였어요.

**Comment by lhslive** [comment]
:+1:
