### ISSUE TITLE
Grid 하단에 page: { display: true } 시 count 수?

### ISSUE THREAD

**Issue by jhanho78** [axisj-com/axisj#388]
안녕하세요?

page:{
 display: true
}
를 주면 아래 하단에 count(s)가 표시되는데

ajax로 값을 Grid에 처음에 뿌려주면 "0"으로 나옵니다.

그런데 브라우져 창을 resize 해주면 카운트가 제대로 표시됩니다.

다른 설정이 있는 건지? ajax로 해당 카운트 값을 넘겨줘야 하는건지요?

**Comment by tom-axisj** [comment]
이게 좀 민망하지만 이렇습니다.
resize할땐 list.length를 이용해서 하단에 count를 다시 출력하고 있어서 생기는 문제 인데요.
대부분은 list.length와 서버 json에서 주는 page.count 값과 같아서 문제가 없습니다.

서버 JSON
```
{
	list:[],
	page:{
		pageNo:1, // 현재 페이지 번호
		pageCount:20, // 페이지 갯수(아이템 갯수가 아님니다.)
		listCount:100 // 아이템 갯수
	}
}
```
으로 값을 주셔야 합니다.
그리고 setConfig 에서 
```
page:{
	paging:true,
	pageNo:1,
	pageSize:100
}
```
으로 정의한 속성이 서버측에 파라미터로 전달 되게 됩니다.
이 파라미터를 이용하여 페이징을 구현하셔야 하는 거지요. 이렇게 해서 서버측에서 전달해준 pageCount 값으로 페이지선택 select 박스를 만들어내게 됩니다.

**Comment by lhslive** [comment]
list 자체에 변화가 없으시다면 setList  호출시 
```
                onLoad:function(){
                   myGrid.setStatus(myGrid..list.length);
                }
```
로 해결 하셔도 됩니다.
