### ISSUE TITLE
테마 Archon에서 문의 드립니다.

### ISSUE THREAD

**Issue by beginnerkht** [axisj-com/axisj#389]
안녕하세요? 

axisj 테마중 Archon에서 테스트 중인데
		formCheck: function () {
			var result = validate("modalForm");
	        if (!result) return false;
			fnObj.formSave();
	    },
이부분에서 validate("modalForm")를 못불러오는거 같은데 

js를 따로 불러와야 하는지 문의 드려봅니다.

**Comment by tom-axisj** [comment]
@groovedk

**Comment by beginnerkht** [comment]
validate를 왜 안먹을까요...

**Comment by hyunjun19** [comment]
저 소스코드가 어느 페이지에 있는건가요?

**Comment by tom-axisj** [comment]
샘플제작할때 validate 라는 함수를 빼 먹은것 입니다. axvalidate라는 클래스가 있는데요. 그걸 호출 해야 하는데 옮기다가 실수 한 것으로 보입니다. 

무시하시면 되겠습니다. 
보그 찾아주셔서 감사합니다

**Comment by beginnerkht** [comment]
답변 감사드립니다~
