### ISSUE TITLE
AXUpload5 Window용 Safari 에서 정상작동 안하는 문제.

### ISSUE THREAD

**Issue by toskysee** [axisj-com/axisj#390]
늘 감사하게 사용하고있어요~
오늘은 제목에 말씀드린바와 같이 AXUpload5 가 Safari 5.1.7 (Windows) 버젼에서 
정상작동을 하지 않아 이슈를 남깁니다.
확인 부탁드립니다.^^

![image](https://cloud.githubusercontent.com/assets/6175643/5770927/e3b56b6a-9d76-11e4-809d-d1025f5af89f.png)

**Comment by tom-axisj** [comment]
제가 테스트를 해봤습니다. 
그 브라우저가 사면 초가네요.
일단 html5 file support가 안되구요. 대안인 flash도 기본 지원이 안됩니다.
flash 플레이어를 설치 하면 될 것으로 기대 합니다.

**Comment by tom-axisj** [comment]
http://get.adobe.com/kr/flashplayer/

**Comment by toskysee** [comment]
확인 감사합니다.^^
