### ISSUE TITLE
dialog.push 이후 focus 질문드립니다.

### ISSUE THREAD

**Issue by ryoueunsun** [axisj-com/axisj#392]
안녕하세요~ 질문이 있어서 글 올립니다.

var msg = myValidator.getErrorMessage();
dialog.push(msg);
myValidator.getErrorElement().focus();

처음에 focus가 되긴 하는데 
dialog.push 후 확인 버튼을 누르고 나면 포커스를 잃는거 같습니다.
alert으로 뿌려줄 때에는 포커스를 잃지 않거든요~~

dialog.push 이걸 꼭 쓰고 싶긴 한데 ㅠㅠ
혹시 다른 방법이 있을까요?

**Comment by hyunjun19** [comment]
현재는 `dialog.push`에 callback이 없어서 기본 API로는 힘들것 같습니다.
`dialog.push(msg)`대신 `toast.push(msg)`를 사용하는 것도 하나의 대안인것 같습니다.

**Comment by ryoueunsun** [comment]
toast.push(msg)도 괜찮긴 할꺼 같은데요... 저 혼자 사용하기에는 나쁘지 않으나 .. ㅋㅋ
싫다고 하실 관리자분이 있으셔서 고민이네요 ㅠㅠ
디자인을 버리고 alert로 가야될지 -_-;;;;;;;;;;

**Comment by hyunjun19** [comment]
버튼별 callback 메서드 구현해야겠네요...

지금 당장 필요하다면 이렇게...
```
var msg  = myValidator.getErrorMessage();
var elem = myValidator.getErrorElement();
function fnValidMessage (msg, elem) {
	var btnCss = 'valid-confirm';
	dialog.push({
		type   : 'Caution',
		title  : 'header message',
		body   : msg,
		buttons: [ 
			{ buttonValue: '확인1', buttonClass: btnCss }
		] 
	});
	
	$('.' + btnCss).click(elem.focus());
}
```

**Comment by ryoueunsun** [comment]
saveForm: function(){
			var validateResult = myValidator.validate();

			function fnValidMessage (msg, elem) {
				var btnCss = 'valid-confirm';
				dialog.push({
					type   : 'Caution',
					title  : 'header message',
					body   : msg,
					buttons: [ 
						{ buttonValue: '확인1', buttonClass: btnCss }
					] 
				});

				$('.' + btnCss).click(elem.focus());
			}

			if (!validateResult) {
				var msg = myValidator.getErrorMessage();
				var elem = myValidator.getErrorElement();
				fnValidMessage(msg,elem);
				myValidator.getErrorElement().focus();
				return false;
			}else{
				document.myForm.submit();
			}


이렇게 돌려보고 있는데도 안됩니다~
잘못된 부분이 있을까요?

**Comment by hyunjun19** [comment]
제가 소스코드를 잘못 봤네요... ^^;;
아래처럼 buttons에 onClick 함수를 주시면 됩니다.

```
dialog.push({
	type   : 'Caution',
	title  : 'header message',
	body   : 'test',
	buttons: [ 
		{ buttonValue: '확인1', buttonClass: 'test', onClick: function(){ console.log(this); } }
	] 
});
```

**Comment by ryoueunsun** [comment]
잘 됩니다!!
감사드려요!!
빠른 피드백 짱짱입니다~

**Comment by tom-axisj** [comment]
@ryoueunsun 이런 배신감이 우리 깃 별표를 안눌르다니~~

**Comment by ryoueunsun** [comment]
제가 아직 github의 사용법을 몰라서요 ㅠㅠ 죄송합니다 ㅠㅠ

**Comment by tom-axisj** [comment]
농담이었어요 ㅎㅎ
제가 죄송

**Comment by hyunjun19** [comment]
:+1:
