### ISSUE TITLE
AXSelect isspace 설정 문의.

### ISSUE THREAD

**Issue by dkswjdals89** [axisj-com/axisj#394]
안녕하세요? 이번에 Axisj를 사용하여 프로젝트를 진행중인 개발자입니다.

다름이 아니라 현재 AXSelect의 Ajax 방식을 이용해서 셀렉터 박스 리스트 내용을 동적으로 로드하여 
잘사용하고 있는데요. AXSelect 바인딩 설정시, isspace, isspaceTitle 이 두가지 값을 이용해서, 디폴트 옵션을 추가하도록 사용하고 있는데요.
사용하다보니 이 디폴트 옵션의 값이 모두 공백으로 기본적으로 사용되고 있더군요.  디폴트 옵션을 특정 값으로 세팅해주고 싶을 경우에 따로 설정값이 있는지 궁금합니다.
살짝 AXSelect.js 파일을 열어서 확인해보았을떄는 없는것 같군요. 
API 문서에도 따로 보이질 않아서 문의 드립니다!~

**Comment by dkswjdals89** [comment]
이슈를 올리고 좀더 AXSelect.js를 살펴보았는데 따로 디폴트 옵션 값 설정이 없는듯 하여, 임의로 스크립트를 아래와 같이 수정해보니 원하는 결과를 얻었네요. Ajax 사용시에만 적용될듯 보이네요. 제가 수정한 부분은..
AXSelect.js 343번 라인부터
'''if (obj.config.isspace) {
							// 설정에 Value 값이 없으면 공백, 있으면 설정된 Value값 적용.
							var optionValue = obj.config.isspaceValue == null ? "" : obj.config.isspaceValue;
							po.push("<option value=\"" + optionValue + "\">" + obj.config.isspaceTitle + "</option>");
						}'''

**Comment by tom-axisj** [comment]
:+1:
