### ISSUE TITLE
AX Grid SetList Ajax Error 처리 관련.

### ISSUE THREAD

**Issue by dkswjdals89** [axisj-com/axisj#398]
안녕하세요?
현재 Axisj를 잘 사용하고 있는데요,
AXGrid에서 setList함수로 ajax 콜하여 그리드에 데이터를 뿌려주고 있는데요. 
서버에서 401 혹은 500 에러로 인해 데이터를 가져오지 못할 경우에, onError 이벤트에서 상태 코드에 따른 처리를 하려고 하는데 현재 AXGrid에서는 ajax 콜 해서 에러가 발생할 때에 대한것은 onError 이벤트를 호출하지 않는것 같습니다. 오직 200 OK 상태에서 result 값이 ok가 아닌경우에만 onError 이벤트를 호출하네요.
아래의 코드처럼 혹시 AXGrid 수정이 가능할지요?
AXGrid.js의 setList 함수에서 ajax 콜 에러 처리부분만 추가로 넣은 코드입니다.

```javascript
new AXReq(url, { 
	type : _method, 
	contentType : _contentType, 
	responseType : _responseType, 
	dataType : _dataType, 
	headers : _headers, 
	debug : obj.debug, 
	pars : pars, 
	onsucc : function(res){
		if ((res.result && res.result == AXConfig.AXReq.okCode) || (res.result == undefined && !res.error)){
			res._sortDisable = sortDisable;
			if (obj.response){
				obj.response.call(res);
			}
			else{
				ajaxGetList(res);
			}
			if (obj.onLoad)
				obj.onLoad.call(res);
		}
		else{
			if (obj.onError)
				obj.onError.call(res);
			else
				AXUtil.alert(res);
		}
	}, 
	onerr: function(res){
		if (obj.onError)
			obj.onError.call(res);
		else
			AXUtil.alert(res.statusText);
	}
});
```

그리고 혹시 저번에 Select Option 디폴트 Value 값 적용에 관한 내용 혹시 axisj 버전업에 포함이 될련지요? 만일 안된다면 현재 진행하는 프로젝트에서 제가 직접 수정한 부분만 관리해서 매번 axisj 버전업 할때마다 손봐줘야할거 같아서요. ㅎㅎ

**Comment by tom-axisj** [comment]
https://github.com/axisj-com/axisj/commit/e3749139e12583c57e65df40c38042b660dae2a5 여기에 select관련한 코드 추가 되었구요.
지금은 dev 브랜치에 있는 것이고 릴리즈에 추가 되려면 이달말에 새로운 릴리즈가 만들어 집니다.

그리고 코드 추가는 해드릴 수 있겠는데욤. 그 보단.. 원래 이게 포크를 뜬 다음에 pull Request 날리시는 방식이에요 
그럼 코드를 보고 머지를 하거든요.
다음번에는 pull request에 도전해 보시는 것을 추천합니다.

**Comment by dkswjdals89** [comment]
제가 Git 자체를 한번도 안써봐서... 말씀하신것은 제가 직접 코드를 수정해서 Pull Request로 올리면 코드가 올바르고 적합한지를 확인하고서 머지한다는 말씀인거죠? ㅎㅎ
한번 Git하고 Git Hub 사용에 대해서 공부좀 해보고 도전해봐야겠네요!

**Comment by tom-axisj** [comment]
@dkswjdals89 맞습니다. 그럼 님 계정으로 저희 깃 커미터 로그도 남고 소스의 히스토리도 나오니까요 아름다운 일이죠~

**Comment by hyunjun19** [comment]
@dkswjdals89 :+1:

**Comment by tom-axisj** [comment]
아 그리고 그렇게 풀 리퀘 하시다가 팀원들이 모두 인정하면 공식 커미터 되시고 홈페이지에 사진과 이름이 올라가고 또 공식 커미터 명함도 만들어 드립니다. 

거기에 저희 팀 내부 커뮤니티에 접속 하실 수 있게 되어 모다 다양한 정보를 얻으실 수 있습니다.
기회가 잘 되어 발표나 대회 나가면 입상 할 기회도 있겠네요
