### ISSUE TITLE
mergeCells 질문드립니다.

### ISSUE THREAD

**Issue by ryoueunsun** [axisj-com/axisj#400]
안녕하세요.
또 문의를 드리네요. 아하하하;;
ㅠㅠ

![1](https://cloud.githubusercontent.com/assets/10161180/5914487/7b01dc90-a639-11e4-9bad-09d897309d9f.PNG)

첨부된 화면과 같이 머지셀 하고 싶습니다만..
체크박스일 경우에는 머지가 안됩니다.

체크박스도 머지가 되었으면 하는데 좋은 방법이 없을까요?

늘 감사드립니다 ㅠㅠ

**Comment by tom-axisj** [comment]
이런 경우라면 http://dev.axisj.com/samples/AXGrid/body.html 이 샘플로 해보시는게 좋을 것 같은데요.
머지 셀로는 레코드를 하나로 처리 할 순 없어요.
그리고 버그 알려주셨는데 빨리 해결 못하고 있습니다.

먹고 살아야 하다보니. 마음 한족이 항상 무겁습니다.

![d11-41-11-03-](https://cloud.githubusercontent.com/assets/5884902/5915841/d9ba0366-a64d-11e4-9c45-2eb1cfce357c.png)

**Comment by ryoueunsun** [comment]
정답은 아니지만 꼼수로 -_-;;;;; 해결했습니다.
어차피 checkbox일 경우에만 사용할 것이기 때문에
AXJ.min.js 선언하고 그 밑에 AXGrid.js 재 선언한 후에,
체크박스의 class name을 맞춰주니 value값만 다르게 인식되어 머지가 되네요.
여기서 좀 더 머리를 쓰면 될 것 같은데 2일 동안 잡고 있다보니 더 이상 잡고 있기 힘드네요 ㅠㅠ

항상 고생이 많으십니다......
먹고 사는 문제는 항상 힘들고 어려운 문제죠.
힘내세요 ^^
