### ISSUE TITLE
AXModal iframe 페이지 이동 관련 이슈.

### ISSUE THREAD

**Issue by dkswjdals89** [axisj-com/axisj#405]
안녕하세요?
최근에 Axisj를 알게되고 프로젝트에 직접 사용하면서 JavaScript에 관심이 많이 생긴 개발자입니다!
저번에 말씀해주신 Pull requests 해서 오픈소스에 참여하는것은 나름 시간날때마다 조금씩 공부하는중인데 Git를 안써봐서 그런지 조금 접근하기가 어렵네요! 조만간 도전해보겠습니다.!

아참 본론으로 들어가서, 현재 AXModal을 이용해서 iframe으로 다른 페이지를 호출해서 사용하고 있는데요.  모달 내부에서 페이지 이동을 하고나면 parent 객체 접근이 보안 문제로 접근할 수 없다고 하는데요, 신기한것은 크롬에서는 아무 문제 없이 parent 객체에 접근해서 모달을 닫을수가 있더군요. 혹시 이부분에 대해서 해결 방법이 없을지 궁금해서 이슈 남겨봅니다. 몇일동안 혼자 고민해봤는데 페이지 이동을 모달을 닫고 새로 다음 페이지로 여는 방법 외에는 해결책이 생각나지 않네요 ㅠㅠ 찾아보니 HTML5에 새로 생긴 Cross Document Messaging을 사용하라는 말도 있네요. ㅎㅎ

**Comment by tom-axisj** [comment]
제 경험을 말씀드리면 도메인이 조금만 달라도 권한이 없다고 나올 수 있었습니다.
부모창과 모달프레임 도메인을 체크 하셔야 할 것 같습니다.
만약 잘 안되시면 저희가 볼수 있는 URL를 주세요.

**Comment by dkswjdals89** [comment]
음 말씀하신데로 도메인 부분을 부모창과 모달 창을 동일하게 맞춰주니 일단 문제는 해결되는듯 하네요! 감사합니다.
