### ISSUE TITLE
AXGrid - 체크박스 질문입니다.

### ISSUE THREAD

**Issue by gaedong2** [axisj-com/axisj#408]
그리드에서 체크박스 사용하는 방법이 궁금합니다. 

예를 들어 디비에 Y,N 이란 값이 들어있다고하면

formatter:"checkbox" 를 컬럼그룹으로 잡아주고

디비에서 조회해 올때  Y 를 true 로 ... N 을 false 로 변경해줘야 하는건지요??

저장또한 마찬가지로 변경을해서 넣어줘야하는것인지요..

타 그리드에서 사용하던걸 이용하려니 궁금한게 많아 죄송합니다.ㅜㅜ

**Comment by tom-axisj** [comment]
```
{key:"no", label:"no", width:"80", align:"center", formatter:"checkbox", checked:function(){
    return this.item.___checked && this.item.___checked["1"];
}},
```
에서 처럼 formatter 다음에 checked를 사용하셔야 합니다.
그럼 데이터에서 어떤 형태로 준다고 해도 this.item.mykey == "Y" 이런식으로 하실 수 있겠죠.
return true이면 체크박스가 체크 됩니다.
단 이걸 쓰실때는 반드시 this.item.___checked && this.item.___checked["1"] 이 값을 or 조건으로 해주셔야 사용자가 선택한 값도 제대로 표현 됩니다.

개발자가 checked를 선언하면 내부에서 checked비교 하던게 무시 되거든요.
```
 this.item.___checked["1"]
```
에서 1은 컬럼 순번입니다.

**Comment by tom-axisj** [comment]
사진이 바뀌니 좋으네요

**Comment by gaedong2** [comment]
'''
{key:"USEYN", label:"사용", width:"100", align:"center",
                                	formatter:"checkbox", checked:function(){
                                	    if(this.item.USEYN == "Y"){
                                	    	return true;
                                	    }
                                	    else {
                                	    	return false;
                                	    }
                                	
                                	},
                                	editor: {
                                        updateWith: ["status"]  //수정후 영향이 받는컬럼
                                    }
                                },
'''
코드는 이렇게 썼습니다...

제가  이해도가 좀 낮아 설명해주신
----
단 이걸 쓰실때는 반드시 this.item.___checked && this.item.___checked["1"] 이 값을 or 조건으로 해주셔야 사용자가 선택한 값도 제대로 표현 됩니다.
----

이부분이 이해가 가질 않습니다. ㅜㅜ

체크가 잘 표현되긴하지만...
저장할때 체크가 되지 않은 놈에게 N값을 어떻게 줘야하는지도 또다른 숙제이군요..


![snag-0038](https://cloud.githubusercontent.com/assets/6636004/6076451/ec8713e0-ae26-11e4-9672-44de920a1930.png)
이렇게 가져왔지만...

체크박스를 선택 삭제 용도가 아닌 
코드 사용여부로 사용할경우... 컬럼해더에 제목대신 천체 선택이 나와버리네요 

![snag-0039](https://cloud.githubusercontent.com/assets/6636004/6076462/0c47cf80-ae27-11e4-8548-b8058d07015e.png)

인라인에디터가 개발중이신데 제가 계속 물어봐서 죄송하네요
체크박스에 마우스를 클릭을 하게 되면 체크해제가 되지만.. '상태' 컬럼에 수정이라고 나오지 않네요..

그리고 마우스를 체크박스가 아닌 다른쪽에 클릭을 하게 되면 그림과 같이 그냥 "Y" 란 값이 돌출되어버립니다.

**Comment by tom-axisj** [comment]
이런 용도로 하는건 inline editor 타입에 checkbox를 받아주도록 변경을 해야 하구요.

this.item은 리스트의 아이템입니다.
그 아이템에 서버에서 정의한 키가 여럿이 달려있죠.
그중에 특정값이 원하는 값이면 체크박스에 체크표시를 할 수 있어요.

checked: function 을 이용해서
그런데 사용자가 체크박스 선택을 하면 이건 서버에서 정의한 키로 할당 할수가 없습니다.
해서 내부에 ___checked[0]  하는 내부 키에 값을 저장합니다.
그러니 

___checked 가 있으면서
___checked[0] 이 true 이면서
mykey 가 Y인 경우를 true 로 판단해야 합니다.

**Comment by tom-axisj** [comment]
inline editor 에서 checkbox를 받아주는 것은 추가 되는 데로 알려드리겠습니다.

**Comment by tom-axisj** [comment]
http://dev.axisj.com/samples/AXGrid/inline-edit.html 이렇게 하면 해결이 된 것 같습니다.

**Comment by gaedong2** [comment]
감사합니다. ^^ 소스수정이 최고이십니다. !!
