### ISSUE TITLE
[AXUpload5] 웹뷰로 감쌌을 경우 파일 삭제 이슈 

### ISSUE THREAD

**Issue by icran** [axisj-com/axisj#409]
안녕하세요. 개인적으로 웹앱을 만드는데 axisj 에 많은 도움을 받고 있는 개발자입니다.
웹과 모바일 웹등에서는 잘 작동하지만 웹앱으로 웹을 감쌌을 경우 
AXUpload5 파일 업로드중에서 전체삭제 기능과 부분 삭제기능이 제대로 작동 안하는 부분을 
발견했습니다. 

그래서 디버깅을 해보니 axisj v1.0.13 기준 2288 번째 라인에 삭제시 활용되는 
deleteSelect: function(arg, withOutServer) 에서 
업로드된 파일 갯수가 1개 이상임에도 불구하고  this.uploadedList.length가 계속해서 1로 
잡히는 문제를 발견했습니다. 

그로 인해 
			jQuery.each(this.uploadedList, function(){
				deleteQueue.push(this.id);
			});
이 부분도 한번만 타게 되어 전체 삭제 버튼을 눌러도 한개만 삭제가 되는 문제가 있습니다. 
혹시 시간되신다면 이 부분에 대해 알려주신다면 너무 감사하겠습니다. 

테스트 : 안드로이드 4.1 ~ 4.4.x 웹뷰 
( 추신 : 모바일웹에서는 잘 작동됩니다.  앱에서만 문제. ) 

항상 고맙습니다.

**Comment by icran** [comment]
번거롭게 해서 죄송합니다. 
제가 특정 안드로이드 버전만 커스텀하게 오버라이딩한 소스에 문제로 확인되었습니다.
( 이슈가 삭제가 안되서 댓글로 남깁니다.. )

**Comment by tom-axisj** [comment]
:+1:
