### ISSUE TITLE
axupload5 질문입니다.

### ISSUE THREAD

**Issue by llois** [axisj-com/axisj#411]
너무 초보같은 질문이라 죄송합니다.

올려주신 샘플을 참고하여 업로드 잘 되고, Get Object나 Get Param 버튼 클릭시 정보도 잘 뜹니다.

그런데 이제 업로드 된 파일들의 정보들을 받아서 (파일이름같은..) DB에 입력 해야 하는데
이런 개별적인 값을 어떻게 받아와야 하는지 잘 모르겠습니다.

get object 안에 있는 내용으로 하면 될거 같은데 잘 안되네요.

감사합니다. 부탁 드리겠습니다.

**Comment by hyunjun19** [comment]
서버단은 아까 질문보니 ASP이신거 같던데...
파일 업로드시에 파일정보도 같이 보내집니다.

아래 이미지를 보시면 파일 업로드시 여러 파라미터도 같이 보낼 수 있습니다.
이건 HTTP spec이니 PHP, Java, ASP 모두 동일합니다.
그러니 ASP file upload로 검색해보시면 원하시는 답을 찾을 수 있을꺼라 생각됩니다.

![image](https://cloud.githubusercontent.com/assets/421863/6129482/24eaaa86-b182-11e4-8989-5cbd98028f11.png)

덧글: 저도 알려드리고 싶지만 Java 개발자라...

**Comment by llois** [comment]
답변 감사합니다!

그런데 다름이 아니오라 서버단으로 넘어가기 전에, jQuery 상에서 업로드 개별 정보를 얻고 싶습니다.

예를 들면 submit 버튼 누르기 전에 FileName을 얻어와서 ajax로 썸네일이미지를 뿌려주던가 하는 작업이 필요합니다.

늦은 시간까지 빠른 답변 너무 감사합니다!

**Comment by hyunjun19** [comment]
http://dev.axisj.com/samples/AXUpload5/index.html 샘플에서 아래 코드를 테스트 해보세요.

```js
	...
	onbeforeFileSelect: function(){
		trace(this);
		return true; // [fn] - 드랍되거나 파일이 선택되기 전에 이벤트 return true; 리턴하지 않으면 진행을 중지 합니다.
	},
	...
``

**Comment by tom-axisj** [comment]
업로드 전에 파일의 선택된 정보를 리드하는것은 제한적이어서 어렵습니다.
요즘 브라우저들이 로컬정보 접근을 제한하고 있어서요.
예를 들어 썸네일뿌리는건 특히나 쉽지 않구요. 

서버에 일단 템프로 업로드 후에 서버 전송하면 링크 하고 템프에서 이동시키는 방법을 주로 사용합니다.
파일 선택되자마자 서버에 업로드를 하는 것이지요.
