### ISSUE TITLE
axupload5 uploadQueueBox 영역 모바일에서 스크롤 이슈 질문드립니다.

### ISSUE THREAD

**Issue by icran** [axisj-com/axisj#412]
안녕하십니까. 
너무나 잘 만들어주신 axupload5 를 잘 사용중에 있습니다. 

간추린 이슈 내용 : 
현재 모바일에서 axupload5 의 uploadQueueBox 영역이 스크롤이 안되는 이슈가 있습니다. 
혹시 그런 이슈가 있는지 아니면 제가 해당 옵션등이 있는데 모르는 건지 알고 싶습니다.

자세한 내용 : 
스크린샷에 보면 4개의 이미지를 올렸고, 
그 이미지들을 감싸는 boarder ( uploadQueueBox ) 가 있습니다. 
이 부분이 전체적 스크롤을 방해하는것 같습니다.  
( 예를들어 10장의 이미지를 세로로 넣었다고 가정시 문제가 될 확률이 있을것 같습니다. )
<img src="https://cloud.githubusercontent.com/assets/5636572/6146387/6ae97a28-b22f-11e4-9774-67d1a4ff9b0b.png" />

항상 고맙습니다. 

혹시 아래 부분이 영향이 있는지 싶어서 해보았는데 하하;; 안되더군요 
$("#uploadQueueBox").removeClass("allowDrop");
$("#uploadQueueBox").removeClass("onDrop");
$("#uploadQueueBox_dropZoneBox").hide();

**Comment by tom-axisj** [comment]
같은 현상 재현이 안되고 있습니다. 콘솔에서 스타일 정보를 캡쳐해서 보내주시거나. 문제가 되는 페이지를 제가 한번 볼 수 있으면 좋을 것 같습니다.

**Comment by tom-axisj** [comment]
안되는 브라우저정보도 주세요

**Comment by icran** [comment]
브라우저는 모바일 크롬과 기본 인터넷 입니다. 
PC 웹에서 마우스로 스크롤할때는 되지만 모바일로 작동시 문제가 있는것 같습니다. 
확인 안드로이드 버전 : 4.3, 4.4.2, 4.4.4 
입니다. 

답변 남겨주셔서 고맙습니다.

**Comment by icran** [comment]
좀더 자세한 정보입니다. ( 웹에서는 잘 되지만 모바일에서 스크롤 안되는 이슈 ) 

해당 엘리먼트 정보 : 
<img src="https://cloud.githubusercontent.com/assets/5636572/6160580/2b0d11ca-b2a8-11e4-989d-c69b22c4ee5e.png"/>

해당 엘리먼트에 바인드된 JQuery 이벤트 정보 
<img src="https://cloud.githubusercontent.com/assets/5636572/6160589/4a98f298-b2a8-11e4-81bd-13a341a73ef1.png"/>

해당 엘리먼트의 Styles 
<img src="https://cloud.githubusercontent.com/assets/5636572/6160596/627bf1a8-b2a8-11e4-9310-48e4293f2aeb.png" />

바쁜시간 내주셔서 고맙습니다.

**Comment by tom-axisj** [comment]
theme.css는 저희 파일이 아닌것 같아요.
어쨋든

.AXUpload5QueueBox 에 overflow:auto 속성이 없어서 생기는 문제 입니다.
추가해주세요.

**Comment by tom-axisj** [comment]
아 모바일이슈라면 height:auto 로 변경하고 overflow:visible해야 될것 같네요.
안드로이드 구 버전에서는 스크롤이 안되니까요. 스크롤 안되는 브라우저인 경우 스크롤 안하도록 설정을 변경해야 겠습니다.

**Comment by icran** [comment]
고맙습니다. 응용해서 잘 풀었습니다. 
다시 한번 감사합니다.
