### ISSUE TITLE
업로드 문의드립니다.

### ISSUE THREAD

**Issue by gaedong2** [axisj-com/axisj#414]
이제 업로드 컨트롤에 대해서 살펴보고있는데요...

업로드후 읽기전용 방법은

인터넷에 떠돌아 다니는방법으로 구현해야하나요??

괜히 열심히 만들었다가 엑시스제이에 그런기능이 이 있으면 허탈할것 같습니다. ㅎㅎ

**Comment by tom-axisj** [comment]
오늘 업로드의 날이네요

업로드후 읽기전용 방법이라는 건 삭제가 안되게 해달라는 말씀인가요?

**Comment by gaedong2** [comment]
네  더이상 추가도 안되고 다운만.받을수 있게요

**Comment by tom-axisj** [comment]
추가 하신 분이 있어요 코드 확인해보고 알려드릴게요

**Comment by tom-axisj** [comment]
```
myUpload.setConfig({
	targetID:"AXUpload5",               //{String} - 업로드 버튼 엘리먼트 아이디
	openMode: "view",                   //{String} - 업로드된 파일 삭제 아이콘 숨김
```

openMode: "view"를 추가하면 업로드된 아이템에 파일 삭제 아이콘이 사라집니다.
그렇다고 삭제 메소드가 안되거나 하진 않습니다.

**Comment by gaedong2** [comment]
감사합니다.

저와같은사람이 있을것 같은데

http://dev.axisj.com/samples/AXUpload5/index.html 
설명란에 추가되었으면 좋겠습니다.

**Comment by tom-axisj** [comment]
직접 한번 참여 해보시는 것도~

**Comment by beginnerkht** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

younggubabo@naver.com 님께 보내신 메일 <Re: [axisj] 업로드 문의드립니다. (#414)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by gaedong2** [comment]
해보고 싶은 마음은 굴뚝같으나..
Git 에 울렁증이 있어서요  방법을 잘몰라서요..

3월에 오시면 한번 배워봐야겠네요 ㅎ
