### ISSUE TITLE
다음페이지 버튼을 눌렀는데 

### ISSUE THREAD

**Issue by haramnara** [axisj-com/axisj#417]
![paging](https://cloud.githubusercontent.com/assets/10950845/6184305/846ce078-b3a3-11e4-9b38-f86d6ec4f6a1.png)

그림처럼 값은 다음 페이지 값이 찍히는데 실제 넘어 가는 값은 기존 페이지 값이 넘어가네요

어떻게 하면 다음 페이지 값을 넘길수 있나요?

**Comment by beginnerkht** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

younggubabo@naver.com 님께 보내신 메일 <[axisj] 다음페이지 버튼을 눌렀는데  (#417)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by tom-axisj** [comment]
dialog 에 출력을 어떤 코드로 했는지 알수 없습니다.
스크립트로 소스진행 부분을 알려주셔야 현상 파악이 될 것 같습니다.
샘플 사이트에서는 그리드 하단에 페이지이동이 정상입니다.

http://dev.axisj.com/samples/AXGrid/ajax.html
![2015-02-14 1 17 32](https://cloud.githubusercontent.com/assets/5884902/6190714/493ff53c-b3e7-11e4-9fba-aaab9a1f1e54.png)

**Comment by beginnerkht** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

younggubabo@naver.com 님께 보내신 메일 <Re: [axisj] 다음페이지 버튼을 눌렀는데  (#417)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
