### ISSUE TITLE
bindSelector 옵션 ajaxPars 개선필요

### ISSUE THREAD

**Issue by hyunjun19** [axisj-com/axisj#420]
## 소스위치
https://github.com/axisj-com/axisj/blob/dev/lib/AXInput.js#L1298

## 증상
bindSelector 옵션에서 ajaxPars를 아예 주지 않으면 selectorName 파라미터가 아예 안 날아갑니다.
`if (pars == "") {` 여기에서 `else`가 필요할꺼 같습니다.

## 문제가 되는 bindSelector 옵션
```js
                appendable: false,
                ajaxUrl   : "./search.json",
                onchange  : function(){
                    console.log('onchanged', this);
                }
```

## 임시방편 bindSelector 옵션
```js
                appendable: false,
                ajaxUrl   : "./search.json",
                ajaxPars  : {},
                onchange  : function(){
                    console.log('onchanged', this);
                }
```

**Comment by beginnerkht** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

younggubabo@naver.com 님께 보내신 메일 <[axisj] bindSelector 옵션 ajaxPars 개선필요 (#420)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by hyunjun19** [comment]
35c0f8c820b064d73c24d7014eb13d92b236bf77

**Comment by beginnerkht** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

younggubabo@naver.com 님께 보내신 메일 <Re: [axisj] bindSelector 옵션 ajaxPars 개선필요 (#420)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by tom-axisj** [comment]
그런데 가만 생각해보면 이 분이 자동으로 댓글을 달아주시고 있어서. 외롭진 않네요.

그리고 커밋할 때 이슈 url를 넣어주면 자동으로 붙어 나오는 기능이 있어요
