### ISSUE TITLE
AXGrid checkbox 상태 

### ISSUE THREAD

**Issue by highbase** [axisj-com/axisj#421]
![1](https://cloud.githubusercontent.com/assets/1219110/6392648/2dd4f530-be06-11e4-9b20-0b6da5c7fd91.PNG)

전체 선택 체크박스 선택 후
하위 체크박스 해제 시, 전체 선택 체크박스를 언체크 처리하면 좋겠습니다.

그리고, 가능하면
하위 체크박스가 모두 체크될 때 전체 선택 체크박스도 체크되도록하면 더욱 좋을 것 같습니다.

**Comment by beginnerkht** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

younggubabo@naver.com 님께 보내신 메일 <[axisj] AXGrid checkbox 상태  (#421)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by hyunjun19** [comment]
사실 지금 상태도 버그는 아닌데 정책의 차이로 보이네요.
좀 더 좋은 방법이 있을것 같긴 한데...

**Comment by beginnerkht** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

younggubabo@naver.com 님께 보내신 메일 <Re: [axisj] AXGrid checkbox 상태  (#421)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by tom-axisj** [comment]
전체선택 버튼을 따로 만들어서 처리하는 편이 낳지 않을까요

**Comment by panic910** [comment]
전체 선택 체크박스를 언체크 처리할 경우에 반대로 생각하면
전체 언체크를 하려면 또 두번 액션이 들어가는거라 어떻게 생각하느냐에 따른 차이 아닐까 생각이 듭니다.

좀 더 좋은 방법은 뭘까요...

전체선택, 전체해제 버튼을 따로 만들어서 구현하는게 더 좋지 않을까요?

**Comment by hyunjun19** [comment]
@tom-axisj 낳지 -> 낫다 ^^;;

요렇게 하면 그림이 이상하죠? ^^;;
전체 체크와 전체 해제를 명확히 분리하면 좋을 것 같은데...

![image](https://cloud.githubusercontent.com/assets/421863/6405883/6cb4c008-be6c-11e4-96fd-9f9493c0eeda.png)

**Comment by tom-axisj** [comment]
체크박스를 낳아 보려고 했는데요 ^^;;

**Comment by hyunjun19** [comment]
@tom-axisj :+1:

**Comment by highbase** [comment]
전체 uncheck 는
전체 check 후 전체 uncheck 하는 것으로 하면 될 듯 합니다.(한 번 더 하는 듯 하지만 곧 익숙해질 겁니다.)
