### ISSUE TITLE
AXUpload5 실제 구현 문의

### ISSUE THREAD

**Issue by wann2** [axisj-com/axisj#422]
안녕하세요.
처음 AxisJ를 접하고 AXUpload5를 구현해보았습니다. 그런데 좀처럼 쉽지가 않아 문의드립니다.

	var myUpload = new AXUpload5();
	
	var fnObj = {
		pageStart: function(){
			fnObj.upload.init();
		},
		upload: {
			init: function(){
				myUpload.setConfig({
					targetID:"AXUpload5",
					targetButtonClass:"Green",
					uploadFileName:"fileData",
					fileSelectAutoUpload:true,
					file_types:"image/*",  //audio/*|video/*|image/*|MIME_type (accept)
					dropBoxID:"uploadQueueBox",
					queueBoxID:"uploadQueueBox", // upload queue targetID
					queueBoxAppendType:"append",
					//queueBoxAppendType:"(prepend || append)",
					//openMode: "view",
					// html 5를 지원하지 않는 브라우저를 위한 swf upload 설정 원치 않는 경우엔 선언 하지 않아도 됩니다. ------- s
					flash_url : "/bower/axisj/lib/swfupload.swf",
					flash9_url : "/bower/axisj/lib/swfupload_fp9.swf",
                    flash_file_types:"*.jpg;*.jpeg;*.gif;*.bmp;*.png",
                    flash_file_types_description:"image",
					// --------- e
					onClickUploadedItem: function(){ // 업로드된 목록을 클릭했을 때.
						//trace(this);
						window.open(this.uploadedPath.dec() + this.saveName.dec(), "_blank", "width=500,height=500");
					},
					
					uploadMaxFileSize:(5*1024*1024), // 업로드될 개별 파일 사이즈 (클라이언트에서 제한하는 사이즈 이지 서버에서 설정되는 값이 아닙니다.)
					uploadMaxFileCount:10, // 업로드될 파일갯수 제한 0 은 무제한
					uploadUrl:"/Agen/houseInsImgUpd",
					uploadPars:{
						houseId: $('#houseId').val()
					},
					deleteUrl:"/Agen/houseInsImgDel",
					deletePars:{
						houseId: $('#houseId').val()
					},

					buttonTxt:"파일올리기",
					
					fileKeys:{ // 서버에서 리턴하는 json key 정의 (id는 예약어 사용할 수 없음)
						name:"name",
						type:"type",
						saveName:"saveName",
						fileSize:"fileSize",
						uploadedPath:"uploadedPath",
						thumbPath:"thumbUrl" // 서버에서 키값을 다르게 설정 할 수 있다는 것을 확인 하기 위해 이름을 다르게 처리한 예제 입니다.
					},
					
					onbeforeFileSelect: function(){
						trace(this);
						return true;
					},
					
					onUpload: function(){
						//trace(this);
							var url = "/Agen/houseInsImgList";
							//var pars = "dummy="+axf.timekey();
							new AXReq(url, {
								pars: "houseId="+$('#houseId').val(), 
								onsucc: function(res){
									if(!res.error){
										myUpload.setUploadedList(res);
									}else{
										alert(res.msg.dec());
									}
								}
							});
						trace(myUpload.uploadedList);
						//trace("onUpload");
					},
					onComplete: function(){
							var url = "/Agen/houseInsImgList";
							//var pars = "dummy="+axf.timekey();
							new AXReq(url, {
								pars: "houseId="+$('#houseId').val(), 
								onsucc: function(res){
									if(!res.error){
										myUpload.setUploadedList(res);
									}else{
										alert(res.msg.dec());
									}
								}
							});
						//trace(this);
						//trace("onComplete");
						$("#uploadCancelBtn").get(0).disabled = true; // 전송중지 버튼 제어
					},
					onStart: function(){
						//trace(this);
						//trace("onStart");
						$("#uploadCancelBtn").get(0).disabled = false; // 전송중지 버튼 제어
					},
					onDelete: function(){
						trace(this);
						//trace("onDelete");
					},
					onError: function(errorType, extData){
						if(errorType == "html5Support"){
							//dialog.push('The File APIs are not fully supported in this browser.');
						}else if(errorType == "fileSize"){
							//trace(extData);
							alert("파일사이즈가 초과된 파일을 업로드 할 수 없습니다. 업로드 목록에서 제외 합니다.\n("+extData.name+" : "+extData.size.byte()+")");
						}else if(errorType == "fileCount"){
							alert("업로드 갯수 초과 초과된 아이템은 업로드 되지 않습니다.");
						}
					}
				});
				// changeConfig
				
				// 서버에 저장된 파일 목록을 불러와 업로드된 목록에 추가 합니다. ----------------------------- s
				var url = "/Agen/houseInsImgList";
				//var pars = "dummy="+axf.timekey();
				new AXReq(url, {
					pars: "houseId="+$('#houseId').val(), 
					onsucc: function(res){
						if(!res.error){
							myUpload.setUploadedList(res);
						}else{
							alert(res.msg.dec());
						}
					}
				});
				// 서버에 저장된 파일 목록을 불러와 업로드된 목록에 추가 합니다. ----------------------------- e
				
			},
			printMethodReturn: function(method, type){
				var list = myUpload[method](type);
				trace(list);
				toast.push(Object.toJSON(list));
			}
		}		
	};
	jQuery(document).ready(
		fnObj.pageStart.delay(0.1)
	);

위와 같이 스크립트를 작성하고 파일올리기버튼을 클릭하여 이미지를 첨부합니다.
서버에서는 정상적으로 이미지를 저장했고 다음과 같은 데이타를 json형태로 보냅니다.

[{"id":"AXA235144352_AX_0", "name":"kitchen3.jpg", "type":"image/jpeg", "saveName":"kitchen3.jpg", "fileSize":147620, "uploadedPath":"/upload/54ef3325d3de39b402bb781e/upload_6b7fd76ab859737759df277e9512f091.jpg", "thumbPath":"/upload/54ef3325d3de39b402bb781e/upload_6b7fd76ab859737759df277e9512f091.jpg"}]

그런데 화면에서는 아래와 같이 보입니다.
![-1](https://cloud.githubusercontent.com/assets/8732515/6394568/b00e8660-be15-11e4-82e4-2e42eeb8b38d.gif)

이미지의 요소검사를 해보면 아래와 같은 URL이 background-image로 되어 있어서 이미지를 볼 수 없는 것 같습니다.
div class="AXUploadIcon" style="background-image: url(http://www.test.kr/Agen/houseIns);">image/jpeg</div

질문1) 위 url을 서버에서 보내주는 아래 URL로 변경하려면 어떻게 하는지요?http://www.test.kr/upload/54ef3325d3de39b402bb781e/upload_6b7fd76ab859737759df277e9512f091.jpg

질문2) 제가 잘못 구현을 했다면 어떻게 서버에서 JSON 데이타를 보내줘야 첨부한 이미지를 볼 수 있나요?

질문3) 첨부파일의 하단에 x 버튼을 클릭했을 때 해당 이미지를 삭제하고자 합니다.
서버에 해당 이미지키값을 어떻게 전달을 하죠?

질문4) onUpload와 onComplete에도 서버로부터 JSON 데이타를 불러오는 로직을 넣었는데도 작동하지 않습니다.

질문5) dev.axisj.com AXUpload5에서 소스보기를 하면 fileListLoad.php와 fileUpload.php, fileDelete.php 3가지가 있는데 소스를 받아볼 수는 없을까요?

**Comment by beginnerkht** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

younggubabo@naver.com 님께 보내신 메일 <[axisj] AXUpload5 실제 구현 문의 (#422)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by tom-axisj** [comment]
일단 소스는 https://github.com/axisj-com/axisj/tree/master/samples/AXUpload5 여기로 가시면 다 공개되어 있구요. 

삭제할땐 파일네임이 넘어가게 되어 있는데요. 저세한건 내일 확인 해드릴게요 오늘 하루도 고생하셨습니다

**Comment by tom-axisj** [comment]
누가 younggubabo@naver.com 님께 watch좀 끄라고 말할순 없겠지요 ㅎㅎ

**Comment by panic910** [comment]
1. 업로드된 이미지가 안보이는 이유는 

소스 중간에 보시면
```
                fileKeys:{ // 서버에서 리턴하는 json key 정의 (id는 예약어 사용할 수 없음)
                    name:"name",
                    type:"type",
                    saveName:"saveName",
                    fileSize:"fileSize",
                    uploadedPath:"uploadedPath",
                    thumbPath:"thumbUrl" // 서버에서 키값을 다르게 설정 할 수 있다는 것을 확인 하기 위해 이름을 다르게 처리한 예제 입니다.
                },
```

thumbPath 의 키값을 thumbUrl로 재정의 했기 때문입니다.

[{"id":"AXA235144352_AX_0", "name":"kitchen3.jpg", "type":"image/jpeg", "saveName":"kitchen3.jpg", "fileSize":147620, "uploadedPath":"/upload/54ef3325d3de39b402bb781e/upload_6b7fd76ab859737759df277e9512f091.jpg", "thumbPath":"/upload/54ef3325d3de39b402bb781e/upload_6b7fd76ab859737759df277e9512f091.jpg"}]

에서 thumbPath를 thumbUrl로 정의해서 서버에서 넘겨 주시면 될겁니다.

아래처럼

[{"id":"AXA235144352_AX_0", "name":"kitchen3.jpg", "type":"image/jpeg", "saveName":"kitchen3.jpg", "fileSize":147620, "uploadedPath":"/upload/54ef3325d3de39b402bb781e/upload_6b7fd76ab859737759df277e9512f091.jpg", "thumbUrl":"/upload/54ef3325d3de39b402bb781e/upload_6b7fd76ab859737759df277e9512f091.jpg"}]

로 정의해서 서버에서 넘겨주시면 이미지 보는 문제는 해결 될겁니다.

그리고 saveName 값은 실제 저장된 파일 이름이기 때문에 

"kitchen3.jpg" 이 아닌 "upload_6b7fd76ab859737759df277e9512f091.jpg" 으로 넘겨주셔야 되구요

"type"는 

"image/jpeg" 가 아닌 파일 확장자 "jpg"를 넘겨주셔야 합니다.

"uploadedPath"는
"/upload/54ef3325d3de39b402bb781e/upload_6b7fd76ab859737759df277e9512f091.jpg"

를

"/upload/54ef3325d3de39b402bb781e/"

으로 파일명을 제외한 경로명으로 해주세요

그래서 최종 제가 생각되는 답은

서버에서 넘겨주는 값을

[{"id":"AXA235144352_AX_0", "name":"kitchen3.jpg", "type":"jpg", "saveName":"upload_6b7fd76ab859737759df277e9512f091.jpg", "fileSize":147620, "uploadedPath":"/upload/54ef3325d3de39b402bb781e/", "thumbUrl":"/upload/54ef3325d3de39b402bb781e/upload_6b7fd76ab859737759df277e9512f091.jpg"}]

으로 넘겨주시면 이미지 보여주는 것은 최종 해결될 것으로 보입니다.

2. 파일삭제 버튼 시 서버에서 파일 삭제

```
deleteUrl:"/Agen/houseInsImgDel",
```

위 부분에서 정의한 delete를 실행하는 파일이 x버튼 누르시면 동작되니 샘플 보시고 작성하시면 됩니다.

항상 말씀드리지만

제 말이 정답은 아닙니다 ^^;

**Comment by beginnerkht** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

younggubabo@naver.com 님께 보내신 메일 <Re: [axisj] AXUpload5 실제 구현 문의 (#422)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by panic910** [comment]
파일 삭제 에제는 간단하게..

```
<?php
$isXmlHttpRequest = (isset($_SERVER['HTTP_X_REQUESTED_WITH'])) ? (strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest') ? true : false: false;
($isXmlHttpRequest) ? header('Content-type: application/json') : header('Content-type: text/plain');

header("Content-Type:text/html; charset=UTF-8");

if (!function_exists('mime_content_type')) {
	
	function mime_content_type($f) {
		$f = escapeshellarg($f);
		return trim(`file -bi $f`);
	}
	
}

$saveName = $_POST['saveName'];

if (is_array($saveName)) {
	
	for ($i=0; $i<count($saveName); $i++) {
	
		$myFile = $_POST['saveName'][$i];
		$mypath = $_POST['uploadedPath'][$i];
		$thumb  = $_POST['thumbUrl'][$i];
		
		unlink($_SERVER['DOCUMENT_ROOT'] . $mypath . $myFile);

	}
	
} else {

	$myFile = $_POST['saveName'];
	$mypath = $_POST['uploadedPath'];
	$thumb  = $_POST['thumbUrl'];
		
	unlink($_SERVER['DOCUMENT_ROOT'] . $mypath . $myFile);
	
}

$return['result'] = 'ok';
$return['msg']    = $mypath . $myFile;

echo json_encode($return);
?>
```

axijs에서 saveName를 넘겨주기 때문에 이걸로 DB에서 찾아서 삭제 하시면 됩니다.

**Comment by tom-axisj** [comment]
@panic910 님 그나저나 한번 시간 내주세요. 우리 만나요~

**Comment by wann2** [comment]
넘 감사합니다!!! 덕분에 구현을 할 수 있게 되었습니다.

**Comment by panic910** [comment]
@tom-axisj 전 잘못한게 없습니다!! ^^*

**Comment by tom-axisj** [comment]
@panic910 딱 그정도만 하시면 되는데요 다음주 수요일이나 시간 내주세요 바쁘면 그 다음주 바쁘면 그 다음주 수요일

**Comment by panic910** [comment]
@tom-axisj 수요일은 제가 업무일정 상 불가능한 날입니다. 제가 여유가 생기면 연락을 드리도록 하죠..
근데 어디 잡혀가는건 아니죠 ?

**Comment by tom-axisj** [comment]
@panic910 네 알겠습니다. 편하신 요일 알려주시구요. 010-8881-9137 로 전화나 메세지 주세요. 
납치의 목적은 없구요. 오픈소스 팀원 섭외 과정입니다. 
그동안 답변 스킬을 봐서 본인이 가진 노하우를 좀 더 적극적으로 이용하셔야 하지 않나 라는 생각입니다.

**Comment by panic910** [comment]
@tom-axisj 네 알겠습니다. 개인정보 보호를 위해 연락처는 삭제 하셔도 됩니다. 연락처는 저장 하겠습니다 ^^;

**Comment by wann2** [comment]
안녕하세요.

Upload5에서 동영상을 업로드할 때 대표이미지를 보이게 하려면 어떻게 합니까?

![-1](https://cloud.githubusercontent.com/assets/8732515/6434255/e961173e-c0c7-11e4-9276-2f425b2e8403.gif)

동영상 파일 첨부는 서버로 정상적으로 업로드되는데,
위 처럼 AXUpload5QueueBox에서는 동영상 이미지가 보이지 않습니다.

코드는 아래와 같습니다.

< link rel="stylesheet" type="text/css" href="/bower/axisj/ui/arongi/AXJ.min.css" >
< script src="https://d3alcypgpxy1qk.cloudfront.net/axisj/dist/AXJ.min.js">< / script >
< script src="/bower/axisj/libpro/AXInputPro.js" >< / script >
< script src="/bower/axisj/lib/AXUpload5.js" >< / script >
...
< div id="AXPageAvi" class="mt20" > 
	< div class="AXUpload5" id="AXUpload5Avi">< / div >
	< div id="uploadQueueBoxAvi" class="AXUpload5QueueBox" style="height:188px;">< / div >
< / div >

**Comment by panic910** [comment]
동영상 썸네일을 추출 하셨다면 썸네일 을 리턴 해 주시면 되겠죠?

**Comment by wann2** [comment]
fileKeys: { // 서버에서 리턴하는 json key 정의 (id는 예약어 사용할 수 없음)
	aviId: 'aviId',
	name: 'name',
	type: 'type',
	saveName: 'saveName',
	fileSize: 'fileSize',
	uploadedPath: 'uploadedPath',
	thumbPath: 'thumbUrl'
},

서버에서는 아래와 같이 URL을 보내줍니다. 
rtnJson.push({
	'aviId': avi._id, 
	'name': avi.fileNm, 
	'type': avi.fileExt, 
	'saveName': avi.filePath,
	'fileSize': avi.fileSize,
	'uploadedPath': '/upload/',
	'thumbUrl': '/upload/' + avi.filePath
});
res.json(rtnJson);

실제 넘겨지는 데이타
[{"id":"AXA103239294_AX_0", "aviId":"54f3bde579026a5407ec12f7", "name":"cf.mp4", "type":"mp4", "saveName":"upload_3a12ae7baa450c26d1d58eedcb722f8e.mp4", "fileSize":"5928681", "uploadedPath":"/upload/54f3bddd79026a5407ec12f6/", "thumbUrl":"/upload/54f3bddd79026a5407ec12f6/upload_3a12ae7baa450c26d1d58eedcb722f8e.mp4"}]

위와 같이 해주었는데도 동영상 이미지가 AXUpload5QueueBox에는 보이지 않습니다.

**Comment by hyunjun19** [comment]
*.mp4 파일이 아니라 이미지를 thumbUrl에 주셔야 합니다.
동영상에서 썸네일 이미지를 추출하셔야 합니다.

만약 썸네일 이미지 추출이 힘들다면 그냥 동영상용 이미지 하나 만들어서 해당 이미지경로를 반환하세요.

**Comment by tom-axisj** [comment]
:+1

**Comment by tom-axisj** [comment]
:+1:

**Comment by wann2** [comment]
그럼 동영상으로부터 이미지를 하나 추출하는 방법을 알아봐야겠군요.
권장할만한 것이 있으면 Comment 좀 달아달라고 해도 될까요?

**Comment by panic910** [comment]
문득 난 생각이지만 upload 에 확징지링 썸네일 을 지정해주는 옵션이 있으면 어떨까 생각해봅니다.
뭐 영상. 엑셀. 파워포인트. 등등 
썸네일이 없을 경우 해당 확장의 기본 썸네일을 지정해준다면 편하신 분들이 있을수도...

**Comment by tom-axisj** [comment]
조만간 함수로 빼 둘 예정입니다

**Comment by panic910** [comment]
보통 로 할겁니다 동영상 추출. 언어에 따라 다르니 구글링 해보셔용. "동영상 썸네일 추출" 검색 ㅎㅎ

**Comment by wann2** [comment]
저는 Node.js를 사용하는데 ffmpeg라고 하는 툴을 다운받아서 소스에서 외부파일 실행하는 방법을 사용하니 동영상에서 대표이미지를 추출할 수 있었습니다.
감사합니다. 조언을 해주셔서.^^

다른 사람들도 필요할 것 같아 아래 로직 첨부합니다.
exec('ffmpeg -i \"'+avi.fileNm+'\" -ss 00:00:01 -an -vcodec png -vframes 1 \"'+avi.fileImg+'\"')

**Comment by tom-axisj** [comment]
:+1:

**Comment by wann2** [comment]
문의사항 1)
iOS폰에서 동영상("*.MOV")을 촬영하여 업로드할 때는 업로드가 되지 않습니다.
동영상 size가 0Byte됩니다.
해당파일을 PC에서 업로드하면 정상적으로 업로드 됩니다. iOS는 지원되지 않는 건가요?
setConfig에는 아래와 같이 기술되어 있습니다.
flash_file_types: '*.avi;*.mpg;*.mpeg;*.mpe;*.wmv;*.asf;*.asx;*.flv;*.mov;*.mp4',
flash_file_types_description: 'video',

문의 사항 2)
A군의 이미지들을 정상적으로 업로드하고
B군의 이미지들도 정상적으로 업로드했습니다.
그러다가 A군 또는 B군의 데이타를 수정하려고 할 때 문제가 발생합니다.
즉, A군을 수정하려고 리스트에서 A군을 클릭해서 수정모드로 가면 정상적으로 A군이 올린 이미지들이 AXUpload5QueueBox에 보입니다.
그런데 리스트에서 B군을 클릭해서 수정하려고 하면 좀전의 A군의 이미지들까지 AXUpload5QueueBox에 포함되어 같이 나타납니다.

AXUpload5QueueBox을 초기화하든 setUploadedList을 초기화하는 방법은 없나요?
소속된 해당 이미지를 불러오는 로직은 아래와 같습니다.
var myUpload = new AXUpload5();
var fnObj = {
    pageStart: function() {
        fnObj.upload.init();
    },
    upload: {
        init: function() {
            myUpload.setConfig({
            ......
    },
    pageList: function() {
        var url = '/imgList';
        //var pars = 'dummy='+axf.timekey();
        new AXReq(url, {
            pars: 'chargeId='+$('#chargeId').val(), //A군 또는 B군의 ID
            onsucc: function(res) {
                if (!res.error) { myUpload.setUploadedList(res);  } 
                else { alert(res.msg.dec());       }
            }
        });
    }
}
......

호출 부분
fnObj.pageStart.delay(0.1),
myUpload.setUploadedList([]), <- 이렇게 해도 초기화가 되지 않음
fnObj.pageList.delay(0.1)

**Comment by tom-axisj** [comment]
관련 기능은 확인 해보고 답변 드릴게요
