### ISSUE TITLE
inline-edit.html 부분 중 질문입니다.

### ISSUE THREAD

**Issue by solarware-lee** [axisj-com/axisj#424]
http://dev.axisj.com/samples/AXGrid/inline-edit.html

이쪽에서는 checkbox, radio, select 다 잘 나오는데 이쪽 소스보기해서 
axisj-1.0.13 다운받아서설치후 inline-edit.html이부분 실행시켜봤는데 checkbox, radio,select 이게 인식을 못하더라구요. 
http://dev.axisj.com/samples/AXGrid/inline-edit.html 에서 한대로 고대로 했는데도 안되더라구요.

```js
{
		                    key:"chk", label:"체크", width:"50", align:"center", formatter:"checkbox",
		                    editor: {
			                    type: "checkbox"
		                    }
	                    },
	                    {
		                    key:"rad", label:"라디오", width:"50", align:"center",formatter:"radio",
		                    editor: {
			                    type: "radio"
		                    }
	                    },
 ```
```js
  {
		                    key:"chk", label:"체크", width:"50", align:"center",
		                    editor: {
			                    type: "checkbox"
		                    }
	                    },
	                    {
		                    key:"rad", label:"라디오", width:"50", align:"center",
		                    editor: {
			                    type: "radio"
		                    }
	                    },
```
![test](https://cloud.githubusercontent.com/assets/11223971/6407895/e5ab3ae4-be8c-11e4-87d4-8310a9fe291a.png)

이런식으로 햇는데 인식을 못하더라구요. 제가 놓치고있는 부분이 있는지 ... 어떤걸 더 추가해줘야 할까요?

**Comment by beginnerkht** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

younggubabo@naver.com 님께 보내신 메일 <[axisj] inline-edit.html 부분 중 질문입니다. (#424)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by hyunjun19** [comment]
`formatter:"radio"`가 빠진거 같은데요.
`formatter`는 값을 보여줄 때 사용되는 옵션입니다.
값이 원하는 형태로 보여지지 않는 다면 `formatter`를 확인해 보세요.

**Comment by beginnerkht** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

younggubabo@naver.com 님께 보내신 메일 <Re: [axisj] inline-edit.html 부분 중 질문입니다. (#424)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by solarware-lee** [comment]
@hyunjun19 안녕하세요 답변감사드립니다. 그거 해봤는데요. radio버튼같은경우는 말씀하신대로 formatter를 적용하면 나타납니다. 하지만 checkbox와 select는 
http://dev.axisj.com/samples/AXGrid/inline-edit.html  여기 나와있는 소스를 고대로 복사 붙여넣기 했는데도 위에 사진처럼 저렇게 인식을 못하네요... 이유가 궁금합니다.

**Comment by tom-axisj** [comment]
1.0.13 버전에 inline edit가 다 안 들어 가 있는 것 같습니다.

브랜치를 dev 로 바꾸면 
https://github.com/axisj-com/axisj/tree/dev 
dev.axisj의 소스와 같습니다.

**Comment by solarware-lee** [comment]
@tom-axisj  안녕하세요. 답변감사드립니다. 죄송한데 제가 이거 어제부터 공부중이라 브랜치를 dev로 바꾸라는게 1.0.13버전에서 어떤 소스를 변경하라는 말씀이신가요? 브랜치를 dev로 바꾸는 방법을 자세히 설명좀 부탁드립니다.

**Comment by hyunjun19** [comment]
https://github.com/axisj-com/axisj/raw/master/dist/AXJ.all.js 이 소스를 다운받아서 AXJ.all.js 파일을 업데이트 해보세요.

**Comment by tom-axisj** [comment]
![2015-02-27 2 44 47](https://cloud.githubusercontent.com/assets/5884902/6408003/41c7992e-be8f-11e4-9bec-d03447ba5142.png)

**Comment by tom-axisj** [comment]
dist와 lib폴더안에 js들을 바꾸면 될텐데요. 일일이 받기 어려우면 sourcetree 같은걸로 clone하는 방법을 구글링 해보세요

**Comment by solarware-lee** [comment]
그럼 AXJ.all.js 이거만 수정해주면 되는건가요???

**Comment by tom-axisj** [comment]
lib안에 있는 js들을 연결해서 AXJ.all.js 를 만들어 두고요. 다시 압축해서 AXJ.min.js를 dist폴더에 만들어냅니다.
그러니 적용하시는 소스에 따라 다르니까요
판단 하셔야 할 것 같아요.
