### ISSUE TITLE
bindPattern 에러

### ISSUE THREAD

**Issue by wann2** [axisj-com/axisj#425]
< link rel="stylesheet" type="text/css" href="/bower/axisj/ui/arongi/AXJ.min.css" >
< !-- < link rel="stylesheet" type="text/css" href="/bower/axisj/ui/arongi/AXInput.css" > -- >

< script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js" ></ script >
< script src="https://d3alcypgpxy1qk.cloudfront.net/axisj/dist/AXJ.min.js" ></ script >
< !- -< script src="../../js/AXInput.js"></script > -- >
...
< div class="row" >
	< input type="text" id="phone2" class="form-control AXInput" >
</ div >
...
< script type="text/javascript" charset="utf-8" >
	var fnObj = {
        pageStart: function(){

			$('#phone2').bindPattern({
				pattern: 'numberint',
				max_length: 4
			});
        }
    };
    $(document).ready(function() {
    	fnObj.pageStart.delay(0.1)
	});
</ script >

위와 같은 기술하면 아래와 같은 에러가 납니다.
![-1](https://cloud.githubusercontent.com/assets/8732515/6414225/25f568f8-bed9-11e4-80c2-9a5651b513f4.gif)

뭐가 잘못되었는지 알 수 있으면 좋겠습니다.

**Comment by panic910** [comment]
AXInput.js 이 정상적으로 링크 된건지 확인 한 번 해보시면 좋을 거 같습니다.

**Comment by wann2** [comment]
panic910님, Upload도 도와주시더니 정말 감사합니다.
덕분에 Upload는 정상적으로 구현했습니다.


AxisJ를 본격적으로 사용하려고 하는데 여기서 걸리네요.

<script src="../../js/AXInput.js"></script>
주석을 풀고 정상적으로 링크가 된 것을 확인했습니다.
소스보기에서 해당 링크를 클릭하면 AXInput.js 을 볼 수 있습니다.
그럼에도 위와 같은 에러가 발생합니다.

**Comment by panic910** [comment]
정확한지는 모르겠지만 데모 페이지 확인을 했습니다.
AXinput.js 가 아니라 libpro/AXInputPro.js 를 링크 하셔야 될거 같습니다.
AXInput.js 안에는 bindPattern 이 안보이네요 ^^;

다운로드 받으신 AXISJ 디렉토리에 보시면 아마 libpro 디렉토리가 있을겁니다 

늦은 시간인데 고생하시네요 ^^;

**Comment by tom-axisj** [comment]
min 파일에 넣지 않은 상태 입니다. 조금 고민되는 것이 있어서. 그랬는데요. 일단은 libpro쓰시고
이달안에 lib으로 이동하겠습니다.

**Comment by tom-axisj** [comment]
CDN이 빨리 갱신되면 그냥 끝~

**Comment by panic910** [comment]
:+1:

**Comment by wann2** [comment]
너무너무 감사합니다.
한국에도 이런 개발자분들이 있다는 데에 다시 한번 꾸벅^^

**Comment by wann2** [comment]
... 그런데 키보드 상단의 숫자키는 입력이 되는데,
NumLock(화살표도 있는 부분)부분에서는 숫자키가 작동하지 않네요.
체크 가능한가요?

**Comment by tom-axisj** [comment]
제 노트북에 숫자패드가 없어서.. ㅡ.ㅡ;; 그쪽에서 keyCode가 달라서 그런건데요.
숫자패드용 keyCode를 알아야봐야 가능하겠네요

**Comment by lhslive** [comment]
따로 구현해서 쓸때 아마 ..
109         <-    - 키 
96 ~ 105 <-    Number Pad 0 ~ Number Pad 9
이걸로 해결 봤던거 같습니다.

**Comment by tom-axisj** [comment]
https://github.com/axisj-com/axisj/blob/master/lib/AXInputPro.js#L421 여기 키패드 숫자의 키코드 조건을 추가 해주면 되는데요. 전 키패드가 없어서 있는분 테스트좀 해서 커밋 해주세요

**Comment by lhslive** [comment]
dev에 커밋은 해놨습니다.
일단 개발하는 프로젝트에도 이걸로 바꿔서 다시 테스트 하는중 입니다.

**Comment by tom-axisj** [comment]
:+1:

**Comment by lhslive** [comment]
추가된 키는 DELETE , NUMPAD 0~9 NUMPAD - 입니다.
요즘은 하나 해놓으면 하날 빼먹더라구요 ㅠㅠ

**Comment by wann2** [comment]
감사합니다. 잘 쓰겠습니다^^
