### ISSUE TITLE
AXU4J 게시판 샘플 관련 질문

### ISSUE THREAD

**Issue by goongdeng** [axisj-com/axisj#426]
안녕하세요 액시스제이 세미나 갔다와서 프로젝트에 적용을 검토하며, 샘플을 열심 돌리는 중입니다.

의문이 있어 질문드립니다.

axu4j-egovframe의 게시판 샘플을 이용해 적용중인데요

모바일 환경 테스트를 위해, 가로 폭을  줄여보다 발견을 했는데요

버그인지 아니면 어떤 코딩을 더 해야 하는지 잘 모르겠네요

일정 사이즈 이하로 가면, 아래와 같이 안보이는 현상입니다.

그럼, 즐거운 하루 되세요

테스트 환경: IE9, FireFox, 

![default](https://cloud.githubusercontent.com/assets/11203496/6436292/8a1089e4-c0f0-11e4-8d9d-8931ee64770e.PNG)

**Comment by tom-axisj** [comment]
아 정말 죄송한데요 axu4j 에 올려주실순 없을까요. 
여기저기에 목록을 관리하기가 어려워서 그렇습니다. 불편하시겠지만 axu4j에 올려주세요
