### ISSUE TITLE
행추가 질문입니다.

### ISSUE THREAD

**Issue by solarware-lee** [axisj-com/axisj#427]
예제 나와있는대로 

<input type="button"	value="추가하기" class="AXButton Red" onclick="fnObj.appendGrid();" />
추가 한 후 

위 스크립트에다가 

//행추가부분
var fnObj = {
......
......
         appendGrid: function(index){
              var item = {};
                 if(index){
                     myGrid.appendList(item, index);
                  }else{
                      myGrid.appendList(item);
                        			}
          },
일단 이쪽 추가를 해줬는데 
계속 오류가 
개체가 'appendGrid' 속성이나 메서드를 지원하지 않습니다.  라는 오류가 나는데 
혹시 해서 alert를 찍어봤습니다.

appendGrid: function(index){
             alert("test");
  var item = {};
                 if(index){
                     myGrid.appendList(item, index);
                  }else{
                      myGrid.appendList(item);
                        			}
          },

alert 또는 trace 조차 아예 안뜨던데 예제보고 했는데 다른걸 또 추가해줘야하는건가요??

**Comment by gaedong2** [comment]
보여주신 정보로는 왜 안나오는지 파악하기가 힘듭니다.
 var fnObj = {이속에 있는부분 } 을 다 올려주셔야 파악할수 있을것 같은데요..
그리고 버튼 호출하는 부분도 필요할듯 합니다.

제 경험상으로 그런 오류가 있을경우에는..
1.줄맞춤이 잘못되어있어 다른곳에 들어간경우
2.소스를 정리한다고 다른핵심코드를 삭제한경우
3.상단에 객체를 선언하지 않은경우
4.필요한 JS 를 임포트 하지 않은경우입니다.

우선 소스의 내용을 올려주시면 감사하겠습니다.

**Comment by solarware-lee** [comment]
아 해결했습니다. appendGrid: function(index){ 이부분을 grid위쪽으로 올리니까 되더군요. 감사합니다.
