### ISSUE TITLE
inline-edit 질문입니다.

### ISSUE THREAD

**Issue by solarware-lee** [axisj-com/axisj#428]
{
                    		                    key:"cdType", label:"코드유형", width:"70", align:"center",
                    		                    editor: {
                    		                        formatter: "dec",
                    		                        type: "text"
                    		                    }
                    		                                
                    	                    },

이런식으로 소스 적용하고 실행해보면  editor선택후 수정후 enter를 안치고 다른곳을 클릭하면
수정된게 다시 원래대로 돌아오는데 이거 꼭 enter안치고 도 커서가 움직이거나 그냥 제가 수정한 그대로 가만이 있게는 불가능한가요? 꼭 엔터 처야 가능한건지..

**Comment by tom-axisj** [comment]
그렇게 할 수도 있겠습니다. 다른곳 클릭하면 입력을 취소 해야 겠죠?
저장을 하는게 맞을까요?

**Comment by solarware-lee** [comment]
아뇨 그니까 제가 궁금한건 editor선택 후 내용을 변경후에 엔터를 치지 않고 다른곳을 클릭시 원래대로 값이 돌아가기때문에 그냥 제가 변경한값이 유지되는방법이 있나요?

**Comment by hyunjun19** [comment]
저장에 한표~

**Comment by solarware-lee** [comment]
전 아래 버튼을 따로만들어서 여려행을 수정한 후 저장을 하게끔 하고싶거든요. 그런데 엔터를 안누를시 값이 다시 이전값으로 돌아가버려서 그게 불편할수가 있기때문에 유지되는방법이 궁금합니다.

**Comment by gaedong2** [comment]
셀에서 입력후 엔터를 누르면 새로입력한값 유지..
마우스로 다른곳을 클릭해도 새로입력한값 유지..
ESC키 누르면 이전에 있었던값 보여주는게 좋을듯해요.. 저도 질문하려고 했습니다만.. ㅎㅎ

**Comment by solarware-lee** [comment]
esc까지는 바라지않고 @gaedong2 님이 말씀한대로 
셀에서 입력후 엔터를 누르면 새로입력한값 유지..
마우스로 다른곳을 클릭해도 새로입력한값 유지.. 이걸 저도 원하고있어서.. 방법이 있나요?

**Comment by tom-axisj** [comment]
저장이 되도록 만들겠습니다.

**Comment by solarware-lee** [comment]
아 아직 구현이 안되있는거군요.... 만들어주신다니.. 감사합니다.

**Comment by tom-axisj** [comment]
여러분 테스트를 해보십시요~

**Comment by solarware-lee** [comment]
@tom-axisj 말씀하신 html파일빼고 8개 수정파일 반영 후 테스트 해본결과 
a컬럼에 첫번째행값을 수정한 후 두번째 행 선택이 아예 안됩니다. 대신 b컬럼의 아무행을 선택시 선택이 가능하게되는데 또다른문제는 b컬럼행값이 a컬럼행 수정된값이 그대로 넘어갑니다. 

스크립트는
<script type="text/javascript" src="/axisj/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="/axisj/lib/AXJ.js"></script>
    <script type="text/javascript" src="/axisj/dist/AXJ.min.js"></script>
    <script type="text/javascript" src="/axisj/lib/AXUtil.js"></script>
    <script type="text/javascript" src="/axisj/lib/AXInput.js"></script>
    <script type="text/javascript" src="/axisj/lib/AXSelect.js"></script>
    <script type="text/javascript" src="/axisj/lib/AXGrid.js"></script>
    <script type="text/javascript" src="/axisj/dist/AXJ.all.js"></script> 이런식으로 선언했구요. 

colgroup 부분은
->
  {
                    		                    key:"cdType", label:"코드유형", width:"70", align:"center",
                    		                    formatter:function(){
                                                	return "<u>" + this.item.cdType + "</u>";
                                                },
                    		                    editor: {
                    		                        formatter: "dec",
                    		                        type: "text"
                    		                    }
                    		                                
                    	                    },
                                            {
                                                key:"cdName", label:"코드유형명칭", width:"200",
                                                formatter:function(){
                                                	return "<u>" + this.item.cdName + "</u>";
                                                },
                                                tooltip:function(){
                                                    return this.item.no + "." + this.item.title + "/" + this.key + "/" + this.value;
                                                },
                                                editor: {
                                                	formatter:"dec",
                                                    type: "text",
                    	                            updateWith: ["_CUD"]
                                                }
                                            },

이런식으로 선언했습니다. 제가 놓친부분이 잇나요?

**Comment by tom-axisj** [comment]
문제가 확인 됬습니다. 금일중에 해결 되겠네요

**Comment by tom-axisj** [comment]
```
<script type="text/javascript" src="/axisj/dist/AXJ.min.js"></script>
```

이렇게만 하시면 됩니다. min 에서 전체 js가 선언되어 있기 때문에 중복 선언 하실 필요가 없구요.

특정 UI 컴포넌트의 디버그가 잘 보이지 않을 땐. 아래와 같이
```
<script type="text/javascript" src="/axisj/dist/AXJ.min.js"></script>
<script type="text/javascript" src="/axisj/lib/AXGrid.js"></script>
```
하셔서 확인하고 싶은 클래스만 추가 선언해주면 됩니다.

**Comment by tom-axisj** [comment]
소스 커밋도 되었습니다.

**Comment by solarware-lee** [comment]
@tom-axisj 안녕하세요. 소스 수정해주셔서 너무 감사드립니다. 다름이 아니고 소스 잘 이용하던중 갑자기 오류가 나서요. 왜그런지는 모르겠습니다.. 현상은
list중 한 행 수정후 다른행 선택하면 오류 가 발생하게됩니다.
오류는 SCRIPT438: 개체가 'unbindInput' 속성이나 메서드를 지원하지 않습니다.  라는 메세지가 뜹니다.
위에 올려주신 js파일은 전부 수정한 상태이구. 

html에서 선언은
말씀하신대로  
<script type="text/javascript" src="/axisj/dist/AXJ.min.js"></script>
<script type="text/javascript" src="/axisj/lib/AXGrid.js"></script> 이렇게 2개 선언했습니다. 뭐가 잘못된걸까요..

**Comment by tom-axisj** [comment]
에러날 때 콘솔 정보를 보내주시면 좋을 것 같습니다.
editCellClear 처리 할 때 순서가 안맞아서 그런거 같은데요.
제 브라우저는 에러가 없어서 확인이  필요합니다.
일단 에러가 예상되는 구문을 수정해서 커밋 했습니다.

**Comment by solarware-lee** [comment]
@tom-axisj  답변 감사드립니다. 수정해주신거 적용을 해봤는데 오류가 계속 나더군요.. 

에러 콘솔정보입니다.
SCRIPT438: 개체가 'unbindInput' 속성이나 메서드를 지원하지 않습니다. 
AXJ.all.js, 줄 16291 문자 15

->if(this.inline_edit.editor) {
		            this.inline_edit.editor.find("input").unbindInput();
		            this.inline_edit.editor.remove();
	            }
 여기서  this.inline_edit.editor.find("input").unbindInput(); 이부분이 에러라고 뜨네요.. ㅠ
신기한건 저번주에 했을때는 됫었는데 갑자기 안되서 당황스럽네요 뭐 건들인게 없는데.. ㅠ

**Comment by tom-axisj** [comment]
이래도?

**Comment by solarware-lee** [comment]
@tom-axisj 빠른답변 감사드립니다. 오류는 같구요. 
 콘솔창에는
->
SCRIPT438: 개체가 'unbindInput' 속성이나 메서드를 지원하지 않습니다. 
AXJ.all.js, 줄 16292 문자 16

에러 부분은
 if(this.inline_edit.editor) {
		            if(this.inline_edit.editor.find("input").get(0)) {
			            this.inline_edit.editor.find("input").unbindInput();
		            }
		            this.inline_edit.editor.remove();
	            }

여기서  this.inline_edit.editor.find("input").unbindInput();
 이 부분입니다. 
그 js 선언은
<script type="text/javascript" src="/axisj/dist/AXJ.min.js"></script>
<script type="text/javascript" src="/axisj/lib/AXGrid.js"></script> 이거만 해주면되는건가요?

현재 

<script type="text/javascript" src="/axisj/dist/AXJ.min.js"></script>
<script type="text/javascript" src="/axisj/lib/AXGrid.js"></script>
<script src="http://newdoc.axisj.com/scripts/prettify/prettify.js"></script>
<script src="http://newdoc.axisj.com/scripts/prettify/lang-css.js"></script>
이렇게 되있습니다.

**Comment by tom-axisj** [comment]
네 맞구요. 이상하네요 브라우저가 먼가요?
그리고 http://dev.axisj.com/samples/AXGrid/inline-edit.html 에서도 같은 현상이 발생하나요?

**Comment by tom-axisj** [comment]
그리드 setConfig 구문을 올려주세요 
소스 올리실 때는 [```] 로 감싸서 올려주시구요.

**Comment by solarware-lee** [comment]
브라우져는 ie10,11동일한 현상이구요. 아그리고 호환성보기 에서 진행중입니다.
http://dev.axisj.com/samples/AXGrid/inline-edit.html  여기서 테스트 해봣는데 여기서는 잘되더라구요..  이상한건 저번주에 적용후 했을때 잘 되었는데 어제 갑자기 안되더라구요..; 혹시나해서 소스를 금요일걸로 돌리고 했는데도 동일하게 오류가 나서 .. 당황스럽네요 ㅠ 
setconfig소스입니다.
->
[ 
myGrid.setConfig({
                                        targetID : "AXGridTarget",
                                        sort:false,
                                        //fitToWidth:true, // 너비에 자동 맞춤

                                        /*
                                         todo : editor type options [text, number, money, calendar, select, selector, switch, segment, slider, finder]
                                         */
                                        colGroup : [
                                            {
                                            	key:"no", label:"No", width:"50", align:"center"
                                            },
                                            {
                                                key:"status", label:"상태", width:"40", align:"center", formatter:function(){
	                                                if(this.item._CUD == "C"){
	                                                    return "신규";
	                                                }else if(this.item._CUD == "D"){
	                                                    return "삭제";
	                                                }else if(this.item._CUD == "U"){
	                                                    return "수정";
	                                                }
                                            	},
                                            	editor:{
                                            		type:"text"
                                            	}
                                            },
                    	                    {
                    		                    key:"cdType", label:"코드유형", width:"70", align:"center",
                    		                    editor: {
                    		                        formatter: "dec",
                    		                        type: "text",
                                            		updateWith: ["status"]
                    		                    }
                    		                                
                    	                    },
                                            {
                                                key:"cdName", label:"코드유형명칭", width:"200",
                                                tooltip:function(){
                                                    return this.item.no + "." + this.item.title + "/" + this.key + "/" + this.value;
                                                },
                                                editor: {
                                                	formatter:"dec",
                                                    type: "text",
                                            		updateWith: ["status"]
                                                }
                                            },
                                            {
                                                key:"mEditor", label:"현업수정", width:"100", align:"center",
                                                editor: {
                                                    type: "checkbox"
                                                }
                                            }
                                        ],
                                        colHeadAlign: "center", // 헤드의 기본 정렬 값 ( colHeadAlign 을 지정하면 colGroup 에서 정의한 정렬이 무시되고 colHeadAlign : false 이거나 없으면 colGroup 에서 정의한 속성이 적용됩니다.
                                        body : {
                                            onclick: function(){
                                            	//alert(this.item.cdType);
                                            	//toast.push(Object.toJSON({index:this.index, item:this.item}));
                                            	//alert(this.cdType.val());
                                            	detailDB( this.item.cdType, subsyscode);

                                            }
                                        },
                                        page: {
                                            paging: false
                                        },
                                        editor: {
                        					rows: [
                        						[
                        							{
                        								key:"no", colSeq:0, align:"left", valign:"middle", form:{type:"text", value:"itemValue"}, AXBind:{type:"number", config:{min:1, max:100}}
                        							},
                        							{
                        								key:"state", colSeq:1, align:"left", valign:"middle", form:{type:"text", value:"itemValue"}, AXBind:{type:"text"}
                        							},
                        							{
                        								key:"cdType", colSeq:2, align:"left", valign:"middle", form:{type:"text", value:"itemValue"}, AXBind:{type:"text"}
                        							},
                        							{
                        								key:"cdName", colSeq:3, align:"left", valign:"middle", form:{type:"text", value:"itemValue"}, AXBind:{type:"text"}
                        							},
                        							{
                        								key:"mEditor", colSeq:4, align:"center", valign:"middle", form:{type:"checkbox", value:"itemValue", options:[{value:true, text:''}]}
                        							}
                        						]
                        					],
                        					//request:{ajaxUrl:"saveGrid.php", ajaxPars:"param1=1&param2=2"},
                        					response: function(){ // ajax 응답에 대해 예외 처리 필요시 response 구현
                        						// response에서 처리 할 수 있는 객체 들
                        						//trace({res:this.res, index:this.index, insertIndex:this.insertIndex, list:this.list, page:this.page});
                        					alert(myGrid.list.length);
                        						for(var i=0; i<myGrid.list.length; i++){
                									if(myGrid.list[i]._CUD =="C"){
                										alert("aaa"); 
                										
                									}
                								}
                        					return;
                        						if(this.error){
                        							trace(this);
                        							return;
                        						}

                        						trace(this.res.item);
                        						
                        						if(this.index == null){ // 추가
                        							var pushItem = this.res.item;
                        							//pushItem 에 추가 값 지정 가능
                        							if(this.res.item.title == ""){
                        								alert("제목이 비어 추가 할 수 없습니다.");
                        								return false;
                        							}
                        							insertNewCode($("#largecode").val(), $("#midgcode").val(), this.res.item.cdType, this.res.item.cdName, this.res.item.mEditor,subsyscode);
                                                    trace(pushItem, this.insertIndex);
                        							myGrid.pushList(pushItem, this.insertIndex);
                        						}else{ // 수정
                        							//trace(this.res.item);
                        							AXUtil.overwriteObject(this.list[this.index], this.res.item, true); // this.list[this.index] object 에 this.res.item 값 덮어쓰기
                        							myGrid.updateList(this.index, this.list[this.index]);
                        						}
                        						
                        					},
                        					onkeyup: function(event, element){
                        						if(event.keyCode == 13 && element.name != "title") myGrid.saveEditor();
                        						else if(event.keyCode == 13 && element.name == "title") myGrid.focusEditorForm("regDate");
                        					}
                        				},		
                                        contextMenu: {
                        					theme:"AXContextMenu", // 선택항목
                        					width:"150", // 선택항목
                        					menu:[
                        						{
                        							userType:1, label:"추가하기", className:"plus", onclick:function(){
                        								myGrid.appendList(null);
                        								//myGrid.appendList(item, index);
                        								/*
                        								var removeList = [];
                        									removeList.push({no:this.sendObj.item.no});
                        								myGrid.removeList(removeList); // 전달한 개체와 비교하여 일치하는 대상을 제거 합니다. 이때 고유한 값이 아닌 항목을 전달 할 때에는 에러가 발생 할 수 있습니다.
                        								*/
                        							}
                        						},
                        						{
                        							userType:1, label:"삭제하기", className:"minus", onclick:function(){
                        								if(this.sendObj){
                        									if(!confirm("정말 삭제 하시겠습니까?")) return;
                        									var removeList = [];
                        										removeList.push({no:this.sendObj.item.no});
                        									myGrid.removeList(removeList); // 전달한 개체와 비교하여 일치하는 대상을 제거 합니다. 이때 고유한 값이 아닌 항목을 전달 할 때에는 에러가 발생 할 수 있습니다.
                        								}
                        							}
                        						},
                        						{
                        							userType:1, label:"수정하기", className:"edit", onclick:function(){
                        								//trace(this);
                        								if(this.sendObj){
                        									myGrid.setEditor(this.sendObj.item, this.sendObj.index);
                        								}
                        							}
                        						}
                        					],
                        					filter:function(id){
                        						return true;
                        					}
                        				}
                                    });
]

**Comment by solarware-lee** [comment]
@tom-axisj 안녕하세요. 제가 js선언을 원래
[
<script type="text/javascript" src="/axisj/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="/axisj/lib/AXJ.js"></script>
    <script type="text/javascript" src="/axisj/dist/AXJ.min.js"></script>
    <script type="text/javascript" src="/axisj/lib/AXUtil.js"></script>
    <script type="text/javascript" src="/axisj/lib/AXInput.js"></script>
    <script type="text/javascript" src="/axisj/lib/AXSelect.js"></script>
    <script type="text/javascript" src="/axisj/lib/AXGrid.js"></script>
    <script type="text/javascript" src="/axisj/dist/AXJ.all.js"></script>
    <script src="http://newdoc.axisj.com/scripts/prettify/prettify.js"></script>
    <script src="http://newdoc.axisj.com/scripts/prettify/lang-css.js"></script>
]

이렇게 했었는데 
말씀하신대로 

[
<script type="text/javascript" src="/axisj/dist/AXJ.min.js"></script>
<script type="text/javascript" src="/axisj/lib/AXGrid.js"></script>
    <script src="http://newdoc.axisj.com/scripts/prettify/prettify.js"></script>
    <script src="http://newdoc.axisj.com/scripts/prettify/lang-css.js"></script>
]

이렇게 하니까 
SCRIPT5007: 개체가 필요합니다. 
AXJ.min.js, 줄 2 문자 6895
SCRIPT445: 개체는 이 기능을 지원하지 않습니다. 
AXGrid.js, 줄 91 문자 9
SCRIPT445: 개체는 이 기능을 지원하지 않습니다. 
AXGrid.js, 줄 91 문자 9
SCRIPT445: 개체는 이 기능을 지원하지 않습니다. 
AXGrid.js, 줄 91 문자 9

이런 메세지가 뜨더군요.. ;;;

**Comment by tom-axisj** [comment]
```
<script type="text/javascript" src="/axisj/dist/AXJ.min.js"></script>
<script type="text/javascript" src="/axisj/lib/AXGrid.js"></script>
<script src="http://newdoc.axisj.com/scripts/prettify/prettify.js"></script>
<script src="http://newdoc.axisj.com/scripts/prettify/lang-css.js"></script>
```

이렇게 해두고 쓰세요. 그리고 그리드 문제가 해결 되면 AXGrid.js 는 제거하세요

**Comment by solarware-lee** [comment]
@tom-axisj 안녕하세요. 빠른답변 너무너무 감사드립니다. ㅠ

[
<script type="text/javascript" src="/axisj/dist/AXJ.min.js"></script>
<script type="text/javascript" src="/axisj/lib/AXGrid.js"></script>
<script src="http://newdoc.axisj.com/scripts/prettify/prettify.js"></script>
<script src="http://newdoc.axisj.com/scripts/prettify/lang-css.js"></script>
]

이렇게 하게되면 오류가 나네요.. 그런데
제가 첨에 하던대로
[
<script type="text/javascript" src="/axisj/lib/AXJ.js"></script>
<script type="text/javascript" src="/axisj/dist/AXJ.min.js"></script>
<script type="text/javascript" src="/axisj/lib/AXUtil.js"></script>
<script type="text/javascript" src="/axisj/lib/AXInput.js"></script>
<script type="text/javascript" src="/axisj/lib/AXSelect.js"></script>
<script type="text/javascript" src="/axisj/lib/AXGrid.js"></script>
<script type="text/javascript" src="/axisj/dist/AXJ.all.js"></script>
<script src="http://newdoc.axisj.com/scripts/prettify/prettify.js"></script>
<script src="http://newdoc.axisj.com/scripts/prettify/lang-css.js"></script>
]

이렇게 적용하고 하니 그 첨에 나던 오류
SCRIPT438: 개체가 'unbindInput' 속성이나 메서드를 지원하지 않습니다. 
이 오류는 나타나질 않고 잘됩니다. 

하나 문제는 그리드 컬럼 선택후 수정을 안한상태인데도 상태값이 수정으로 변경이 됩니다.
수정을 해도 그 선택한 행이 수정이되는건 당연한거고
선택만 하고 다른행을 선택해도 수정상태로 변경이 되더라구요. 원래 수정이 안되는게 맞는거죠?

**Comment by tom-axisj** [comment]
얼마전 많은 분들이 에디트 상태에서 다른 영역을 클릭하면 저장 하자고 투표를 하셨는데요.
그래서 에디트 상태에서 다른영역을 누르면 저장 상태로 처리 됩니다.
이걸 한번 더 개선 하려면 아웃 될 때 데이터가 변경 되었는지 확인 후 저장 할지 그냥 둘지 체크를 하도록 수정 해야 합니다. 조금 더 기능을 보강 해야 겠습니다.

**Comment by solarware-lee** [comment]
@tom-axisj 아그렇군요. 바쁘실텐데 친절히 답변 달아주셔서 너무 감사드립니다. 오류수정도 해주시고 넘 감사드려요!!
