### ISSUE TITLE
질문만 늘어가네요..ㅠ grid관련입니다.

### ISSUE THREAD

**Issue by solarware-lee** [axisj-com/axisj#430]
체크된 리스트값을 가져올때는 
myGrid.getCheckedList()라는 메소드를 사용하면 편리하더라구요.

var checkedList = myGrid. getCheckedList(2);// colSeq
alert(Object.toJSON(checkedList));

이런식으로 구현시 체크된값만 가져오더라구요.

그리고 grid에 전체 리스트를 가져올경우 
alert("list ==" +  Object.toJSON(myGrid.list));
이런식이면 다 가져올수 있더라구요. 

제가 구현하고싶은건 수정된 항목만 가져오길 원하는데요. getcheckedlist처럼 
수정된항목만 가져올수있는 그런 메소드 있을까요? 아니면 제가 생각한게

for(var i=0; i<myGrid.list.length; i++){
    if(myGrid list에서 _cud값이 U, 즉 업데이트된값 인 경우){
         그런 list값들을 var updateList 에 담고싶습니다.
     }
}
alert(Object.toJSON(updateList ));

요롷게 확인하고싶은데 

질문 요약하자면

1. getcheckedlist처럼 
수정된항목만 가져올수있는 그런 메소드 있을까요? 

2.  if(myGrid list에서 _cud값이 U, 즉 업데이트된값 인 경우) 여기서
myGrid list에서 업데이트된 list 값을 가져오고싶은데 어떤식으로 해야하는지..
myGrid.list.get[i]............ 어떤식으로 해야할까요..

3. 2번에서 if에서 업데이트된값을 찾은다음에
var updateList 에 담으려고하면 
var updateList = myGrid에서 찾은값 [i]번째 이런식으로 담으면되는건지... 
궁금합니다...ㅠㅠ

**Comment by lhslive** [comment]
```
		var updatedlist = []
		for(var i=0; i<myGrid.list.length; i++){
			 if(myGrid.list[i]._CUD == "C"){
				updatedlist.push(myGrid.list[i]);
			 }
		 }
		 trace(updatedlist);
```

새로 들어온 아이템을 체크할때 쓰던 로직입니다.
이런걸 원하셨는지.. 제가 맞게 이해를 한건지 모르겠네요

**Comment by solarware-lee** [comment]
@lhslive 안녕하세요! 답변 너무 감사드립니다. 
아 제가 myGrid.list[i]._CUD  요걸 쓰는 문법을 몰랐네요 감사합니다. 새해복많이받으세요 ㅎㅎ

**Comment by lhslive** [comment]
도움이 되셨다면 다행입니다.
시간 나시면 전체 소스를 한번 쭉 열어서 보시는게 앞으로의 개발에 도움이 되실것 같네요.
아..그리고 문제 해결되셨으면 요 아래 close도 눌러주세요 ^^
새해복 많이 받으시고 올한해 건승을 기원 드립니다.

**Comment by hyunjun19** [comment]
:+1:

**Comment by hyunjun19** [comment]
63d5b819cd1a64950b39ed8f1880c27487b3e56a

getList라는 메서드를 추가했습니다.
릴리즈까지는 시간이 좀 걸리겠지만 유용하게 사용하셨으면 좋겠네요.^^

**Comment by tom-axisj** [comment]
:+1:

**Comment by lhslive** [comment]
:+1:
