### ISSUE TITLE
element 이동 시 bind 된 controller가 이동되는 시간 단축 방법 문의드립니다.

### ISSUE THREAD

**Issue by darkpoem** [axisj-com/axisj#435]
예를 들어 달력을 bind한 input이 이동될 경우 달력 icon이 따라 오는 시간이 길어서 짧게 줄이고 싶은데 방법을 모르겠습니다.

**Comment by tom-axisj** [comment]
마찬가지로 dev 브랜치에는 빠르게 변경되어 있는에요. 
직접 바꾸시려면 AXInput.js 에서 windowResize 이벤트시에 시작을 변경 할 수 있습니다.

**Comment by darkpoem** [comment]
아 AXInput.js에 있는 거군요.
답변 감사합니다.
