### ISSUE TITLE
bindPattern 건의사항입니다.

### ISSUE THREAD

**Issue by darkpoem** [axisj-com/axisj#436]
input에 bindPattern을 할 경우 오른쪽 키패드로 숫자 입력 시 입력이 안됩니다.
또한, delete 키도 안먹히더라구요.
기본적으로 오른쪽 키패드나 delete의 경우 사용 빈도가 높아서 keyEvent를 허용해 줘야 한다고 생각합니다.
고려 부탁드립니다.
개인적으로는 수정해서 사용중입니다.

**Comment by tom-axisj** [comment]
dev 브랜치에 최신 소스가 적용되어 있습니다. 다음주 월요일에 마스터로 머지 됩니다.
릴리즈 적용은 월말에 이루어 지는데
그 전에 사용하시려면 dev 브랜치의 소스를 이용하셔야 합니다.

**Comment by darkpoem** [comment]
답변 감사합니다.

**Comment by tom-axisj** [comment]
shift+Home을 감지 할 순 있는데 멀 해야 하는거죠?

**Comment by hyunjun19** [comment]
혹시 핫키 기능을 원하시는게 아니신지...

https://github.com/jeresig/jquery.hotkeys 요런거...

**Comment by darkpoem** [comment]
현재 bindPattern을 이용해서 bind한 input 안에서 작성한 text를 전체 선택해서 delete키를 이용해서 삭제할 때 보통 많이 사용하는 방식이 shift+Home이라고 생각하는데 이런 액션은 사용이 안되더라구요. 해서 질문드렸습니다.

**Comment by hyunjun19** [comment]
enhancement => shift+Home 등 액션 추가지원

**Comment by hyunjun19** [comment]
4bd277c50f59dcfac1466c38a4ec71cb6f2688ad

shift+Home, shift+End 액션 추가지원
