### ISSUE TITLE
AXTopDownMenu()의 setHighLightOriginID() 질문 드립니다

### ISSUE THREAD

**Issue by ChohyeKim** [axisj-com/axisj#438]
url이 변하지 않고 해쉬태그로 contents DIV만 변하는 형식으로 개발 중인데요.

AXTopDownMenu() 의 setHighLightOriginID() 관해서 질문 드립니다.

```
var topMenu_data = [
   {_id:"m01", label:"정보관리", url:"javascript:fcObj.goURL('#m01');",cn:[
      {_id:"m0101", label:"업체정보", url:"javascript:fcObj.goURL('#m0101');"},
      .....
   ]}
];
```

```
fcObj.goURL : function(str){
  var hash = "";
  location.href=str;
  if(window.location.hash){
      hash = window.location.hash.substring(1); 
  }
  topMenu.setHighLightOriginID(hash);
}
```

대메뉴는 문제가 없는데 하위메뉴가 중복 하이라이트 처리가 되더라구요.

![test](https://cloud.githubusercontent.com/assets/11262613/6552123/754f18fa-c685-11e4-8091-62a31b3a8086.JPG)

해당 문제를 해결할 방법이 있는지 궁금합니다!

**Comment by tom-axisj** [comment]
기능을 확인 해보니 기존 하이라이트 제거 구문이 빠져 있었습니다. 
해서 해당 기능을 추가하여 dev 브랜치에 추가 하였습니다. 감사합니다.

**Comment by ChohyeKim** [comment]
확인했습니다. 감사합니다!
