### ISSUE TITLE
그리드 인라인 에디트 기능 문의합니다.

### ISSUE THREAD

**Issue by sunglass9** [axisj-com/axisj#443]
다음처럼 그리드를 만들었습니다.
그러나 클릭시 에디트 모드로 바뀌지 않습니다. 뭐가 틀린건가요?

var myGrid = new AXGrid(); // 그리드 변수를 초기화 합니다.
var fnObj = {
	pageStart: function(){
		
		myGrid.setConfig({
			targetID : "AXGridTarget",
			theme : "AXGrid",
			//mediaQuery: {
			//mx:{min:0, max:600}, dx:{min:600}
			//},
			itToWidth: true,
			colHeadAlign: "center", // 헤드의 기본 정렬 값
			colGroup : [
				{key:"SEQ", label:"순번", width:"70", align:"center"},
				{key:"NOSUN", label:"노선", width:"200", align:"center"},
				{key:"ITEM_NM", label:"품목", width:"100", align:"center"},
				{key:"COMP_NM", label:"운송사", width:"120", align:"center"},
				{key:"CAR_NUM", label:"차량번호", width:"150", align:"center"},
				{key:"IMG_REG", label:" ", width:"50", align:"center"},
				{key:"DRV_NM", label:"기사", width:"100", align:"center"},
				{key:"DRV_PH", label:"전화번호", width:"100", align:"center"},
				{key:"T_DATE", label:"상차일", width:"150", align:"center", 
					formatter:function(){
                        return '<input type="text" name="" id="AXdate_'+this.index+'" class="AXInput W100 AXdate" value="'+ this.value +'" />';
                    }
				},
				{key:"H_DATE", label:"하차일", width:"100", align:"center", 
					editor: {
                                type: "calendar"
                            }
				},
				{key:"CARD_NO", label:"카드번호", width:"70", align:"center"},
				{key:"IMG_SAVE", label:" ", width:"50", align:"center"}
			],
			body : {
				onclick: function(){
					//toast.push(Object.toJSON(this.item));
				},
				onchangeScroll: function(){
					trace(this);
					for(var i=this.startIndex;i<this.endIndex+1;i++){
						trace("i="+i);
						$("#AXdate_"+i).bindDate({align:"right", valign:"top",
							onchange:function(){
								trace(this.objID);
								var myi = this.objID.substr(this.objID.lastIndexOf("_").number()+1);
								myGrid.list[myi].regDate = this.value;
							}
						});
					}
				}
			},
			
			page:{
				paging:true,
				pageNo:1,
				pageSize:100,
				status:{formatter: null}
			}
		});
		
		$("#a_yj_dt").bindDate({align:"right", valign:"top", onChange:function(){
		//toast.push(Object.toJSON(this));
		}, defaultDate:"<%=a_yj_dt%>"});
		//$("#a_yj_dt").bindPattern({pattern: "date"});

		jQuery("#a_nosun_code").bindSelect({
			ajaxUrl: "/data/select_nosun_code_data.asp",
			ajaxPars: "",
			isspace: false,
			isspaceTitle: "전체"
		});
		jQuery("#a_item_code").bindSelect({
			ajaxUrl: "/data/select_item_code_data.asp",
			ajaxPars: "",
			isspace: false,
			isspaceTitle: "전체"
		});
		jQuery("#a_comp_cd").bindSelect({
			ajaxUrl: "/data/select_comp_cd_data.asp",
			ajaxPars: "",
			isspace: false,
			isspaceTitle: "전체"
		});

	}
}

오류를 찾았습니다.
<pre>
[!-- css block -->
[link rel="stylesheet" type="text/css" href="/axj/axisj/ui/arongi/AXJ.css">
[link rel="stylesheet" type="text/css" href="/axj/axisj/ui/arongi/AXInput.css">
[link rel="stylesheet" type="text/css" href="/axj/axisj/ui/arongi/AXButton.css">
[link rel="stylesheet" type="text/css" href="/axj/axisj/ui/arongi/AXSelect.css">
[link rel="stylesheet" type="text/css" href="/axj/axisj/ui/arongi/AXGrid.css">
[!-- js block -->
[script type="text/javascript" src="/axj/axisj/jquery/jquery.min.js"></script>
[script type="text/javascript" src="/axj/axisj/lib/AXJ.js"></script>
[script type="text/javascript" src="/axj/axisj/lib/AXUtil.js"></script>
[script type="text/javascript" src="/axj/axisj/lib/AXInput.js"></script>
[script type="text/javascript" src="/axj/axisj/lib/AXSelect.js"></script>
[script type="text/javascript" src="/axj/axisj/lib/AXGrid.js"></script>
를 
[!-- css block --> 
[link rel="stylesheet" type="text/css" href="/axj/axisj/ui/arongi/AXJ.min.css" />
[!-- js block -->
[script type="text/javascript" src="/axj/axisj/jquery/jquery.min.js"></script>
[script type="text/javascript" src="/axj/axisj/lib/AXJ.min.js"></script>
</pre>
일렇게 하니까 제대로 보이네요..

**Comment by tom-axisj** [comment]
죄송하지만 안되신다는 부분이 이해가 잘 안되고 있습니다. 인라인 에디트가 보이지 않는 다는 말씀 이신가요?

**Comment by lhslive** [comment]
자문 자답을 하신듯 한데..close 해도 되지 않을까요?
