### ISSUE TITLE
AXGrid - 자체 API 연동

### ISSUE THREAD

**Issue by montesoul** [axisj-com/axisj#444]
AXGrid 를 자체 API 와 연동하려 합니다. 

웹페이지를 로딩할 때 데이터 목록을 서버에서 가져 와서 .setList() 를 수행하고, 
서버에서 추가 데이터를 받아 왔을 때는 .fetchList() 로 데이터를 추가 했습니다. 

이제 다음의 이슈들이 남았는데, 문서에서 찾기가 쉽지 않네요.

1. 이제 수정과 삭제의 경우, 수정된 항목과 삭제된 항목을 서버로 전송하려 하는데, 
수정된 아이템과 삭제된 아이템을 어떻게 받아 와야 하는지를 모르겠습니다. 

2. 특정 컬럼을 기준으로 소팅을 한 경우, .fetchList() 를 통해 아이템을 추가하면 소팅과는 무관하게 무조건 맨 하단으로 표시가 되더군요. 기존의 소팅규칙을 적용하여 fetch할 수 있는 방법이 있는지요? 아니면 맨 하단이 아니라 특정 위치에 끼워 넣을 수 있는 메소드가 있는지요? 

3. .setConfig() 에서 특정 컬럼을 기준으로 소팅하여 출력하는 옵션이 있는지요? 

4. AXGrid 객체 생성 이후에 특정 컬럼을 기준으로 소팅하는 메소드는 무엇인지요?

**Comment by hyunjun19** [comment]
1. https://github.com/axisj-com/axisj/issues/430 요기 동일한 질문이 있습니다.^^
2. fetchList는 sort관련 코드가 없네요. sortList를 다시 호출하셔야 할것 같습니다. 그리고 pushList 메서드를 사용하시면 원하는 인덱스에 추가하실 수 있습니다.
3.. http://jdoc.axisj.com/AXGrid.html#setConig sort 속성을 사용하시면 됩니다.
```js
colGroup : [
        {key:"no", label:"번호", width:"50", align:"right", sort:"asc"}
]
```
4. 2번에서도 나왔지만 sortList 메서드 입니다.

**Comment by lhslive** [comment]
확실친 않지만 예전에 개발했던 기억을 더듬어 보며 답변 드립니다 .(확답이 아닙니다)
1. #430 와 
    http://dev.axisj.com/samples/AXGrid/passive.html 여길 참조해 보세요.

2. fetchList() 이후 redrawGrid() 를 호출해 보세요.

3. colGroup 에서 해당 컬럼에 sort 옵션이 있습니다. ( sort:false, sort:"desc",sort:"asc")

4. colHead 의 onclick 이나.다른 함수에서 호출하셔도 됩니다.
    아래의 예는 첫번째 컬럼 기준으로 내림차순하는 예시 입니다.
```
                            for (var i = 0 ; i < myGrid.config.colGroup.length ; i++) {
                                myGrid.config.colGroup[i].sort = undefined;
                            }
                            myGrid.config.colGroup[0].sort = "desc"
                            myGrid.redrawGrid();
```


정확하진 않지만.. 이걸 바탕으로 원하시는 결과물을 얻으시면 좋겠네요.

**Comment by montesoul** [comment]
오호~ 두 분 다 감사합니다!!
