### ISSUE TITLE
grid 편집시에 숫자 처리. 질문 있어요 

### ISSUE THREAD

**Issue by narsisya** [axisj-com/axisj#445]
숫자 타입으로 선언하고 값이 0일 경우 표시가 안되네요.

var item = {run_Seq:6, parsing_Tgt_Row_No:0, parsing_Tgt_Col_No:0, parsing_Tgt_Char_No:0};
    							myCmdGrid.appendList(item, 1);
신규 추가시에 이런식으로 처리해서 에디터로 보내면 화면에 0이 뿌려지지 않고 ajax로 보낼때도 값이 공백으로 넘어갑니다. 
방법이 없을까요?

**Comment by narsisya** [comment]
덧붙이면 var item = {run_Seq:0, parsing_Tgt_Row_No:1, parsing_Tgt_Col_No:1, parsing_Tgt_Char_No:1};
    							myCmdGrid.appendList(item);
이런식으로 추가하면 값이 정상적으로 1이 뿌려집니다 ㅠㅠ

**Comment by tom-axisj** [comment]
dev 브랜치에 수정된 버전이 커밋되었습니다. 
버그 찾아주셔서 감사합니다.

**Comment by narsisya** [comment]
감사합니다.
