### ISSUE TITLE
AXGrid에서 marker 사용시 행 선택 대상 버그

### ISSUE THREAD

**Issue by hyunjun19** [axisj-com/axisj#447]
![marker-bug01](https://cloud.githubusercontent.com/assets/421863/6655766/a8f41552-cb4e-11e4-915c-7b8c9ec1d8ee.png)

이미지를 보면 오렌지색 컬럼을 선택했는데 실제 선택되는 부분은 상위행의 왼쪽 컬럼이 선택되었습니다.
이 문제는 행을 selected 처리할 때 marker에 대한 별도 처리(foot은 선택불가)가 필요해 보입니다.

**Comment by hyunjun19** [comment]
https://github.com/axisj-com/axisj/blob/dev/lib/AXGrid.js#L3903 여기서 foot은 `this.body`에 없어서 안걸리는데 marker는 여기 있어서 걸리네요.

**Comment by tom-axisj** [comment]
marker 행은 선택이 되면 안 되는데. 수정을 해보겠습니다.

**Comment by hyunjun19** [comment]
00a264ed402cd706dccbac4634437b9912f69365
