### ISSUE TITLE
버튼 클릭에 대해서 질문드려요

### ISSUE THREAD

**Issue by ChohyeKim** [axisj-com/axisj#448]
버튼을 한번 클릭하면 아래 캡쳐본처럼 계속 눌려있는 상태이던데요

![2](https://cloud.githubusercontent.com/assets/11262613/6659066/ac04da58-cbbf-11e4-99bb-0ccc7fab1dd6.JPG)

focusout이 되면 다시 돌아오긴 하는데..

mouseup이 되면 다시 원복되길 바라거든요

예제사이트에서도 같은 현상이던데 혹시 의도하신건지...

**Comment by tom-axisj** [comment]
현재 CSS가 :focus :hover가 같기 때문에 발생하는 현상인데요.
의도 했다기 보다는.. 탭으로 포커스 이동 할 때가 마우스 오버 할때랑 같은 상황이라고 생각을 했거든요.
좀 애매 합니다.

**Comment by ChohyeKim** [comment]
mousedown, mouseup 를 이용해도 버튼 비활성화/활성화를 하지 못한다는 뜻인가요..?ㅠㅠ

다른방법이 있을까요?

**Comment by lhslive** [comment]
css 직접 수정하셔서 쓰시면 됩니다.

http://www.w3schools.com/cssref/sel_active.asp

기타 속성들도 추가 하셔서 입맛대로 하시면 되겠네요.

**Comment by ChohyeKim** [comment]
css파일에서 button focus항목 제거하니 잘되네요~ 감사합니다.
