### ISSUE TITLE
AxGrid 질문 - 선택한 row 아래에 행추가하기

### ISSUE THREAD

**Issue by lovelysylph** [axisj-com/axisj#450]
안녕하세요. 그리드에서 선택한 row 아래에 행 추가를 하고 싶어서 질문드립니다.

예제로 테스트중인데, index를 length+1 이나 1,5, 10 처럼 아예 숫자로만 되어 있어서요.

선택한 row의 index 를 가져올 수 있는 방법이 혹시 있을까요?

지금은 최상단에 빈 row 를 생성하도록  index 를 0으로 했는데.. 

선택한 row의 아래에 빈행을 추가하고 싶습니다.

```
append: function(index){
				this.target.pushList({}, 0);
			},
```

**Comment by lhslive** [comment]
인덱스만 들고 오시려면 
```
  myGrid.selectedRow.first()
```
해당 row 전체 아이템을 가지고 오시려면
```
  myGrid.getSelectedItem()
```

**Comment by KimJM** [comment]
http://jdoc.axisj.com/
개발할 때 이 문서가 도움이 많이 되더라구요, 참고하시면 좋을 것 같습니다~

**Comment by lovelysylph** [comment]
답변 감사합니다!

**Comment by hyunjun19** [comment]
질문과 답변이 순식간에 지나갔네요... 빠름~ 빠름~ 빠름~ :+1:

**Comment by tom-axisj** [comment]
이런 질문은 거져 먹기인데 아쉽 :+1:
