### ISSUE TITLE
bindTooltip 체인닝 불가 버그

### ISSUE THREAD

**Issue by hyunjun19** [axisj-com/axisj#452]
https://github.com/axisj-com/axisj/blob/master/lib/AXCore.js#L4655 

`return this;` 구문이 each 문 밖에 있어야 할 꺼 같습니다.

**Comment by tom-axisj** [comment]
:+1:

**Comment by lhslive** [comment]
:+1:

**Comment by hyunjun19** [comment]
6bef40af71f3c04d7d04af8e5775f002d6eca77c fixed
