### ISSUE TITLE
grid ajax처리 문의

### ISSUE THREAD

**Issue by gjjoo** [axisj-com/axisj#455]
1.
myGrid.setList({
   ajaxUrl: url,
   ajaxPars: "param1=1"
});
이부분 잘되는거 맞는거죠? jsp파일이고 스프링 json데이터 넘어오는것 까지는 확인했고, 
AxGrid.js 봤을때 new AXReq()를 타고  onsucc에서 trace로 json데이터 까지 확인했습니다만, 어떤 이유에서인지 몰라도 계속 "undefined" alert이 뜨네요...

2.
var list = [{abc:"def"}];
myGrid.setList(list);
이부분은 잘되구요..

3.
new AXReq(url, {
   onsucc: function(data){
      myGrid.setList(data);
   }
});
1번이 안되서 찾아보다가 다음과 같은 방법으로 했는데 저렇게 하면 잘되네요...

문제는, myGrid.reloadList(); 함수를 사용하고 싶은데 1번과 같은 방법으로 해야 되는거 같은데 1번이 도저히 안되서 못하고 있네요..

확인 부탁드립니다ㅠㅠ

**Comment by gjjoo** [comment]
해결했네요... list라는 key값에 넣어줘야 되네요.. 휴.. 개인적으로 불편 ㅠ

**Comment by tom-axisj** [comment]
ajax는 대게 page변수를 받아야 해서 오브젝트에 list가 될 수 밖에 없는 상황이 있었어요

**Comment by KimJM** [comment]
전에 이 이슈 보고 답글 달아드리려 했는데 너무 늦었네요
개인적으로 편한 방법이니 참고해주시면 좋겠네요
아래와 같은 모델 하나 작성 후
````java
public class AXGridResult<T> {
	private ArrayList<T> list;
	public AXGridResult(ArrayList<T> list){ this.list = list; }
}
````
컨트롤러 쪽에서는 아래와 같이 사용하시면 보기에도 깔끔합니다
````java
	@RequestMapping(value = "/stores", method = RequestMethod.GET)
	@ResponseBody
	public AXGridResult<Store> getStores(HttpServletRequest httpRequest, HttpSession httpSession) {
		return new AXGridResult<Store>(storeService.getStores());
	}
````
위 처럼 사용 하시면 추가 상태 값.. 등등 response시 장점도 있어서 전 list 로 묶인 걸 더 선호합니다
