### ISSUE TITLE
myGrid.setConfig의 request 질문...

### ISSUE THREAD

**Issue by gjjoo** [axisj-com/axisj#457]
myGrid.setConfig({
   ...
   request:{
      ajaxUrl:"/save",
      ajaxPars:"a=1&b=2&c=3",
      debug: true,
      onsucc: function(){
         trace("데이터 저장 성공~");
      }
   }
   ...
});

request를 사용하니깐 추가나 수정시 바로 request를 호출하더라구요, 그런데 문제가 호출하고나서 제어를 해야하는데 잘모르겠습니다.. 'onsucc'를 사용하면 저장 한 후 해당 function이 호출될 줄 알았는데, 아니더라구요... 방법이 없을까요??

**Comment by hyunjun19** [comment]
onsucc 말고 response로 구현해 보세요.
```js
request: {
    ....
    response: function() {
        // 여기에 구현해 보세요.
    }
}
```

**Comment by hyunjun19** [comment]
잘 못 알려드렸네요.

`request.response`가 아니라 `editor.response` 입니다.

```js
editor: {
    request: { ... }
    response: function() {
        // 여기에 구현해 보세요.
    }
}
```

**Comment by gjjoo** [comment]
감사합니다!! ㅎ response 생각도 못했네요..ㅠㅠ
