### ISSUE TITLE
그리드 순번 문의드립니다.

### ISSUE THREAD

**Issue by lovelysylph** [axisj-com/axisj#458]
안녕하세요. 궁금한 게 있어서 질문드립니다. 그리드에 순번컬럼이 있는데,

![1](https://cloud.githubusercontent.com/assets/11494115/6701174/67188ed2-cd5c-11e4-8a2f-d648ffd1cfad.PNG)

순번 컬럼이 행추가나 삭제를 하면 중간에 숫자가 붕뜨게 되잖아요.. 1, 3, 4 이렇게요.
그래서 
```
function fncSetRowNum(){
	for (var i = 0; i < myGrid.list.length ; i++) { 
		myGrid.updateItem(0, 0, i, i+1); 
		
	}
}
```
이렇게 순번을 다시 주고 있긴한데, 저렇게 따로 안해줘도

자동으로 세팅해주는 ... 컬럼속성에 순번 속성 그런게 있는지 궁금합니다.

**Comment by tom-axisj** [comment]
https://github.com/axisj-com/axisj/issues/36 이걸 참고해 보세용

**Comment by lovelysylph** [comment]
감사합니다!
