### ISSUE TITLE
그리드 ajax 질문이 있습니다.

### ISSUE THREAD

**Issue by lovelysylph** [axisj-com/axisj#460]
안녕하세요. ajax로 조회를 해보고 있는 중인데 질문이 있습니다.

아래 화면 처럼 OK 라고 alert 이 뜨고 그리드는 뜨질않고 계속 돌고 있는데.. OK 는 왜 뜨는건지..

그리고 왜 조회가 안되는건지 도통 원인을 못찾고 있어서요..

![1](https://cloud.githubusercontent.com/assets/11494115/6703449/351e2f40-cd7f-11e4-9d41-4ade49e98ec4.PNG)

```
<Script Language="JavaScript">
var pageID = "ajax";
var myGrid = new AXGrid();
var itemSum = 0;
var list = [ ];
var fnObj = {
	pageStart: function(){

		myGrid.setConfig({
			targetID : "AXGridTarget",
			theme : "AXGrid",
			  colGroup : [
	                {key:"no", label:"번호", width:"50", align:"right", pk:true, formatter:function(){return this.index+1;}}, 
					{key:"KPI_MCLS_NM", label:"대관점", width:"72"},
					{key:"KPI_LCLS_CD", label:"대관점코드", width:"72", display:false},
					{key:"KPI_MCLS_NM", label:"중관점", width:"80"},
					{key:"KPI_MCLS_CD", label:"중관점코드", width:"80", display:false},
					{key:"KPI_SCLS_NM", label:"소관점", width:"122"},
					{key:"KPI_SCLS_CD", label:"소관점코드", width:"80", display:false}
	            ],
			
			body : {
				onclick: function(){
	               		
	             }
			},
			page:{
				  paging:false
			}
		});//setConfig end

           myGrid.setList({
               ajaxUrl:"/GauceChannelSVL2?cmd=sbc2.common.CM_SELECT_Cmd&proc=SELECT_JSON"
				, ajaxPars:"&IS_PATH=sbc2/od/OD_S031.xml"
							+"&IS_SQL=SELECT_KPI_X"
							+"&IS_CONDITION="
				, onLoad:function(){
                   //trace(this);
               }
           });

		//myGrid.setDataSet({price:123000, amount:10});
	}//pageStart end 
};
	
$(document).ready(function(){
	fncOnLoad();
	fnObj.pageStart.delay(0.1);	// 0.1초 지연 실행됨
});

```

setList 에 ajaxUrl 에 컨트롤러를 호출해주는데, 내부에서

```
String json = Ajax_Util.listToJSON(tmp);
			System.out.println(json);
			response.setContentType("text/json; charset=UTF-8");
			response.getWriter().print(json);
			response.getWriter().flush();
```
스트링에 json 을 담아서 그걸 화면에 뿌리려는데 .. 저기 System.out.println 찍힌거 보면

{"list":[{KPI_MCLS_NM: "기업성과",CHK: "F",DATA_DIV: "1",KPI_SCLS_CD: "KPIS009",KPI_CD: "KPI_042",COM_VAL: "null",KPI_LCLS_NM: "핵심역량",KPI_MCLS_CD: "KPIM003",KPI_NM: "주요고객 비율",SCORE: "null",KPI_SCLS_NM: "고객만족",INP: "null",IDS_AVG: "null",KPI_LCLS_CD: "KPIL002",ORD: "29",MNDT_YN: "Y"}, {KPI_MCLS_NM: "기업성과",CHK: "F",DATA_DIV: "1",KPI_SCLS_CD: "KPIS009",KPI_CD: "KPI_044",COM_VAL: "null",KPI_LCLS_NM: "핵심역량",KPI_MCLS_CD: "KPIM003",KPI_NM: "고객 반품률",SCORE: "null",KPI_SCLS_NM: "고객만족",INP: "null",IDS_AVG: "null",KPI_LCLS_CD: "KPIL002",ORD: "31",MNDT_YN: "Y"}]}

이렇게 나오거든요. 
샘플에 있는 gridData.json  페이지가 {"list":[{"code_sw":"abc"},{"code_sw":"bdc"}]} 이런 형태길래
저도 이런형태로 가공을 했는데.. 
json 형태가 잘못된 건가요?

**Comment by tom-axisj** [comment]
![2015-03-18 1 21 48](https://cloud.githubusercontent.com/assets/5884902/6704087/50093338-cd87-11e4-9b11-e05acf8d1dd8.png)

이런 콘솔창 보시면 xhr header 정보가 있거든요.
그 정보 한번 봐주시구요. 
아무래도 AJAX호출시 contentType이 안 맞는 것 같은데요. 리얼 json으로 리턴 하시면 AXReq 속성을 조금 바꾸어야 합니다.

**Comment by lovelysylph** [comment]
콘솔창 정보가..
![2](https://cloud.githubusercontent.com/assets/11494115/6704216/edec3ed2-cd88-11e4-9c01-eb833a7f8868.PNG)

이렇습니다.
컨트롤러에서 
```
String json = Ajax_Util.listToJSON(tmp);
			System.out.println(json);
			response.setContentType("text/json; charset=UTF-8");
			response.getWriter().print(json);
			response.getWriter().flush();
```
여기서 저 contentType 이 문제인걸까요?

**Comment by tom-axisj** [comment]
http://api.jquery.com/jQuery.ajax/ 에서 관련 옵션을 보셔야 할 것 같구요. 

```
AXConfig.AXReq.contentType = "application/json; charset=utf-8";
```

를 선언 후 해보시면 어떨까 합니다.
그 외에도 이런 속성을 변경 할 수 있는데. 대부분 컨텐츠 타입만 확인하면 됩니다. 
```
AXConfig.AXReq.contentType = "";
AXConfig.AXReq.responseType = "";
AXConfig.AXReq.dataType = "";
```

콘솔에서 URL리스트를 클릭해보세요. 그럼 서버 리턴 값을 볼 수 있습니다. 그 값이 맞는지도 확인 해야 겠습니다.

**Comment by lovelysylph** [comment]
선언하시라는 저 소스를  그냥 자바스크립트 내에 적용하면 되는건가요?;

```
<Script Language="JavaScript">
var pageID = "ajax";
var myGrid = new AXGrid();
var itemSum = 0;
var list = [ ];

AXConfig.AXReq.contentType = "application/json; charset=utf-8";

var fnObj = {
	pageStart: function(){

		myGrid.setConfig({
			targetID : "AXGridTarget",
			theme : "AXGrid",
			  colGroup : [   ...
	               
```

**Comment by tom-axisj** [comment]
ajax통신방식을 선택하시는 것이니 당장은 페이지에 붙여주시면 되는데. 앞으로는 공통JS에 넣어 두셔야 되겠구요. 
일단 해보세요 안될수도 있으니

**Comment by tom-axisj** [comment]
캡쳐는 header이고 preview나 response탭에는 머라고 나오나요?

**Comment by hyunjun19** [comment]
'System.out.println(json); ' 이 결과는 너무 믿지 마세요.
크롬 개발자 툴에서 아래처럼 나오는지 확인해 보셔야 합니다.

응답이 `JSON`이 아니라 `String`으로 반환되는 경우 같습니다.

![image](https://cloud.githubusercontent.com/assets/421863/6704540/7bd41a0e-cd8d-11e4-93d9-dd234a21cfb8.png)

**Comment by lovelysylph** [comment]
preview나 response 모두 이렇습니다;

![1](https://cloud.githubusercontent.com/assets/11494115/6704556/b3b20670-cd8d-11e4-8e32-2ea85fe2340d.PNG)

**Comment by tom-axisj** [comment]
안타깝지만 잘 못 짜셨네요. AJAX할아버지가 와도 이렇게 하면 안돌아 갑니다.

**Comment by lovelysylph** [comment]
AXConfig.AXReq.contentType = "application/json; charset=utf-8"; 
선언하기 이전 에는  이렇게 나오긴하는데.. 저걸 선언하면 아예 안돌아가네요 ㅠ ㅠ 
잘못짠건가요..ㅠ...

![1](https://cloud.githubusercontent.com/assets/11494115/6704591/1dbebebe-cd8e-11e4-90cd-26818a4e5665.PNG)

**Comment by hyunjun19** [comment]
저 이미지에서 헤더 탭을 찍어서 보여주세요.

**Comment by lovelysylph** [comment]
이렇습니다.

![1](https://cloud.githubusercontent.com/assets/11494115/6704623/84dc80ae-cd8e-11e4-97c1-a6d096eee7a6.PNG)

**Comment by tom-axisj** [comment]
서버페이지에서 response.setContentType("text/json; charset=UTF-8"); 를 해주었으니 리턴이 JSON으로 가는데. 요청은 또 다르고 어렵네요. 
서버페이지가 요청을 안받아주는것 같은데

**Comment by lovelysylph** [comment]
AXConfig.AXReq.contentType = "application/json; charset=utf-8";  선언안했을 때 프리뷰는 이런데..어렵네요 ㅠㅠ

![2](https://cloud.githubusercontent.com/assets/11494115/6704701/a5f40d38-cd8f-11e4-94b0-924e82056b74.PNG)

**Comment by tom-axisj** [comment]
컨텐츠타입 json을 쓰려면 json객체를 제대로 만들어서 리턴 하셔야 할 겁니다. 문자열로 페이지에 출력하면 안되는 것으로 알고 있어요

**Comment by hyunjun19** [comment]
제 응답 헤더는 `application/json;charset=UTF-8` 요렇게 찍히네요.
혹시 모르니 한 번 그대로 복사해서 사용해 보세요.

`AXConfig.AXReq.contentType = "application/json;charset=UTF-8";`

**Comment by lovelysylph** [comment]
AXConfig.AXReq.contentType = "application/json;charset=UTF-8";
이걸 jsp 에 복사해서 붙이면 OK 대신 undefined 알럿이 뜨네요. 
제대로 된 jsono 객체로 만들어서 리턴하도록 수정해봐야겠습니다 ㅠㅠ..

```
<Script Language="JavaScript">
var pageID = "ajax";
var myGrid = new AXGrid();
var itemSum = 0;
AXConfig.AXReq.contentType = "application/json;charset=UTF-8";

var fnObj = {
	pageStart: function(){

		myGrid.setConfig({
			targetID : "AXGridTarget",
			theme : "AXGrid",
			  colGroup : [
```
![1](https://cloud.githubusercontent.com/assets/11494115/6704800/2c2f157c-cd91-11e4-823a-c038742e7e87.PNG)

**Comment by hyunjun19** [comment]
JSON 형태를 다시 확인해 보세요.
키도 `"`로 묶어야 합니다. 아까 올려주신 내용을 보니 키에 `"`이 없네요.

```js
{"list":[{KPI_MCLS_NM: "기업성과",CHK: "F",DATA_DIV: "1",KPI_SCLS_CD: "KPIS009",KPI_CD: "KPI_042",COM_VAL: "null",KPI_LCLS_NM: "핵심역량",KPI_MCLS_CD: "KPIM003",KPI_NM: "주요고객 비율",SCORE: "null",KPI_SCLS_NM: "고객만족",INP: "null",IDS_AVG: "null",KPI_LCLS_CD: "KPIL002",ORD: "29",MNDT_YN: "Y"}, {KPI_MCLS_NM: "기업성과",CHK: "F",DATA_DIV: "1",KPI_SCLS_CD: "KPIS009",KPI_CD: "KPI_044",COM_VAL: "null",KPI_LCLS_NM: "핵심역량",KPI_MCLS_CD: "KPIM003",KPI_NM: "고객 반품률",SCORE: "null",KPI_SCLS_NM: "고객만족",INP: "null",IDS_AVG: "null",KPI_LCLS_CD: "KPIL002",ORD: "31",MNDT_YN: "Y"}]}
```

**Comment by hyunjun19** [comment]
콜렉션이나 빈을 JSON으로 변환하시는 경우에는 http://jackson.codehaus.org 라이브러리를 추천합니다.

**Comment by lovelysylph** [comment]
ㅠㅠㅠ 키에 "   빠진것 때문..이었습니다....죄송합니다..ㅠㅠ 
그리드가 보이네요 ㅠㅠ 감사합니다 ㅠㅠㅠㅠ 링크해주신 라이브러리 참고할게요.
두분 감사합니다..ㅠ ㅠ

**Comment by hyunjun19** [comment]
드디어 해결되었네요. 저희도 처음부터 JSON을 자세히 봤으면 금방 알았을 텐데 대충봐서 오래 걸렸네요. ^^;;
:+1:

**Comment by tom-axisj** [comment]
감사하면 밥이라도 한번 쏘세요 ^^
:+1:
