### ISSUE TITLE
AXTree(AJAX)에서 onexpand 시...

### ISSUE THREAD

**Issue by gjjoo** [axisj-com/axisj#461]
AXTree 예제 Ajax쪽에서 onexpand시 같은레벨에 있는 다른 노드들은 화살표가 없어지네요...

안없지게 하고 싶은데 방법이 없을까요??

**Comment by KimJM** [comment]
dev 브랜치 다시 받아서 확인 한번 해보시기 바랍니다.
"__subTree":true 로 주시면 자식이 존재하지 않아도 화살표가 존재합니다.

**Comment by KimJM** [comment]
__subTree:true 면 화살표를 보여주게 되었고, 내부 Tree Item 의 subTree Array length 가 0일 경우 
화살표를 안 보여주도록 하게 되는 부분이 있었습니다.

__subTree:true 이면서 실제 데이터는 없으니 모순이 발생하고 추가할 subTreeItem이 없다는 것으로 판단하고
화살표 또한 안 나오게 된 것 같습니다.

서버 쪽에서 자식이 존재하는 데이터에게는 __subTree:true 를 포함하여 response 주시면 될 것 같네요..

**Comment by tom-axisj** [comment]
:+1:

**Comment by gjjoo** [comment]
감사합니다! ㅎㅎ 잘 되네요!
