### ISSUE TITLE
그리드 관련 궁금한 것이 있습니다.

### ISSUE THREAD

**Issue by lovelysylph** [axisj-com/axisj#462]
안녕하세요. 문득 궁금한 게 생겨서..
화면의 input box 와 보이지않는 그리드를 바인드해주는 기능이 혹시 있는지요? api 를 봤을 땐 없는 것
같아서 혹시 있는지 궁금해서요.
inputbox 의 값을 변경하면 바인드 된 그리드의 해당 셀 값이 자동으로 변경되는 식으로요 ''

**Comment by lhslive** [comment]
그리드의 내장 input이 아닌 그리드 밖의 별도 input box를 말씀하시는 건가요?..

```
<input type="text" name="" id="" onblur="fn_change_grid_val(this.value);">
```


```
  function fn_change_grid_val(val){
    if(val){
     myGrid.list[0].some_key = val;
    }
    
  }
```

이런걸 말씀하신 거려나요..

**Comment by lovelysylph** [comment]
네 그리드 밖 별도의 인풋박스요. 스크립트로 인풋박스 값을 그리드에 넣어주지 않아도 바인드 되어 있어서 자동으로 변경되는 기능이 있는지 궁금해서요 ㅎㅎ

**Comment by lhslive** [comment]
자동변경은 없고요..
http://jdoc.axisj.com/AXGrid.html#updateItem 

이거 참고 하셔서 간단하게 구현 하세요.

**Comment by lovelysylph** [comment]
네 답변 감사합니다 ^^
