### ISSUE TITLE
AXGrid 건의 사항

### ISSUE THREAD

**Issue by zeroty** [axisj-com/axisj#463]
안녕하세요. 테스트로 그리드를 적용하다보니 약간의 문제가 생겨 문의 드립니다.

제가 PHP는 안써봐서 잘 모르겠는데 보통 스프링을 쓸 경우 파라미터를 json형태로

 넘기고 맵으로 자동 바인딩해서 사용하는데 AXGrid에 .setList옵션에는 dataSendMethod옵션이

 존재하지 않네요.

일단 아래와 같이 수정해서 쓰고 있으나 setList에도 json타입을 고려해주셨으면 합니다.

JSP소스 
 this.target.setList({
                	contentType: "application/json; charset=utf-8",
            		type: "POST",
            		dataType: "json",
            		dataSendMethod: "json",
                    ajaxUrl: "/json/getMaintenanceInfo.json",
                    ajaxPars: "a=1&b=2&c=3",
                    onLoad:function(){
                    	console.log("onload!!");
                        //trace(this);
                    }
                });

JS소스
var appendPars = [
                "pageNo=" + ((exts == "paging") ? this.page.pageNo : 1),
                "pageSize=" + this.page.pageSize
      ];
            
var pars = (obj.ajaxPars) ? obj.ajaxPars + "&" + appendPars.join('&') : appendPars.join('&');

if(obj.dataSendMethod == "json") {
   pars = JSON.stringify(pars.queryToObject());
} 

JAVA Controller소스
@RequestMapping("/json/getMaintenanceInfo")
	public Map<String, Object> getMaintenanceInfo( @RequestBody HashMap<String, Object> paramMap ) throws ServletException, IOException {

  ..
}

감사합니다.

**Comment by tom-axisj** [comment]
AXConfig.AXReq.dataSendMethod = "json|query-json|parameter" 

3개중 하나의 옵션을 선택하실수 있도록 변경하였습니다.
저희는 ajax통신을 하나의 AXReq라는 클래스가 처리 하는데. 이 코어에서 AXConfig.AXReq 에 속성을 그때 그때 받도록 되어 있습니다.
페이지 상단에서 변수를 변경 하신후 사용하시거나. 
AXConfig.js파일을 적절히 변경후 사용하시면 되겠습니다. min파일을 사용하는 경우엔 압축파일안에도 AXConfig.js가 들어 있으니 압축을 적절하게 다시 하셔야 하겠습니다.
