### ISSUE TITLE
궁금한점이 있습니다. 

### ISSUE THREAD

**Issue by boxkie** [axisj-com/axisj#466]
AXUpload5 를 테스트 삼아 구현 해보려하는데

java 쪽 빽앤드 소스는 찾아봐도 나오지 않네요

API 를 봐도 별다른 내용이 없는데

MVC model 형태로 java로 구현되어있는 예제나 샘플은 없는건가요?

**Comment by hyunjun19** [comment]
액시스제이는 자바스크립트 라이브러리 입니다.
Java 쪽은 직접 검색해서 찾아보셔야 합니다.
MVC 모델이라고 해도 Spring인지 아니면 다른 프레임워크인지에 따라서도 달라지며 설정도 복잡한 편이기 때문에 여기서 직접 설명드리긴 힘듭니다.

**Comment by boxkie** [comment]
몇가지 더 질문드리겠습니다.
AXUPload5 같은 경우 게시판형태로 만들어서 적용할 경우 파일을 추가할때마다
Ajax 로 바로 업로드 하지 않고 등록 버튼을 눌렀을때 올라와있는 파일들이
한번에 업로드 될수 있도록 하는 옵션이 있나요? 
등록 버튼을 누르면 스크립트로 업로드 동작을 작동시키고 onComplete function 으로
form 을 submit 시키는 형태로 사용하고 싶습니다만 가능한지 궁금합니다.

**Comment by hyunjun19** [comment]
http://dev.axisj.com/samples/AXUpload5/manualUpload.html 여기를 참고하세요.

**Comment by boxkie** [comment]
아..
 fileSelectAutoUpload:false,
있네요 감사합니다.
jquery file upload 구현하고 있었는데
AXUPload5가 더 쉽게 구현 할 수 있을듯하네요
감사합니다.

**Comment by hyunjun19** [comment]
밤 늦게 고생하시네요.
즐프하세요~

**Comment by boxkie** [comment]
네 늦은시간에도 답변주셔서 감사합니다.
