### ISSUE TITLE
AxGrid에서 paging처리가 되지 않습니다..

### ISSUE THREAD

**Issue by sparkkong** [axisj-com/axisj#467]
데이터는 잘 나오는데 페이징 처리만 되지 않습니다.

아래는 실제 데이터이구요.

{"page":{"pageCount":0,"listCount":20,"pageNo":1},"list":[{"RNUM":1,"ADVERTISERNAME":"DHL코리아","BRANDNAME":"DHL","CATE3NAME":"특급운송서비스","CATE2NAME":"운송","CATE1NAME":"서비스"}],"msg":"data"}

아래처럼 세팅했습니다.
```js
cusGrid.setConfig({
			emptyListMSG: "데이터가 존재하지 않습니다.",
			targetID : "gridDataList",
			theme : "AXGrid",
			fitToWidth: true,
			colGroup : [
				{key:"ADVERTISERNAME", label:"광고주", width:"100", align:"left"},
				{key:"BRANDNAME", label:"브랜드", width:"100", align:"left"},
				{key:"CATE", label:"업종", width:"200", align:"left", formatter:function(){
					return this.item.CATE1NAME + " < " + this.item.CATE2NAME + " < " + this.item.CATE3NAME;
				}}
			],
			colHeadAlign: "center",
			body : {				
				addClass: function(){	
					// red, green, blue, yellow, white, gray
					if(this.index % 2 == 0){
						return "yellow";
					}else{
						return "white";
					}
				}
			},
			page:{
				paging:true,
                status:{formatter: null}
			}
		});		
```
예제페이지와의 다른점은. json데이터를 만들었을때(java,GSon으로 json으로 변환)  key항목 "page"(더블쿼테이션으로 감쌈)으로 처리된것 뿐입니다.

확인 부탁드릴게요~

**Comment by hyunjun19** [comment]
페이징 처리가 안된다는 말을 좀 더 상세하게 설명해 주세요.
`그리드 하단에 페이지 표시 셀렉트가 값이 10까지 나와야 하는데 1밖에 없어요` 라든지
`페이지 이동 버튼을 눌렀는데 서버에 페이징 관련 파라미터가 안넘어가요` 같이요.

**Comment by tom-axisj** [comment]
```
{"page":{"pageCount":0,"listCount":20,"pageNo":1},"list":[{"RNUM":1,"ADVERTISERNAME":"DHL코리아","BRANDNAME":"DHL","CATE3NAME":"특급운송서비스","CATE2NAME":"운송","CATE1NAME":"서비스"}],"msg":"data"}
```
여기서 pageCount는 페이지의 갯수 인데요. 0 인건 이상하구요.

**Comment by zeroty** [comment]
제 생각에는 다른 라이브러리의 경우 total count와 list만 받아서 클라이언트 쪽에서 

paging을 구현하는데 AXGrid의 경우 java단에서 pageCount까지 계산해서 줘야해서 

혼동이 오시는 것 같네요.

float pageNo = Integer.parseInt(paramMap.get("pageNo").toString());
float pageSize = Integer.parseInt(paramMap.get("pageSize").toString());

int pageCount = (int) Math.ceil(listCount / pageSize);

* float으로 데이터를 캐스팅하지 않을 경우 정상값이 나오지 않을 수 있습니다.

이런 식으로 페이지 카운트를 직접 만들어서 추가해주셔야 합니다.

**Comment by sparkkong** [comment]
모두모두 감사드립니다.
제가 요며칠 밤늦게 까지 작업해서 그랬던건지 pageCount가 0이었던걸 인지하지 못했습니다.
(데모페이지에 있는것과 몇번씩 비교했었는데..ㅠㅜ)
pageCount가 구해지고 나서는 문제없이 작동됩니다.

감사합니다.^^

**Comment by tom-axisj** [comment]
늦게까지 고생하신다니 마음이 짠하네요. 어쩌면 액시스제이를 왜 사용했냐는 딴지를 받으실 수도 있겠다.  라는 비관을 잠시합니다. 그런말 나오지 않을 수 있게 노력해야 겠습니다.

**Comment by sparkkong** [comment]
아닙니다. 너무너무 잘쓰고 있습니다.
항상 감사하게 생각하고 있습니다^^
