### ISSUE TITLE
[필독] [모임안내] 액시스제이 사용자 교육 및 친목도모

### ISSUE THREAD

**Issue by tom-axisj** [axisj-com/axisj#468]
안녕하세요 4월 2,3번째 중에 하루를 정하여 액시스제이 사용자 교육 및 저녁식사 자리를 계획중입니다.
본격적인 행사준비 전에 참가자 조사 중입니다.
참가하실 의향이 있으신 분은 댓글로 참석여부를 남겨 주시기 바람니다.

**Comment by KimJM** [comment]
참가합니다 ^~^

**Comment by hyunjun19** [comment]
참석이요~

**Comment by groovedk** [comment]
주중으로 건의해봅니다 헛헛

**Comment by lhslive** [comment]
4월중이면 참석 가능합니다!

**Comment by Jo-Jong-gyun** [comment]
살포시 참석 의사 비추고 갈게요^^

**Comment by tom-axisj** [comment]
@Jo-Jong-gyun 무조건 나오시는 것으로 하세요.
대략 7~8분 정도가 모이실 것 같네요. 

4월 16일이나 4월 22,23일 예상합니다.

**Comment by llois** [comment]
참석합니다~

**Comment by tom-axisj** [comment]
개인사정으로 행사를 못하게 되었습니다. 빨리 알려드리지 못해 죄송합니다.
조만간 자리를 만들어 보겠습니다.
