### ISSUE TITLE
AXSearch selectbox AXBind 처리

### ISSUE THREAD

**Issue by zeroty** [axisj-com/axisj#469]
안녕하세요.

AXSearch에서 selectbox타입을 아래와 같이 추가하다가 발견한건데요.

    {label:"고객사", labelWidth:"100", type:"selectBox", width:"", key:"BP_CD", addClass:"", valueBoxStyle:"", value:"",
	                              options: [],
	                              AXBind: {
	                                  type: "select", config: {
	                                	  
	                                	  reserveKeys: {
	         	                  				options: "systemInfoList",
	         	                  				optionValue: "SYS_NO",
	         	                  				optionText: "SYS_NAME"
	         	                  			 },
	         	                  			 
	                                	contentType: "application/json; charset=utf-8", //추가해도 text/html으로 전송하여 java method매핑이 안됨.
	                                	dataType: "json",
	                                  	ajaxUrl: "/json/getMaCodes.json",
	                                  	ajaxPars: {}, 
	                                  	ajaxAsync: true,
										isspace: true, isspaceTitle: "선택하세요",
										setValue: "",
										alwaysOnChange: true,
	                                     onChange: function() {
	                                  	}
	                                  }
	                              }
	                          },

위와 같이 ContentType을 json타입으로 전송하고 싶어서 아래와 같이 임시로 소스를 수정하여 쓰고 있

습니다.

bindSelect: function (objID, objSeq) {
...
if (obj.config.ajaxUrl) {

			var url = obj.config.ajaxUrl;
			var pars = obj.config.ajaxPars;
			var contentType =  obj.config.contentType; //임의대로 추가함
...
new AXReq(url, { 
	                contentType: contentType, //임의대로 추가함.

bindSelect에도 contentType변경할 수 있도록 보완 부탁드립니다.

또 한가지는,

selectbox를 동시에 여러개 ajax로 가져오면 가장 마지막에 가져온 값 기준으로 앞에 셀렉스박스도 다 바뀌는 현상이 있네요.

**Comment by tom-axisj** [comment]
데이터가 다르게 되지 않는 다는 건 아래 샘플에서 확인 해보시구요.
http://dev.axisj.com/samples/AXSelect/select-custom.html

contentType를 설정하는 것은 확장 하는 김에 좀 다양하게 아래과 같이 추가되었습니다.
https://github.com/axisj-com/axisj/blob/dev/lib/AXSelect.js#L343

**Comment by zeroty** [comment]
위 예제의 경우 각각 다른 url를 가지나 저같은 경우 컨트롤러에서 List안에 3개의 리스트를 추가하여 데이터를 전송하고 있습니다.

    {label:"고객사", labelWidth:"100", type:"selectBox", width:"", key:"BP_CD", addClass:"", valueBoxStyle:"", value:"",
	                        	  options:[],
	                        	  AXBind:{
	                                    type:"select", config: {
	                                    
	                                    }
	                                }
	                          },
	                          {label:"시스템", labelWidth:"100", type:"selectBox", width:"", key:"SYS_NO", addClass:"secondItem", valueBoxStyle:"", value:"",
	                                options:[],
	                                AXBind:{
	                                    type:"select", config: {
	                                    	reserveKeys: {
	                            				options: "systemInfoList",
	                            				optionValue: "SYS_CODE",
	                            				optionText: "SYS_NAME"
	                            			},
	                                    	contentType: "application/json; charset=utf-8",
	                                    	ajaxUrl: "/json/getMaCodes.json", ajaxPars: "", ajaxAsync: true,
											isspace: true, isspaceTitle: "선택하세요",
											setValue:"",
											alwaysOnChange: true,
	                                        onChange:function(){
	                                            //toast.push(Object.toJSON(this));

	                                        }
	                                    }
	                                }
	                            },
	                            {label:"진행상태", labelWidth:"100", type:"selectBox", width:"", key:"PROGRESSION", addClass:"secondItem", valueBoxStyle:"", value:"N",
	                                options:[],
	                                AXBind:{
	                                    type:"select", config: {
	                                    	reserveKeys: {
	                            				options: "procStatList",
	                            				optionValue: "CODE",
	                            				optionText: "CODE_NAME"
	                            			},
	                                    	contentType: "application/json; charset=utf-8",
	                                    	ajaxUrl: "/json/getMaCodes.json", ajaxPars: "", ajaxAsync: true,
											isspace: true, isspaceTitle: "선택하세요",
											setValue:"",
											alwaysOnChange: true,
	                                        onChange:function(){
	                                            //toast.push(Object.toJSON(this));

	                                        }
	                                    }
	                                }
	                            }


obj.config.options = res[cfg.reserveKeys.options];
trace("@@@@@@@@@@@@@@@@@@@@@@@@@@@@", cfg.reserveKeys.options);

이와 같이, 로그를 찍어보면.

arg[0] : @@@@@@@@@@@@@@@@@@@@@@@@@@@@, arg[1] : procStatList
AXJ.all.js:697 undefined
AXJ.all.js:697 arg[0] : @@@@@@@@@@@@@@@@@@@@@@@@@@@@, arg[1] : procStatList
AXJ.all.js:697 undefined
AXJ.all.js:697 arg[0] : @@@@@@@@@@@@@@@@@@@@@@@@@@@@, arg[1] : procStatList
AXJ.all.js:697 undefined

reserveKey가 개별로 먹지 않고, 가장 마지막 리저브키의 options가 3개 다 표시됩니다.

**Comment by tom-axisj** [comment]
http://dev.axisj.com/samples/AXSearch/misc.html
샘플에서 테스트 해보았습니다.

아마도 관련 패치 전 버전으로 개발중이신것 같습니다.
릴리즈를 사용하시면 최신 소스가 아니실 것 같습니다.
최신소스는 dev브랜치에 있습니다. (참고로 릴리즈는 매달 24일쯤 이루어 집니다.)

**Comment by zeroty** [comment]
아 dev브랜치가 별도로 있었네요. dev브랜치에서 받아서 테스트해보니 잘되네요. 감사합니다.
