### ISSUE TITLE
AXToolBar 에서 상단메뉴 타이틀 클릭시 서브메뉴 펼치기

### ISSUE THREAD

**Issue by utobiz** [axisj-com/axisj#470]
AXToolBar 에서 최상단 label명 클릭시 onclick 이벤트 발생명령에
하위메뉴 펼치는 함수나 실행문이 있습니까?

즉 label명 우측 화살표를 통해 풀다운 시킬 수 있지만, 제목을 눌러서 바로 풀다운 시킬 수는 없는지요?

**Comment by tom-axisj** [comment]
dev 브랜치에 수정된 버전이 커밋되었습니다.

onclick이 없거나 false이면 expand되도록 수정되었습니다.
