### ISSUE TITLE
[질문]Grid Editor에서 ColSeq:1 선택값에 따라 ColSeq2의 AxBind파라미터 값을 동적으로 생성하고 싶을 경우

### ISSUE THREAD

**Issue by narsisya** [axisj-com/axisj#473]
Grid Editor에서 ColSeq:1 선택값에 따라 ColSeq2의 AxBind파라미터 값을 동적으로 생성하고 싶을 경우

ColSeq의 입력값을 가져와서 AXBind의 ajaxPar에 세팅할수 있는 방법을 알고 싶습니다.

**Comment by tom-axisj** [comment]
현재 관련한 기능이 없습니다. 업데이트시에 고민하여 적용하겠습니다.

**Comment by narsisya** [comment]
네 감사합니당. ^^;
