### ISSUE TITLE
AXUpload5 질문있습니다.

### ISSUE THREAD

**Issue by boxkie** [axisj-com/axisj#474]
![2015-03-22 17 15 44](https://cloud.githubusercontent.com/assets/10544177/6768557/21fb4908-d0b7-11e4-9fde-7848483e04e0.PNG)
사진이 잘 보이시려나 모르겠네요.

MVC model
Spring 으로 구현중입니다.

upload ajax 메서드 리턴을 
{
fileKeys=
[{
thumbUrl=/axisJTest/upFile/thum/pop4.jpg, uploadedPath=D:/workZone/o_world/axisJTest/src/main/webapp/upFile/,
type=jpg,
saveName=pop4.jpg,
fileSize=68460,
name=pop4.jpg
}]
}
이렇게 리턴했습니다.
upload contorller 쪽에서 파일, 썸네일 업로드가 정상적으로 이루어 지는것을
확인하였고
리턴한 후 오류도 없습니다.
그런데 리턴후에 나오는 썸네일 이미지가 나오지 않네요.
정상적으로 리턴한것같은데 원인을 알수 있을까요?

**Comment by tom-axisj** [comment]
캡쳐에 답이 있습니다.

![2015-03-22 6 30 27](https://cloud.githubusercontent.com/assets/5884902/6768755/91033dce-d0c1-11e4-9671-7b52abbdf416.png)

background-image값이 다른것 같습니다.

**Comment by boxkie** [comment]
if(res[cfg.fileKeys.thumbPath]){
					jQuery("#" + cfg.queueBoxID).find("#"+itemID+" .AXUploadIcon").css({
						"background-image":"url('"+(res[cfg.fileKeys.thumbPath]||"").dec()+"')"
					}).addClass("AXUploadPreview");
				}else{
					jQuery("#" + cfg.queueBoxID).find("#"+itemID+" .AXUploadIcon").css({"background-image":"url()"});
					jQuery("#" + cfg.queueBoxID).find("#"+itemID+" .AXUploadIcon").html((res[cfg.fileKeys.type]||"").dec().replace(".", ""));
				}

thumbUrl 에 값이 있으면 값으로 대체 되는게 아닌가요?

**Comment by tom-axisj** [comment]
그러지 마시고 네트워크 탭에서 response를 확인해보세요.

**Comment by boxkie** [comment]
![2015-03-22 20 26 51](https://cloud.githubusercontent.com/assets/10544177/6769119/d3bb5e0c-d0d1-11e4-99f6-1d8cd5521091.PNG)
이렇게 나왔습니다

**Comment by tom-axisj** [comment]
![2015-03-22 8 39 01](https://cloud.githubusercontent.com/assets/5884902/6769171/7f491786-d0d3-11e4-9c64-a9f7970530ad.png)
조금 다르신 것 같아요

**Comment by boxkie** [comment]
![2015-03-22 20 48 56](https://cloud.githubusercontent.com/assets/10544177/6769212/ed46d088-d0d4-11e4-8691-9159607efdff.PNG)
![2015-03-22 20 49 02](https://cloud.githubusercontent.com/assets/10544177/6769213/eea399ac-d0d4-11e4-813d-00598f8cab6a.PNG)

으음.. 동일하게 맞춰줘도 그렇네요 아까보다는 한 단계 나아진듯하지만 ㅎ
계속 이것저것 해봐야겠습니다. 늦은시간에 답변주셔서 감사합니다 ^^

**Comment by tom-axisj** [comment]
여기 보시면 
https://github.com/axisj-com/axisj/blob/master/samples/AXUpload5/fileUpload.php#L32
리턴 할 때 thumbUrl 을 쓰는데 thumbPath를 쓰시네요.

물론 여기서 
https://github.com/axisj-com/axisj/blob/master/samples/AXUpload5/index.html#L75
설정 할 수 있는데. 설정데로 안되신다면 제 실수 인 것 같구요. 한번 확인 해보세요

**Comment by boxkie** [comment]
아.. 제가 이미지가 안 떠서 저거 바꿔보기도하고 type 에 .jpg를 jpg 로 리턴해보기도 하고 이것저것해서
그렇게 넘어갔네요. 
fileKeys 이녀석으로 한번 더 싼게 문제가 되었던거 같습니다.
404 not found 가 반갑네요 ㅎ
이클립스라서 실경로 잡아주면 이미지 잘 뜰듯합니다.

감사합니다 ^^
