### ISSUE TITLE
grid에서 colGroup  display:false시 문제점..

### ISSUE THREAD

**Issue by gjjoo** [axisj-com/axisj#475]
(1). 작성일에 display:false를 설정하였습니다.
![1](https://cloud.githubusercontent.com/assets/10864943/6774243/246912ec-d161-11e4-93e8-e33c98563a9b.png)

(2).사진과 같이 작성일이 잘 빠져서 나오고 있네요.
![2](https://cloud.githubusercontent.com/assets/10864943/6774253/3926a3a2-d161-11e4-8133-764bf93f7212.png)

(3).이제 작성일을 display시키기 위해 체크 하여 나타나게 했습니다.
![3](https://cloud.githubusercontent.com/assets/10864943/6774261/49d22c1c-d161-11e4-8f6b-2a35e1fddd14.png)

(4). 여기서 추가나 수정을 하여 edit할 시 빨간색 줄 그어진 부분처럼 안맞는게 나옵니다...
![4](https://cloud.githubusercontent.com/assets/10864943/6774268/5b956306-d161-11e4-989a-9008df6b0a66.png)

이리저리 테스트 해봐도 계속 저현상이네요 ㅠㅠ 

한번 봐주셨으면 합니다...

**Comment by hyunjun19** [comment]
설정 구문도 같이 보여주세요.
알려주신 정보가 너무 적습니다.
많이 알려주실 수록 빠르고 정확한 답변이 가능합니다.

♡♥♧♣ [필독] 이슈를 남기시는 분들께. ♡♥♧♣ ♡♥♧♣ ♡♥♧♣ ♡♥♧♣ ♡♥♧♣ ♡♥♧♣ #368
https://github.com/axisj-com/axisj/issues/368

**Comment by gjjoo** [comment]
1. 작성일에 display:false를 설정하였습니다.
![1](https://cloud.githubusercontent.com/assets/10864943/6774243/246912ec-d161-11e4-93e8-e33c98563a9b.png)

2.사진과 같이 작성일이 잘 빠져서 나오고 있네요.
![2](https://cloud.githubusercontent.com/assets/10864943/6774253/3926a3a2-d161-11e4-8133-764bf93f7212.png)

3.이제 작성일을 display시키기 위해 체크 하여 나타나게 했습니다.
![3](https://cloud.githubusercontent.com/assets/10864943/6774261/49d22c1c-d161-11e4-8f6b-2a35e1fddd14.png)

4. 여기서 추가나 수정을 하여 edit할 시 빨간색 줄 그어진 부분처럼 안맞는게 나옵니다...
![4](https://cloud.githubusercontent.com/assets/10864943/6774268/5b956306-d161-11e4-989a-9008df6b0a66.png)


이리저리 테스트 해봐도 계속 저현상이네요 ㅠㅠ 

한번 봐주셨으면 합니다...

**Comment by tom-axisj** [comment]
버그가 맞습니다. 
급한일이 정리되는 대로 수정하겠습니다. 감사합니다.

**Comment by KimJM** [comment]
버그 관련하여 수정을 하였습니다. dev 브랜치 다시 받으셔서 한번 확인 부탁드리고 
이상 있으시면 말씀해주세요.

**Comment by gjjoo** [comment]
Good!! 감사합니다~
