### ISSUE TITLE
Tree 관련 하여 질문 드립니다.

### ISSUE THREAD

**Issue by MainC** [axisj-com/axisj#476]
안녕하세요. Axisj Tree Component를 알아보던 중 궁금 한 사항이 몇개 있어 이렇게 이슈로 질문 드리게 되었습니다.

1) 체크트리를 사용 시 -1이미지 처럼 두 컬럼으로 나뉘어 특정 컬럼에 모든 체크박스가 들어간 것이 아닌 -2 처럼 컬럼 하나에 Title 앞 부분에 체크박스가 오도록 하는 옵션이 있을까요?
(없다면 기능 지원 해주실 수 있으신가요..?)
-1 
![tree1](https://cloud.githubusercontent.com/assets/4474131/6773279/308eb11c-d152-11e4-866a-8f1f88e41842.png)
-2
![tree2](https://cloud.githubusercontent.com/assets/4474131/6773280/33bf7de4-d152-11e4-9c16-1e67c2a1465a.png)

2) 트리자체가 테이블을 기반으로 만들어 진 것 처럼 보이는데, 혹시 Tree도 (Big data 시)
Virtual Scolling 지원해주는 옵션이 있나요?
(없다면 기능 지원 해주실 수 있으신가요..?)

**Comment by tom-axisj** [comment]
2번의 경우에는 지금 작업중인 코드가 있어서 추후 반영될 예정입니다. 
1번의 경우에는 조금 고민이 되는 옵션입니다.

**Comment by MainC** [comment]
@tom-axisj 
2번의 Scroll Virtualization은 Due Date가 언제쯤인지 알 수 있을까요?
