### ISSUE TITLE
AXUpload 관련

### ISSUE THREAD

**Issue by volcanas** [axisj-com/axisj#477]
Manual Upload 시 uploadUrl:"uploadFile.php" 로 설정하면 첨부한 파일 수가 2개면 
uploadFile.php 를 2번 호출 하던데요..  

uploadFile.php를 한번만 호출하여 선택한 첨부파일 2개를 한번에 저장하려고 하는데요..
config 설정값 변경으로 한번만 호출이 가능한가요?

**Comment by hyunjun19** [comment]
http://dev.axisj.com/samples/AXUpload5/manualUpload.html
원하는 시점에 저장하는 기능은 가능합니다. 하지만 uploadFile.php는 파일 갯수만큼 호출됩니다.

**Comment by volcanas** [comment]
답변 감사합니다..
