### ISSUE TITLE
AXUpload5 manual 관련 질문있습니다.

### ISSUE THREAD

**Issue by boxkie** [axisj-com/axisj#478]
메뉴얼 쪽 업로드의 경우 이미지를 추가 하고 업로드를 누르면

ajax 로 업로드가 되고 썸네일과 삭제 버튼이 생깁니다.

그렇다면

1. 업로드 누르기 전에 추가한 이미지에대해서 선택적 삭제(취소)가 되게 하는 기능이 있나요?

2. 업로드 누르기 전에 추가한 이미지에대해서 썸네일이 나오도록하는 기능이 있나요?

나눠서 적어보니 글이 뭔가 딱딱하네요;;

**Comment by hyunjun19** [comment]
1. 선택적 삭제는 API가 없습니다. `clearQueue` 메서드를 참고해서 구현하세요.
```js
function (){
	//큐제거
	jQuery.each(this.queue, function(){
		jQuery("#"+this.id).hide(function(){
			jQuery(this).remove();
		});
	});
	this.queue = [];
}
```
2. 업로드 전에 썸네일이 나오도록 하는 방법은 순수 웹에서는 불가능합니다.

**Comment by boxkie** [comment]
https://blueimp.github.io/jQuery-File-Upload/
아.. 이 플러그인이 순수 웹이 아닌가요?
로컬에서 구현했을때는 업로드까지 확인을 해서 가능할까 싶었는데 아쉽네요.

삭제는 한번 구현해 봐야겠습니다. 감사합니다.

**Comment by hyunjun19** [comment]
첨부해주신 주소는 유용해 보이네요.
내부적으로 적용을 검토해 보도록 하겠습니다.

**Comment by hyunjun19** [comment]
bcebbba514f5098cacfd2926f5331143f0a9f60e 에서 수정되었습니다.

API 수정사항이 없으니 그냥 기다렸다가 다음달 릴리즈를 반영하시면 됩니다.

**Comment by boxkie** [comment]
네 감사합니다 ^^

**Comment by tom-axisj** [comment]
:+1:
