### ISSUE TITLE
selectbox ajax처리시 문의

### ISSUE THREAD

**Issue by gjjoo** [axisj-com/axisj#479]
{
	result:"ok",
		options:[
		{code:1, name:"서울"},
		{code:2, name:"대전"},
		{code:3, name:"부산"}
	],
	etcs:""
}

위와 같이 optionValue, optionText를 사용하지 않고, key값을 커스터마이징 해서 사용하고 싶습니다..

**Comment by zeroty** [comment]
아래 제 질문들 참조하시면 될 것 같은데..핵심은 reserveKeys이고, result는 필수로 ok로 넘겨주셔야 넘어갑니다.

// 예약어 설정

29.		$("#ax-select-02").bindSelect({
30.			reserveKeys: {
31.				options: "options",
32.				optionValue: "code",
33.				optionText: "name"
34.			},
35.			ajaxUrl: "selectData-02.php",
36.			ajaxPars: "",
37.			onchange: function(){
38.				trace("change : " + Object.toJSON(this));
39.			}
40.		});

http://dev.axisj.com/samples/AXSelect/select-custom.html

참조하시면 될 듯 합니다.

**Comment by lhslive** [comment]
:+1:

**Comment by gjjoo** [comment]
감사합니다!!
