### ISSUE TITLE
AXCalendar 아이콘위치 문의 드립니다..

### ISSUE THREAD

**Issue by sparkkong** [axisj-com/axisj#480]
Calendar를 참 유용하게 사용하고 있는데, 몇가지 문제가 있어서 문의드립니다.
데모페이지처럼 display:none이 아닌 상태에서 바인드하면 문제가 없으나, 
숨겨진상태에서 바인드되면 아이콘의 위치가 고정되지 않습니다.
사이트 특성상 검색조건은 숨겨놓고 필요할때만 보여주는 구조입니다.

먼저 첨부된 파일을 보시면 달력아이콘위 위치가 제자리를 찾지 않습니다.
기간선택 버튼을 눌렀을때 하단 박스를 보여주는데 그때 증상이 나타납니다.

![2](https://cloud.githubusercontent.com/assets/6268169/6794641/ae5eaca8-d217-11e4-8381-c51d51901a7b.png)

$("#twinEnddt").bindTwinDate({
   align:"center", 
   valign:"center", 
   separator:"-", 
   startTargetID:"twinStartdt"
 });
<input type="text" name="twinStartdt" id="twinStartdt" value="" style="width:100px" /> - 
<input type="text" name="twinEnddt" id="twinEnddt" value="" style="width:100px" />

그리고 지금은 아이콘을 클릭해야만 달력이 보이는데, text box를 클릭해도 달력이 뜨도록 할 수 있나요?

**Comment by tom-axisj** [comment]
아이콘이 안보이는 상태에서 브라우저를 조금 리사이즈 하면 보여지나요?

**Comment by lhslive** [comment]
숨겨진 상태가 해제된 이후에 바인드 해보세요.
대부분의 자바스크립트 기반 UI 컴포넌트들은 해당 엘레먼트의 포지션 기반으로 위치를 잡는데
화면상에 display되고 있지 않을때 바인드가 되면 기준 위치가 뒤틀리는 경우가 많습니다.

**Comment by sparkkong** [comment]
리사이즈하면 잘 보입니다.
또한 lshlive님 말씀처럼 화면상에 보일때마다 바인딩처리하니까 정상적으로 보입니다. 감사합니다.
그런데 혹.. text box를 클릭해도 달력이 뜨도록 할 수 있나요?

**Comment by lhslive** [comment]
```
<input type="text" name="" id="AXInputDate" class="AXInput W100" onclick="calendar(this);"/>
```


```
	function calendar(obj){
		var id = $(obj).attr("id");
		$("#inputBasic_AX_"+id+"_AX_dateHandle").click();
	}
```


적당히 응용 하시면....
