### ISSUE TITLE
AXGrid 페이징 관련 오류

### ISSUE THREAD

**Issue by zeroty** [axisj-com/axisj#482]
![default](https://cloud.githubusercontent.com/assets/1608782/6796181/948e5d54-d231-11e4-8813-a004356f77ea.png)

위 사진처럼 페이징 셀렉트박스 1번위에 조그만하게 개체가 하나 더 존재합니다. 그걸 클릭시 오류가 나네요.

**Comment by tom-axisj** [comment]
버그 픽스된 소스가 dev브랜치에 커밋되었습니다.
버그 찾아주셔서 감사합니다.
