### ISSUE TITLE
AXGrid editor에서 select 값을 ajax로...(문의)

### ISSUE THREAD

**Issue by gjjoo** [axisj-com/axisj#485]
1. 
![20150324_180611](https://cloud.githubusercontent.com/assets/10864943/6798468/cfe65018-d250-11e4-882f-3ad3cef28fe3.png)

2.
![20150324_180925](https://cloud.githubusercontent.com/assets/10864943/6798483/efe0f184-d250-11e4-9cbd-c0096ddfb6b6.png)

1번과 같은 결과를 2번과 같이 바꾸고 싶습니다.. 내공이 부족하여 아무리 해봐도 잘 안되네요... 도와주세요~

**Comment by tom-axisj** [comment]
```
{colSeq:2, align:"left", valign:"top", 
    form:{
        type:"select", 
	    value:function(){
            return this.value.dec();
        }, 
	    validate:function(){
            return true;
        }
    },
    AXBind:{
		type:"select", config:{
	        ajaxUrl:"selectorData.php",
	        ajaxPars:"",
	        onChange:function(){

	        }
        }
    }
},
```
이렇게~

**Comment by gjjoo** [comment]
(1)
![20150325_090256](https://cloud.githubusercontent.com/assets/10864943/6815511/e4d2c5f6-d2cd-11e4-8197-79a9d326f8b6.png)

(2)
![20150325_090346](https://cloud.githubusercontent.com/assets/10864943/6815513/ebab9e8e-d2cd-11e4-98bc-4a808d57d292.png)

알려주신 방법대로 해서 editor.html을 (1)번 사진과 같이 수정했습니다. 그런데 ajax호출도 안되고 2번사진처럼 아무것도 뜨지를 않네요.. 클릭을 해봐도 반응이 없습니다. 크롬 Network에 응답이 오질 않네요..
(2015-03-25, 09시에 혹시나 해서 dev 브렌치로 받아서 테스트 해봤는데도 잘안되네요.. 한번만 더 도와주세요 ㅠ)

**Comment by KimJM** [comment]
`AXBind:{type:"selector", config:{` 를 `AXBind:{type:"select", config:{` 로 변경 해보시겠어요??

**Comment by gjjoo** [comment]
아 테스트한다고 selector 해논 걸 수정안했네요.. 이제 됩니다 감사합니다!!

**Comment by gjjoo** [comment]
한가지더 질문!!
현재 select ajax 해서 바인딩 처리하는 부분이 gride editor쪽 이잖아요??
수정할라고 클릭했을때 그리드에 있는 값을 select에 바인딩 해서 바로 보여주고 싶은데, 감이 안잡힙니다. ㅠㅠ

**Comment by KimJM** [comment]
http://dev.axisj.com/samples/AXGrid/editor.html 예제에서 그리드 행에 오른쪽 마우스 클릭 후 
수정하기 메뉴 같은 기능을 말씀하시는건가요?? 이 기능은 샘플 소스 참고하시면 됩니다만..
