### ISSUE TITLE
AXUpload5 preview 이미지 출력부분 질문있습니다.

### ISSUE THREAD

**Issue by boxkie** [axisj-com/axisj#486]
이번에 이미지 저장 경로를 웹 루트 밖으로 빼서 저장 했습니다.

그래서 이미지 불러오는 부분을 전자정부 getImage.do

메서드 부르는 방식으로 썸네일 이미지를 뿌려주려고 하는데 

if(res[cfg.fileKeys.thumbPath]){
					jQuery("#" + cfg.queueBoxID).find("#"+itemID+" .AXUploadIcon").css({
						"background-image":"url('"+(res[cfg.fileKeys.thumbPath]||"").dec()+"')"
					}).addClass("AXUploadPreview");
				}else{
					jQuery("#" + cfg.queueBoxID).find("#"+itemID+" .AXUploadIcon").css({"background-image":"url()"});
					jQuery("#" + cfg.queueBoxID).find("#"+itemID+" .AXUploadIcon").html((res[cfg.fileKeys.type]||"").dec().replace(".", ""));
				}

이 부분 소스가 백그라운드 css로 불러오는 형태라

웹 루트 외부로 접근이 불가능합니다.
혹시 이미지 뿌려주는 preview 부분을 
img 태그로 뿌려주는 방법이 없을까요?

어느정도 분석은 되는데 이 부분을 어떻게 수정해야 할지 좀 감이 잡히지 않습니다.

**Comment by tom-axisj** [comment]
가상 폴더를 만들어서 경로를 잡아주면 되지 않을까요? css에서 웹에보이지 않는 이미지를 넣을 방법은 없을 겁니다.

**Comment by boxkie** [comment]
가상 폴더를 만들어준다는 의미가 어떤것인지 알 수 있을까요?

CSS 에서 처리하는건 제 생각에도 불가능해 보이네요;

**Comment by tom-axisj** [comment]
WAS에 가상 폴더를 만드는게 있어요. 
사용자에게 보여질 폴더명을 정하고 실제 폴더를 연결 할 수 있지요.
WAS마다 설정이 다르기 때문에 제가 정확히 가이드 해드리긴 어렵겠습니다.

@hyunjun19 @lhslive @KimJM 소환

**Comment by hyunjun19** [comment]
방금 테스트 해봤는데 그냥 /cmm/fms/getImage.do 사용하시면 됩니다.

```jsp
<div style="background: url('http://localhost:8080/cmm/fms/getImage.do?atchFileId=westzero.png');width: 200px;height: 200px;"></div>
```

![image](https://cloud.githubusercontent.com/assets/421863/6802883/2a675642-d277-11e4-9204-86c2c02e243e.png)

**Comment by tom-axisj** [comment]
:+1:

**Comment by boxkie** [comment]
아... 스프링 3.0으로 하다가 2.5 로 바꾸면서 생긴 실수인가보네요;;
내일 한번 다시 해봐야겠습니다.
답변 감사합니다 ^^

**Comment by zeroty** [comment]
대용량파일의 경우 FileController를 거치는게 좋지만 저런 이미지성인 경우 컨트롤러를 타는 것보다는 tom님 말씀처럼 심볼릭 링크를 걸어서 처리하시는 게 좋습니다. (동시접속이 많으면 Exception이 자주 일어남)

Tomcat을 웹서버로 쓰신다면 conf/server.xml에 allowLinking옵션을 true로 하시면 심볼릭 링크 건 디렉토리도 WAS가 인식하게 됩니다.

<Context  ... 중략 allowLinking="true"></Context>

**Comment by boxkie** [comment]
네 도움 되는 말씀 감사합니다. 컨트롤러 쪽으로 접근해서 짜려는 이유는

파일이 저장될때 확장자를 제외해서
확장자 없이 파일 형태로 저장되기 때문에 Controller를 거치게 짜고 있습니다.

동시접속을 생각한다면 이 부분도 생각해볼 문제인듯하네요.
말씀주신 방법은 이번 개발 끝나고 한번 찾아봐야겠습니다.
답변 감사합니다^^
