### ISSUE TITLE
AXGrid(viewMode Mobile)  & AXGrid RWD  페이징 관련 문의

### ISSUE THREAD

**Issue by sunydady** [axisj-com/axisj#487]
안녕하세요!!!!!!
너무나 감사히 고맙게 axisj  공부 하는 1인!!! 입니다.

1.0.12 사용중이다 이번에 13 이 나와서 두리번 거리던중
그리드가  인제 반응 까지 하더군요!!!
빨리써고고 싶던차 이것 저것 보다보니
쪼매 이상한 부분이 있어서요~

1. 아래에도 글이 있는데 start count 위에 하나가 더 생김
![1](https://cloud.githubusercontent.com/assets/6290515/6799495/bb0815e2-d259-11e4-9033-401820a741d1.png)

2.마지막 페이지 에서 다음 페이지 클릭시 오류
![2](https://cloud.githubusercontent.com/assets/6290515/6799497/bf1331c6-d259-11e4-9239-e651f96d0e80.png)

3.2번상황 이후에 는 드롭다운 으로 페이지 이동도 안됨 , 새로고침 뿌니 방법이 없습니다~
![3](https://cloud.githubusercontent.com/assets/6290515/6799500/c1ac03cc-d259-11e4-9cf8-1cb3a6684779.png)

항상 감사하고있습니다.
화이팅!!!!!

**Comment by hyunjun19** [comment]
페이징 드랍다운에서 스크롤을 위로 끝까지 올리니까 1페이지 위에 빈칸이 나타나네요.
해당문제는 버그 같습니다.

**Comment by tom-axisj** [comment]
버그 픽스된 소스가 dev브랜치에 커밋되었습니다.
버그 찾아주셔서 감사합니다.
