### ISSUE TITLE
AXUpload5 Drag&Drop 관련

### ISSUE THREAD

**Issue by LeeAeHee** [axisj-com/axisj#489]
샘플사이트에 있는 소스를 이용하여 테스트했구요..
Modal창에서 파일 Drag&Drop 시에 파일이 중복해서 올라갑니다.
똑같은 소스로 일반 페이지에서 테스트 했을때는 이런 현상이 없었습니다.
이미지 첨부합니다.

![image](https://cloud.githubusercontent.com/assets/11202898/6820172/2359278e-d30f-11e4-916a-8e1e934ca5dc.png)

![image](https://cloud.githubusercontent.com/assets/11202898/6820180/30bc018a-d30f-11e4-832b-2a19a8d7c300.png)

**Comment by tom-axisj** [comment]
http://dev.axisj.com/samples/AXModal/index.html
에 "창열기" 버튼을 클릭하면 업로드페이지가 열리도록 했는데요.

![2015-03-25 11 43 15](https://cloud.githubusercontent.com/assets/5884902/6827074/c8c7ef78-d348-11e4-93e0-abd346d4ae69.png)

말씀하신 현상이 재현되지 않습니다. 브라우저 버전정보등, 좀더 자세한 사항을 알려주셔야 할 것 같습니다.

**Comment by LeeAeHee** [comment]
소스를 다시 확인 해보니 제 로직상 실수였네요.. upload 컴포넌트를 2개를 생성해 버려서 그런 것 같습니다. 확인해주셔서 감사합니다!.
