### ISSUE TITLE
AXUpload5 저장된 파일 목록 불러오기 관련 질문있습니다.

### ISSUE THREAD

**Issue by boxkie** [axisj-com/axisj#490]
Controller 쪽으로 한 게시물에 대하여 파일 목록을 만들어서 

return 했는데 오류가 납니다.

리턴되는 형태는 

[
{"mainImage":"true","id":"MF_AX_0","name":"ban.jpg","type":"jpg","saveName":"BBS_2015032503
12420170","fileSize":"69675","uploadedPath":"/cmm/fms/BoardFileDown.do?atchFileId=FILE_000000000448634&fileSn=0&dwldHistYn=N&bbsId=BBSMSTR_1445&fn=ban.jpg","thumbUrl":"/cmm/fms/FileDown.do?atchFileId=FILE_000000000448634&fileSn=0&thumbYn=Y"},
{"id":"MF_AX_1","name":"main5 - 복사본.jpg","type":"jpg","saveName":"BBS_201503250312422621","fileSize":"327696","uploadedPath":"/cmm/fms/BoardFileDown.do?
atchFileId=FILE_000000000448634&fileSn=1&dwldHistYn=N&bbsId=BBSMSTR_1445&fn=main5 - 
복사본.jpg","thumbUrl":"/cmm/fms/FileDown.do?atchFileId=FILE_000000000448634&fileSn=1&thumbYn=Y"},
{"id":"MF_AX_2","name":"pop1 - 복사본 - 복사본 - 복사본.jpg","type":"jpg","saveName":"BBS_201503250312425042","fileSize":"57105","uploadedPa
th":"/cmm/fms/BoardFileDown.do?atchFileId=FILE_000000000448634&fileSn=2&dwldHistYn=N&bbsId=BBSMSTR_1445&fn=pop1 - 복사본 - 복사본 - 복사본.jpg","thumbUrl":"/cmm/fms/FileDown.do?atchFileId=FILE_000000000448634&fileSn=2&thumbYn=Y"},
{"id":"MF_AX_3","name":"pop1 - 복사본 - 복사본.jpg","type":"jpg","saveName":"BBS_201503250312427953","fileSize":"57105","uploadedPath":"/cmm/fms/BoardFileDown.do?atchFileId=FILE_000000000448634&fileSn=3&dwldHistYn=N&bbsId=BBSMSTR_1445&fn=pop1 - 복사본 - 복사본.jpg","thumbUrl":"/cmm/fms/FileDown.do?atchFileId=FILE_000000000448634&fileSn=3&thumbYn=Y"}
]
id, name, type, saveName, fileSize, uploadedPath, thumbUrl, ,mainImage??

입니다.

처음에 오류를 확인하고 샘플에 올려주신 데이터를 확인해서 

[
{id:'MF_AX_0',name:'AX_1039820194.jpg',saveName:'AX_1039820194.jpg',type:'file',fileSize:'6
9675',uploadedPath:'/samples/AXUpload5/files/',thumbUrl:'files
%2FAX_1039820194.jpg',mainImage: true},
{id:'MF_AX_1',name:'AX_1138995254.png',saveName:'AX_1138995254.png',type:'file',fileSize:'1
9401',uploadedPath:'/samples/AXUpload5/files/',thumbUrl:'files%2FAX_1138995254.png',},
{id:'MF_AX_2',name:'AX_1206284124.png',saveName:'AX_1206284124.png',type:'file',fileSize:'1
9401',uploadedPath:'/samples/AXUpload5/files/',thumbUrl:'files%2FAX_1206284124.png',},
{id:'MF_AX_3',name:'AX_1249132755.jpg',saveName:'AX_1249132755.jpg',type:'file',fileSize:'5
7105',uploadedPath:'/samples/AXUpload5/files/',thumbUrl:'files%2FAX_1249132755.jpg',
}
]

이 형태로 response 가 일어나는것을 확인했고 최대한 비슷하게 return 이 일어나도록
맞춰줘도 오류가 나타납니다.

콘솔에 나타나는 에러 내용은

error : {"readyState": 4, "responseText": "[{\"mainImage\":\"true\",\"id\":\"MF_AX_0\",\"name\":\"ban.jpg\",\"type\":\"jpg\",\"saveName\":\"BBS_201503250312420170\",\"fileSize\":\"69675\",\"uploadedPath\":\"/cmm/fms/BoardFileDown.do?atchFileId=FILE_000000000448634&fileSn=0&dwldHistYn=N&bbsId=BBSMSTR_1445&fn=ban.jpg\",\"thumbUrl\":\"/cmm/fms/FileDown.do?atchFileId=FILE_000000000448634&fileSn=0&thumbYn=Y\"},{\"id\":\"MF_AX_1\",\"name\":\"main5 - 복사본.jpg\",\"type\":\"jpg\",\"saveName\":\"BBS_201503250312422621\",\"fileSize\":\"327696\",\"uploadedPath\":\"/cmm/fms/BoardFileDown.do?atchFileId=FILE_000000000448634&fileSn=1&dwldHistYn=N&bbsId=BBSMSTR_1445&fn=main5 - 복사본.jpg\",\"thumbUrl\":\"/cmm/fms/FileDown.do?atchFileId=FILE_000000000448634&fileSn=1&thumbYn=Y\"},{\"id\":\"MF_AX_2\",\"name\":\"pop1 - 복사본 - 복사본 - 복사본.jpg\",\"type\":\"jpg\",\"saveName\":\"BBS_201503250312425042\",\"fileSize\":\"57105\",\"uploadedPath\":\"/cmm/fms/BoardFileDown.do?atchFileId=FILE_000000000448634&fileSn=2&dwldHistYn=N&bbsId=BBSMSTR_1445&fn=pop1 - 복사본 - 복사본 - 복사본.jpg\",\"thumbUrl\":\"/cmm/fms/FileDown.do?atchFileId=FILE_000000000448634&fileSn=2&thumbYn=Y\"},{\"id\":\"MF_AX_3\",\"name\":\"pop1 - 복사본 - 복사본.jpg\",\"type\":\"jpg\",\"saveName\":\"BBS_201503250312427953\",\"fileSize\":\"57105\",\"uploadedPath\":\"/cmm/fms/BoardFileDown.do?atchFileId=FILE_000000000448634&fileSn=3&dwldHistYn=N&bbsId=BBSMSTR_1445&fn=pop1 - 복사본 - 복사본.jpg\",\"thumbUrl\":\"/cmm/fms/FileDown.do?atchFileId=FILE_000000000448634&fileSn=3&thumbYn=Y\"}]", "status": 200, "statusText": "OK"}

이렇게 나타납니다.
이렇게 저렇게 해결할려고 시도는 많이 해봤지만 해결이 되지않네요.

**Comment by tom-axisj** [comment]
```
id, name, type, saveName, fileSize, uploadedPath, thumbUrl, ,mainImage??
```

이것도 출력되는 건가요?

**Comment by boxkie** [comment]
아닙니다. 그 부분은 샘플 response 살펴 보다가 mainImage 라는 모르는게 있어서
파라미터 한번 적어본건데 질문 올리면서 빼는걸 깜빡했네요;;

**Comment by boxkie** [comment]
[{mainImage:true,id:'MF_AX_0',name:'ban.jpg',type:'jpg',saveName:'BBS_201503250234015410',fileSize:69675,uploadedPath:'/cmm/fms/BoardFileDown.do?atchFileId=FILE_000000000448615&fileSn=0&dwldHistYn=N&bbsId=BBSMSTR_1445&fn=ban.jpg',thumbUrl:'/cmm/fms/FileDown.do?atchFileId=FILE_000000000448615&fileSn=0&thumbYn=Y'}]

[{'mainImage':true,'id':'MF_AX_0','name':'ban.jpg','type':'file','saveName':'BBS_201503250234015410','fileSize':'69675','uploadedPath':'/cmm/fms/BoardFileDown.do?atchFileId=FILE_000000000448615&fileSn=0&dwldHistYn=N&bbsId=BBSMSTR_1445&fn=ban.jpg','thumbUrl':'/cmm/fms/FileDown.do?atchFileId=FILE_000000000448615&fileSn=0&thumbYn=Y'}]

[{"mainImage":true,"id":"MF_AX_0","name":"pop2.jpg","type":"file","saveName":"BBS_201503260223034960","fileSize":"41139","uploadedPath":"/cmm/fms/BoardFileDown.do?atchFileId=FILE_000000000448665&fileSn=0&dwldHistYn=N&bbsId=BBSMSTR_1445&fn=pop2.jpg","thumbUrl":"/cmm/fms/FileDown.do?atchFileId=FILE_000000000448665&fileSn=0&thumbYn=Y"}]

{"mainImage":true,"id":"MF_AX_0","name":"pop2.jpg","type":"file","saveName":"BBS_201503260223034960","fileSize":"41139","uploadedPath":"/cmm/fms/BoardFileDown.do?atchFileId=FILE_000000000448665&fileSn=0&dwldHistYn=N&bbsId=BBSMSTR_1445&fn=pop2.jpg","thumbUrl":"/cmm/fms/FileDown.do?atchFileId=FILE_000000000448665&fileSn=0&thumbYn=Y"}

{"mainImage":"true","id":"MF_AX_0","name":"pop2.jpg","type":"file","saveName":"BBS_201503260223034960","fileSize":"41139","uploadedPath":"/cmm/fms/BoardFileDown.do?atchFileId=FILE_000000000448665&fileSn=0&dwldHistYn=N&bbsId=BBSMSTR_1445&fn=pop2.jpg","thumbUrl":"/cmm/fms/FileDown.do?atchFileId=FILE_000000000448665&fileSn=0&thumbYn=Y"}

[{"mainImage":"true","id":"MF_AX_0","name":"pop2.jpg","type":"file","saveName":"BBS_201503260223034960","fileSize":"41139","uploadedPath":"/cmm/fms/BoardFileDown.do?atchFileId=FILE_000000000448665&fileSn=0&dwldHistYn=N&bbsId=BBSMSTR_1445&fn=pop2.jpg","thumbUrl":"/cmm/fms/FileDown.do?atchFileId=FILE_000000000448665&fileSn=0&thumbYn=Y"}]

으음.. 스프링 2.5 라서 String 형태로 리턴해주고있는데 그거때문일까요..
파라미터를 " , ' 로 싸서 일까요 [ 대괄호 때문일까요 type 이 file 이라서 일까요 ture 를 ', " 싸서일까요..

response 되는 json 객체 형태를(주의사항같은) 문서화 해두신게 있으신가요?

**Comment by tom-axisj** [comment]
```
[
    {},
    {},
    {}
]
```

이런식으로 하셔야 할 것 같은데요 그리고 무엇보다 이런 경우는 개발자도구 콘솔 > 네트워크 > 해당 url 상세보기에서 response를 보셔야 합니다. 거기에 제대로 나오면 서버데이터는 문제가 없겠습니다.

**Comment by boxkie** [comment]
"
public class AjaxJsonView extends AbstractView {

	@Override
	protected void renderMergedOutputModel(Map model,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
 
		response.setContentType("text/json");
		response.setHeader("Cache-Control", "no-cache");
		response.setCharacterEncoding("UTF-8");
 
		PrintWriter writer = response.getWriter();
		writer.write((String) model.get("ajaxJson"));  
		writer.close();
	}
}
"
답변 감사합니다. text/json 이 부분이  text/xml 로 되어있어서 발생한 오류 였습니다.
