### ISSUE TITLE
AXSearch 인풋폼 관련

### ISSUE THREAD

**Issue by zeroty** [axisj-com/axisj#491]
안녕하세요.

AXSearch안에 인풋폼안에 값을 넣고 엔터를 쳐도 아무 반응이 없네요.

onsubmit를 구현해줬는데도 그러네요.

AXSearch예제에서도 최초 index페이지에선 잘 되는데 RWD에선 코드 거의 비슷한 것 같은데 

안되는 이유가 무엇인지 도통 모르겠네요.

--------------------------------------------------------------------------------------------

AXSearch row에 type이 submit이 있을 경우에만 onsubmit이 실행되는 것 같네요.

보통 인풋폼 누르고 사람들이 엔터치면 조회되는 걸로 생각하는데 옵션을 설정할수 있도록

하면 좋을 것 같습니다.

**Comment by tom-axisj** [comment]
form 안에 input만 여러개 넣으시면 엔터를 쳐도 결과가 같으실 겁니다.
form 안에 input type=submit, button 이 있거나 input 태그가 하나 있을 때만 엔터입력시 form 서브밋이 됩니다.
같게 만들었습니다.
