### ISSUE TITLE
그리드 머지 관련 버그2

### ISSUE THREAD

**Issue by david80** [axisj-com/axisj#494]
![11](https://cloud.githubusercontent.com/assets/11273651/6823290/dfd6990e-d329-11e4-992f-c7a4fcbf4a86.gif)

grid: {
            target: new AXGrid(),
            get: function () { return this.target; },
            bind: function () {
                this.target.setConfig({
                    targetID: "page-grid-box",
                    theme: "AXGrid",
                    fitToWidth: true,
                    mergeCells: [0],
                    mediaQuery: {
                        mx: { min: 0, max: 767 },
                        dx: { min: 767 }
                    },
                    colGroup: [
                        { key: "s_cell_nm", label: "셀 유형", width: "100", align: "center", formatter: "dec" }
                    ],

컬럼이 한개였을 경우
mergeCells: [0],
0번인덱스 머지를  하면 셀유형 4건이 다른 명칭인데도 머지가 되버리네요

머지를 빼면 이렇게 나옵니다.
![localhost_20150325_200356](https://cloud.githubusercontent.com/assets/11273651/6823313/1affb09c-d32a-11e4-9e64-8e99d22dd42b.jpg)

**Comment by KimJM** [comment]
오늘자로 mergeCells 관련 버그 수정이있었습니다.
dev브랜치 다시 받아 확인 해주실수있으신지요??

**Comment by david80** [comment]
받아도 같은 현상이네요

**Comment by KimJM** [comment]
확인해보겠습니다^^

**Comment by david80** [comment]
dev브랜치 받은거로 다시 해보니 잘 되네요~ 캐시가 물고 있었나봐요 ㅎㅎㅎ

**Comment by KimJM** [comment]
:thumbsup:

**Comment by hyunjun19** [comment]
:+1:
