### ISSUE TITLE
그리드 온클릭시 언더파인드 에러 메시지창...

### ISSUE THREAD

**Issue by david80** [axisj-com/axisj#495]
![1](https://cloud.githubusercontent.com/assets/11273651/6837779/f3f14406-d393-11e4-8c80-f14b726ace38.png)

그리드 온클릭 시 이런 에러 메시지가 나오는데... 이전 버젼에는 이상 없었는데 최신 라이브러리 받은 후로 이런에러가 나오네요;;

grid: {
            target: new AXGrid(),
            get: function () { return this.target; },
            bind: function () {
                this.target.setConfig({
                    targetID: "page-grid-box",
                    theme: "AXGrid",
                    fitToWidth: true,
                    mediaQuery: {
                        mx: { min: 0, max: 767 },
                        dx: { min: 767 }
                    },
                    colGroup: [
                        { key: "emp_seq", label: "선택", width: "40", align: "center", formatter: "radio" },
                        {
                            key: "rowidx", label: "번호", width: "40", align: "center", formatter: function () {
                                return (this.index + 1);
                            }
                        },
                        { key: "duty_nm", label: "직책", width: "60", align: "center", formatter: "dec" },
                        { key: "emp_nm", label: "성명", width: "50", align: "center", formatter: "dec" },
                        { key: "salary_sum", label: "급여합계", width: "80", align: "right", formatter: "money" },
                        { key: "deduct_sum", label: "공제합계", width: "80", align: "right", formatter: "money" },
                        {
                            key: "_amt_pay", label: "지급액", width: "80", align: "right", formatter: function () {
                                return (this.item.salary_sum.number() - this.item.deduct_sum.number()).money();
                            }
                        }
                    ],
                    body: {
                        oncheck: function () {
                            fnObj.item.open("gridView", this.item); 
                            fnObj.dataLoad(this.item);              
                            fnObj.grid.get().setFocus(this.index);  
                        },
                        onclick: function () {
                            if (this.c != 0) fnObj.dataLoad(this.item);
                        },
                        ondblclick: function () {

                        },
                        addClass: function () {

                        },
                        onchangeScroll: function () {

                        }
                    },
                    page: { paging: false, status: { formatter: null } }
                });
            },
dataLoad: function (item_obj) {
            var url = pageUrl + "/SelectMasterView"; 
            var pars = "item_Key=" + item_obj.emp_seq;
            new AXReq(url, {
                debug: false, pars: pars, onsucc: function (res) {
                    if (!res.error) {
                        var item = res.rs;
                        var frm = document["table-form"];

                        item.salary_sum = item.salary_sum.money();
                        item.deduct_sum = item.deduct_sum.money();

                        $(frm).bindViewForm(item, "");
                        fnObj.grid_dtl.search(item.emp_seq);
                    } else {
                        AXMsg.alert(res.msg.dec());
                    }
                }
            });
        },

**Comment by KimJM** [comment]
````javascript
dataLoad: function (item_obj) {
        var url = pageUrl + "/SelectMasterView"; 
        var pars = "item_Key=" + item_obj.emp_seq;
        new AXReq(url, {
            debug: false, pars: pars, onsucc: function (res) {
                if (!res.error) {
                    var item = res.rs;
                    var frm = document["table-form"];

                    item.salary_sum = item.salary_sum.money();
                    item.deduct_sum = item.deduct_sum.money();

                    $(frm).bindViewForm(item, "");
                    fnObj.grid_dtl.search(item.emp_seq);
                } else {
                    AXMsg.alert(res.msg.dec());
                }
            }
        });
    }
},
````
소스만 보기에는 ajax에서 에러가나서 `AXMsg.alert(res.msg.dec());` 에서 나타는것 같은데요.
dataLoad 함수를 디버깅 해보시고 alert 가 발생하는 부분을 확인해주시면 감사하겠습니다.

**Comment by david80** [comment]
![2](https://cloud.githubusercontent.com/assets/11273651/6838707/49104a24-d3a1-11e4-9ae3-0a489fe1d582.png)


디버깅 해보니 여기에서 걸리네요.

**Comment by hyunjun19** [comment]
https://github.com/axisj-com/axisj/blob/master/lib/AXGrid.js#L6671 여기서 오류가 발생하는데 직접 디버깅이 불가능 하니 파악이 힘드네요.

`<script type="text/javascript" src=".../AXJ.min.js"></script>` 를 `<script type="text/javascript" src=".../AXJ.all.js"></script>`으로 바꾸고 저희가 접속할 수 있도록 URL을 열어 주시는게 제일 확실합니다.

**Comment by KimJM** [comment]
mergeCells에서 발생한거군요. 원인 파악이 된것같습니다 수정 조치하겠습니다.

**Comment by KimJM** [comment]
확인해본결과 mergeCells 이 적용 되어 있지 않는데 저기 부분이 호출 되는것이 이상합니다만..
혹시 화면에 다른 그리드가 존재하는지요? 현재 그리드에서 저 부분이 호출이 될수가 없는것같네요

**Comment by david80** [comment]
아! 그리드 2개 였을때 상세그리드 머지를 빼니까 잘 되네요;;

'''grid: {
            target: new AXGrid(),
            get: function () { return this.target; },
            bind: function () {
                this.target.setConfig({
                    targetID: "page-grid-box",
                    theme: "AXGrid",
                    fitToWidth: true,
                    mediaQuery: {
                        mx: { min: 0, max: 767 },
                        dx: { min: 767 }
                    },
                    colGroup: [
                        { key: "emp_seq", label: "선택", width: "40", align: "center", formatter: "radio" },
                        {
                            key: "rowidx", label: "번호", width: "40", align: "center", formatter: function () {
                                return (this.index + 1);
                            }
                        },
                        { key: "duty_nm", label: "직책", width: "60", align: "center", formatter: "dec" },
                        { key: "emp_nm", label: "성명", width: "50", align: "center", formatter: "dec" },
                        { key: "salary_sum", label: "급여합계", width: "80", align: "right", formatter: "money" },
                        { key: "deduct_sum", label: "공제합계", width: "80", align: "right", formatter: "money" },
                        {
                            key: "_amt_pay", label: "지급액", width: "80", align: "right", formatter: function () {

                                return (this.item.salary_sum.number() - this.item.deduct_sum.number()).money();
                            }

                        }

                    ],
                    body: {

                        oncheck: function () {

                            fnObj.item.open("gridView", this.item); //팝업으로 정직원 급여기준정보를 띄움
                            fnObj.dataLoad(this.item);              //상세화면 바인딩
                            fnObj.grid.get().setFocus(this.index);  //현재 라디오버튼을 선택한 곳으로 그리드 포커스 세팅
                        },
                        onclick: function () {
                            /*
                                this.c : 열
                                this.r : 행
                            */
                            if (this.c != 0) fnObj.dataLoad(this.item);
                        },
                        ondblclick: function () {

                        },
                        addClass: function () {

                        },
                        onchangeScroll: function () {

                        }
                    },
                    page: { paging: false, status: { formatter: null } }
                });
            },
            search: function (obj) {
                var pars = (obj || "");
                mask.open();
                fnObj.grid.get().setList({
                    ajaxUrl: pageUrl + "/SelectMasterList", ajaxPars: pars, onLoad: function () {
                        mask.close();
                    }
                });
            },
            reload: function () {
                this.target.reloadList();
            },
            setHeight: function () {
                var h = fnObj.getAvailHeight();

                var adjustHeight = $("#AXSearchTarget").outerHeight() - 41;

                $("#page-grid-box").css({ height: h - adjustHeight });
                fnObj.grid.get().resetHeight();
            }
        },
        item: {
            target: new AXModal(),
            get: function () { return this.target; },
            bind: function () {
                window.myModal = this.target;
                this.target.setConfig({
                    windowID: "myModalContainer",
                    mediaQuery: {
                        mx: { min: 0, max: 767 }, dx: { min: 767 }
                    },
                    displayLoading: true
                });
            },
            open: function (type, item) {
                var pars = {};
                if (type == "gridView") {
                    //그리드에서 팝업 띄울 경우
                    pars = { callBack: "fnObj.item.callBack", emp_seq: item.emp_seq };
                } else if (type == "regist") {
                    //신규등록일경우
                    pars = { callBack: "fnObj.item.callBack" };
                }


                //모달새창window.open과동일
                this.target.openNew({
                    url: "SalaryStdinfo_Pop.aspx",
                    pars: pars,
                    options: "width=1005,height=800,location=no,directories=no,resizable=yes,status=no,toolbar=no,menubar=no,scrollbars=yes",
                    closeByEscKey: true
                });
            },
            callBack: function () {
                //alert("부모로 callBack");
                var obj = fnObj.grid.get().getSelectedItem();
                if (obj != null) {
                    if (obj.item != null) fnObj.dataLoad(obj.item);
                }
                fnObj.grid.reload();
            }
        },

        dataLoad: function (item_obj) {

            var url = pageUrl + "/SelectMasterView"; //직원기본정보와 급여공제금액만 받아옴
            var pars = "item_Key=" + item_obj.emp_seq;
            new AXReq(url, {
                debug: false, pars: pars, onsucc: function (res) {
                    if (!res.error) {
                        var item = res.rs;
                        var frm = document["table-form"];

                        //금액항목 ,세자리 붙이기 적용
                        item.salary_sum = item.salary_sum.money();
                        item.deduct_sum = item.deduct_sum.money();

                        //자동 SetBind
                        $(frm).bindViewForm(item, "");
                        
                        fnObj.grid_dtl.search(item.emp_seq);  //급여 기준 상세 정보를 가져옴 

                    } else {
                        AXMsg.alert(res.msg.dec());
                    }
                }
            });
        },
        grid_dtl: {
            target: new AXGrid(),
            get: function () { return this.target; },
            bind: function () {
                this.target.setConfig({
                    targetID: "page-tool-grid-box",
                    theme: "AXGrid",
                    fitToWidth: true,
                    height: "auto",
                    mediaQuery: {
                        mx: { min: 0, max: 767 },
                        dx: { min: 767 }
                    },
                    //mergeCells: [0],
                    colGroup: [
                         { key: "item_num", label: "항목번호", display: false, width: "100", align: "right", formatter: "money" },
                        {
                            key: "sal_deduc_gb", label: "구분", width: "40", align: "center", formatter: function () {
                                if (this.item.sal_deduc_gb == "I")
                                    return "급여항목";
                                else
                                    return "공제항목";

                            }
                        },
                       { key: "sal_deduc_nm", label: "항목", width: "100", align: "center", formatter: "dec"  },
                       { key: "amount", label: "급여액", width: "100", align: "right", formatter: "money" }
                      ],

                    body: {

                        oncheck: function () {
                            //trace(this.item);
                        },
                        onclick: function () {
                            /*
                                this.c : 열
                                this.r : 행
                            */
                            //if (this.c != 0) fnObj.item.open("gridView", this.item);
                        },
                        ondblclick: function () {

                        },
                        addClass: function () {

                        },
                        onchangeScroll: function () {

                        }
                    },
                    page: { display: false, paging: false, status: { formatter: null } }
                });
            },'''

**Comment by david80** [comment]
그리드 2개였을때 머지를 넣으니 문제가 되는듯함..

**Comment by KimJM** [comment]
grid_dtl 데이터 가져오는 부분이 어디있나요?
`fnObj.grid_dtl.search(item.emp_seq); `와 에러가 날것 같기도하네요..
저도 확인해보겠습니다.

증상이 gird onclick 시 grid_dtl 에서 에러가 나는것으로 보아 데이터 관련 문제로 보이기도합니다

**Comment by david80** [comment]
데이터는 이상없는데요
 mediaQuery: {
                        mx: { min: 0, max: 767 },
                        dx: { min: 767 }
                    },
                    //mergeCells: [1],
                    colGroup: [
                         { key: "item_num", label: "항목번호", display: false, width: "100", align: "right", formatter: "money" },
                        {
                            key: "sal_deduc_gb", label: "구분", width: "40", align: "center", formatter: function () {
                                if (this.item.sal_deduc_gb == "I")
                                    return "급여항목";
                                else
                                    return "공제항목";

                            }
                        },
                       { key: "sal_deduc_nm", label: "항목", width: "100", align: "center", formatter: "dec"  },
                       { key: "amount", label: "급여액", width: "100", align: "right", formatter: "money" }
                      ],
디스플레이 false와 관련있는거 같아요. 이걸 빼니 정상적으로 되네요..
머지할때 이상이 발생..

**Comment by david80** [comment]
'''
mergeCells: [1],
 colGroup: [
 { key: "item_num", label: "항목번호", display: false, width: "100", align: "right", formatter: "money" },
 {
 key: "sal_deduc_gb", label: "구분", width: "40", align: "center", formatter: function () {
 if (this.item.sal_deduc_gb == "I")
 return "급여항목";
else
 return "공제항목";
 }
'''

이 구조인경우 에러가 나오는듯하네요.

**Comment by david80** [comment]
![localhost_20150326_131926](https://cloud.githubusercontent.com/assets/11273651/6840407/c9bbf0ba-d3ba-11e4-8432-4a8f530888a0.jpg)

요 데이터가 있는 상태에서
{ key: "item_num", label: "항목번호", display: false, width: "100", align: "right", formatter: "money" },

하면 에러가 발생 언더파인드..

**Comment by tom-axisj** [comment]
에러 없는지 확인 해주시고 이슈 닫아주세요.
