### ISSUE TITLE
FileListLoad 부분 질문을 다시 올립니다.

### ISSUE THREAD

**Issue by boxkie** [axisj-com/axisj#498]
var url = "<c:url value='/cop/bbs/fileListLoadAxisj.do?fileId=${result.atchFileId}&bbsId=${brdMstr.bbsId}' />";
				var pars = "dummy="+AXUtil.timekey();
				new AXReq(url, {pars:pars,
					onsucc:function(res){
					alert("시작");
					console.log(JSONtoString(res));
                    if(!res.error){
                    	alert("정상");
                        myUpload.setUploadedList(res);
                    }else{
                    	alert("오류");
                        alert(res.msg.dec());
                    }
				},
				onerr: function(res){
					alert("완전오류");
					console.log(JSONtoString(res));
				}
				}); 

오늘 하루 아무리 데이터를 다르게 던져도 오류가 나서 혹시나 싶어서 onerr 쪽 부분을 뿌려보았는데
alert("완전오류"); 이 작동 하는것을 발견했습니다.
이 부분에 대해서 어떤 부분을 살펴보면 좋을지 조언을 부탁드립니다.

**Comment by boxkie** [comment]
아.. 질문 삭제가 안되네요;;
해결했습니다.

public class AjaxXmlView extends AbstractView {
 	@Override
	protected void renderMergedOutputModel(Map model,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
 		response.setContentType("text/json");
		response.setHeader("Cache-Control", "no-cache");
		response.setCharacterEncoding("UTF-8");
 		PrintWriter writer = response.getWriter();
		writer.write((String) model.get("ajaxXml"));  
		writer.close();
	}
}


response.setContentType("text/json"); 이 부분이 text/xml 로 되어있었습니다.

**Comment by hyunjun19** [comment]
해결하셨다니 다행입니다. ^^
