### ISSUE TITLE
GridList 에서 setFocus 을 이용하여 포커싱 이동시 undefined이 뜹니다.

### ISSUE THREAD

**Issue by GitHubhyun** [axisj-com/axisj#500]
```
nextMemInfo: function(){
var memIndex = this.gridList.target.getSelectedItem().index;
var nextMemindex = (Number(memIndex)+1);
this.gridList.target.setFocus(nextMemindex);
var selectItem = this.gridList.target.getSelectedItem();
alert("selectItem.error==>"+selectItem.error);
if(selectItem.error == "noselected"){
alert("없습니다.");
}else{
fnEditObj.editForm.setData(selectItem.item.IN_MEM_SEQ, null);
}
}
```
![1](https://cloud.githubusercontent.com/assets/11675197/6862940/3516c6ec-d48c-11e4-9924-d4123a3683fc.PNG)
![2](https://cloud.githubusercontent.com/assets/11675197/6862941/351748a6-d48c-11e4-9502-b14670ec6eb4.PNG)

위의 코드로 코딩하여 이전글다음글 프로그램을 만드는중 다음글 버튼을 눌러 nextMemInfo를 호출하여 다음줄로 포커싱을 이동하는 동안 undefined 에러는 발생하는데 원인을 모르겠습니다;;
제일 마지막줄이나 처음줄에서 호출시 noselected여부로 포커싱이동을 막아볼려하였는데; 
어찌해야 하는지 감이 안잡혀서요.

**Comment by hyunjun19** [comment]
getSelectedItem 에서 반환되는 JSON 형식은 세 가지 입니다.

1. 여러 행이 선택된 경우 => `{ index: [ 0, 1, 2], item: [ {}, {}, {} ] }`
2. 단일 행이 선택된 경우 => `{ index: 0, item: {} }`
3. 선택된 행이 없는 경우 => `{ error: "noselected", description: "선택된 item이 없습니다." }`

지금 보기에는 1번이나 2번 경우인데 `error`을 찍어 보신거 같아요. JSON 전체 값을 확인해 보세요.
`trace(selectItem)` 요렇게 하시면 콘솔창에 JSON 값 전체를 확인하실 수 있습니다.
