### ISSUE TITLE
AXUpload5 질문 있습니다. 

### ISSUE THREAD

**Issue by boxkie** [axisj-com/axisj#501]
1. 업로드 같은경우 모든 업로드가 완료되었을때 발생하는 이벤트 onComplete 함수가 있습니다. 
    그렇다면 삭제가 모두 완료가 되었을때 실행되는 함수는 없나요?
    삭제가 모두 이루어 지면 '삭제가 완료되었습니다.' 라는 메시지를 띄우고 싶은데 
    onDelete 의 경우 한 파일당 한번씩 동작을 하네요.

2. file_type 제한의 경우 MIME_type 으로 적용한다고 적혀 있는데
    image/gif | image/jpeg | text/html |.....
    이런식으로 써내려 가면 되는것인가요?
    조금더 쉬운 방법은 없는지 궁금합니다.

**Comment by panic910** [comment]
AXUpload5.js 에서

removeUploadedList: function 의

```
newUploadedList = null;
아래에
if (this.config.onDeleteAll && this.uploadedList.length < 1)  this.config.onDeleteAll.call();
추가
```

그리고 upload config 설정할 때에
```
                onDeleteAll: function(){
                    alert('삭제가 완료되었습니다.');
                }
```

위 함수 추가 하시면 일단 해결 됩니다.

**Comment by tom-axisj** [comment]
:+1: 역시
js에서 관련함수를 추가 하도록 하겠습니다. 아니 했네요.

**Comment by boxkie** [comment]
감사합니다.
추가해서 사용하도록 하겠습니다.

MIME_type 의 경우 
substring 이나 split 으로 확장자 부분만 잘라서 
관리자에서 등록한 확장자 비교만 하면 간단할거 같은데
MIME_type 으로 사용하자니 다소 불편하네요
MIME_type 전체를 따로 테이블로 뽑아서 관리를 해야할까 어떻게 할까 고민됩니다.

오늘도 답변 감사합니다.

**Comment by boxkie** [comment]
감사합니다.
추가해서 사용하도록 하겠습니다.

MIME_type 의 경우 
substring 이나 split 으로 확장자 부분만 잘라서 
관리자에서 등록한 확장자 비교만 하면 간단할거 같은데
MIME_type 으로 사용하자니 다소 불편하네요
MIME_type 전체를 따로 테이블로 뽑아서 관리를 해야할까 어떻게 할까 고민됩니다.

오늘도 답변 감사합니다.

**Comment by tom-axisj** [comment]
MIME 타입 지정이 HTML5 file선택창 필터 표준입니다. 확장자로 할래야 할수 가 없지요.
