### ISSUE TITLE
AXInput  bind TwinDateTime 부분 날짜 value 관련 버그

### ISSUE THREAD

**Issue by utobiz** [axisj-com/axisj#503]
AXInput 
bind TwinDateTime
관련하여 버그인듯해서 올립니다.

다른 AXInput 의 경우 달력레이어에서 기존 입력된 날짜값을 가져와서 반영하지만
현재 샘플 페이지(http://dev.axisj.com/samples/AXInput/calendar.html)에서
bind TwinDateTime 예제의 경우 날짜를 입력한뒤 다시 열어보면,  기존 value를 못가져오고 현재 월로 갱신되어 보여집니다.

**Comment by tom-axisj** [comment]
저와 커미터들은 그런 현상이 없다고 합니다. 캐시가 아닐까요?

**Comment by utobiz** [comment]
다른 장소에서 테스트 해본 바, 캐시는 아닌거 같고요. 제가 다시 설명하려고 글을 적다가 다시 테스트 하는 과정에서 아래와 같은 현상들이 발견됩니다.

아래의 모두는 http://dev.axisj.com/samples/AXInput/calendar.html 페이지에서 TwinDateTime 에 대해서 한 테스트들입니다. TwinDate 등의 경우는 정상이고 TwinDateTime에서 이런 현상이 나타납니다.

테스트 방법은 우선 특정 날짜시간 범위를 캘린더 아이콘을 클릭해서 입력을 합니다. 그 다음에 다시 캘린더 아이콘을 눌렀을 때 나타나는 현상들입니다.  즉, default value 가 있는 경우 입니다.

날짜형식이 Datetime 형식이지만, 시간은 영향을 안받는듯 해서 날짜만 기술합니다.

1.[정상] 1/1 - 3/30 입력한후 다시 캘린더를 열면 정상입니다.

2. [비정상] 2/3 - 3/25 입력한후 다시 캘린더를 열면 기존값이 3/4 - 3/26으로 월과 일이 변경되어 버립니다. 그리고 다시 캘린더를 열면 열때마다 하루씩 날짜가 증가하네요.

3. [비정상] 1/1 - 2/25 입력한후 다시 캘린더를 열면 기존값이 1/2 - 3/26으로 월과 일이 변경되어 버립니다. 그리고 다시 캘런디를 열면 열때마다 하루씩 날짜가 증가합니다.

혹시 다른 분들은 이와 다른가요?

**Comment by tom-axisj** [comment]
이 문제는 새벽에만 발생합니다.
timeZone 이 +09:00인데. 9시간 당겨지면서 시간값이 - 로 되고 그럼 날짜가 이상 작동하게 되는데요...
해결은 봤는데. 1월 1일 일때 타임존이 조금 어렵네요.

```
var d = new Date(Date.UTC(aDate[0], parseFloat(aDate[1]) - 1, parseFloat(aDate[2]), parseFloat(hh), parseFloat(mi)));
if(parseFloat(aDate[1]) == 1 && parseFloat(aDate[2]) == 1 && parseFloat(hh) < (d.getTimezoneOffset()/60).abs()) {
	d.setUTCHours(0);
}else{
	d.setUTCHours(d.getUTCHours() + (d.getTimezoneOffset()/60));
}
return d;
```

에서 처럼 시간값이 1월 1일 이면서 시간이 타임존보다 작을 때 예외 처리를 해야 하는데.. 
여기서 부터는 생각좀 해봐야 겠습니다.

**Comment by tom-axisj** [comment]
테스트 해주세요. 1월 1일 일때 오전 9시 보다 전으로는 선택후 다시 날짜 선택창 띄우면 다시 9시 초기화 되는 현상이 있습니다. 현재로선 최선이네요. 예외처리를 한번 더 해야 하는데 쉽게 하는 방법을 고민중입니다.
