### ISSUE TITLE
Textarea 를 구현하려면 AXEditor를 활용해야 되는 건가요?

### ISSUE THREAD

**Issue by aaboo** [axisj-com/axisj#504]
그렇게 복잡하게 안해도 되는데 ㅠㅠ.

**Comment by hyunjun19** [comment]
`<textarea class="AXInput">내용</textarea>`  이렇게 말구요?
좀 더 정확하게 질문해 주세요.

**Comment by aaboo** [comment]
아. http://dev.axisj.com 에 샘플이 없어서 찾고 있던 중이었습니다.
그렇게 하는 방법도 있었군요 ㅡ,.ㅡa

**Comment by hyunjun19** [comment]
`<textarea class="AXTextarea">내용</textarea>` 이게 정답이네요.^^;;

**Comment by aaboo** [comment]
<textarea class="AXInput">내용</textarea> 
<textarea class="AXTextarea">내용</textarea> 
둘 다~ 잘 들어 맞아 떨어지기 그지 없습니다.

dev.axisj.com 에 샘플 넣어 주시면
앞으로 저 처럼 귀차니즘에 빠진 사람들이
찾아 헤메는 일은 없을 것 같아요 ㅎㅎ; 

바쁘시면 말고요
암튼 감사합니다~

**Comment by hyunjun19** [comment]
네 샘플에 추가하는게 좋을 것 같네요. ^^
