### ISSUE TITLE
fixedColSeq을 설정했을때 valign이 안먹히는 문제

### ISSUE THREAD

**Issue by beginnerkht** [axisj-com/axisj#506]
제목 그대로 fixedColSeq를 설정하였을때 valign:"middle" 속성이 적용이 안됩니다.

혹시 다른방법으로 접근을 해야하는건지 답변 부탁드리겠습니다.

**Comment by KimJM** [comment]
테스트 해본결과 정상적으로 되는것으로 보입니다만..
적용 부분 소스를 올려주시면 빠른 답변이 가능할것 같습니다.

**Comment by beginnerkht** [comment]
<script type="text/javascript">
		var pageID = "ajax";
		var myGrid = new AXGrid();
		var mySearch = new AXSearch();
		var myModal = new AXModal();

		var fnObj = {
		    pageStart: function(){
		        fnObj.grid.init();
				$("#edate").bindTwinDate({align:"right", valign:"bottom", separator:"-", startTargetID:"sdate", onChange:function(){
					//toast.push(Object.toJSON(this));
				}});
		    },
		    pageResize: function(){
		    },
		    grid: {
				init: function () {
						myGrid.setConfig({
						targetID: "AXGridTarget",
						theme: "AXGrid",
						fixedColSeq:3,
						colGroup: [
							{ key: "agency", label: "시행기관", width: "150", align: "center" },
							{ key: "farmname", label: "농가명", width: "100", align: "center" },
							{ key: "", label: "구분", width: "100", align: "center" },
							{ key: "regno", label: "개체식별번호", width: "150", align: "center", formatter: function(){
								var dt = this.item.regno.toUpperCase();
								if (dt == "GAP") dt = "<span style='color:red;'>"+dt+"</span>";
								return dt;
							} },
							{ key: "BM1824_1", label: "c1", width: "50", align: "center"},
							{ key: "BM1824_2", label: "c2", width: "50", align: "center"},
							{ key: "BM2113_1", label: "c1", width: "50", align: "center"},
							{ key: "BM2113_2", label: "c2", width: "50", align: "center"},
							{ key: "ETH10_1", label: "c1", width: "50", align: "center"},
							{ key: "ETH10_2", label: "c2", width: "50", align: "center"},
							{ key: "ETH225_1", label: "c1", width: "50", align: "center"},
							{ key: "ETH225_2", label: "c2", width: "50", align: "center"},
							{ key: "ETH3_1", label: "c1", width: "50", align: "center"},
							{ key: "ETH3_2", label: "c2", width: "50", align: "center"},
							{ key: "INRA23_1", label: "c1", width: "50", align: "center"},
							{ key: "INRA23_2", label: "c2", width: "50", align: "center"},
							{ key: "SPS115_1", label: "c1", width: "50", align: "center"},
							{ key: "SPS115_2", label: "c2", width: "50", align: "center"},
							{ key: "TGLA122_1", label: "c1", width: "50", align: "center"},
							{ key: "TGLA122_2", label: "c2", width: "50", align: "center"},
							{ key: "TGLA126_1", label: "c1", width: "50", align: "center"},
							{ key: "TGLA126_2", label: "c2", width: "50", align: "center"},
							{ key: "TGLA227_1", label: "c1", width: "50", align: "center"},
							{ key: "TGLA227_2", label: "c2", width: "50", align: "center"},
							{ key: "TGLA53_1", label: "c1", width: "50", align: "center"},
							{ key: "TGLA53_2", label: "c2", width: "50", align: "center"}
						],

						colHead : {
							rows: [
								[
									{colSeq:0, rowspan:3, valign:"middle"},
									{colSeq:1, rowspan:3, valign:"middle"},
									{colSeq:2, rowspan:3, valign:"middle"},
									{colSeq:3, rowspan:3, valign:"middle"},
									{colSeq:null, colspan:22, label:"유전자분석결과", valign:"middle", align:"center"},
								],
								[
									{colSeq:null, colspan:2, label:"BM1824", align:"center"},
									{colSeq:null, colspan:2, label:"BM2113", align:"center"},
									{colSeq:null, colspan:2, label:"ETH10", align:"center"},
									{colSeq:null, colspan:2, label:"ETH225", align:"center"},
									{colSeq:null, colspan:2, label:"ETH3", align:"center"},
									{colSeq:null, colspan:2, label:"INRA23", align:"center"},
									{colSeq:null, colspan:2, label:"SPS115", align:"center"},
									{colSeq:null, colspan:2, label:"TGLA122", align:"center"},
									{colSeq:null, colspan:2, label:"TGLA126", align:"center"},
									{colSeq:null, colspan:2, label:"TGLA227", align:"center"},
									{colSeq:null, colspan:2, label:"TGLA53", align:"center"}
								],
								[
									{colSeq:4},
									{colSeq:5},
									{colSeq:6},
									{colSeq:7},
									{colSeq:8},
									{colSeq:9},
									{colSeq:10},
									{colSeq:11},
									{colSeq:12},
									{colSeq:13},
									{colSeq:14},
									{colSeq:15},
									{colSeq:16},
									{colSeq:17},
									{colSeq:18},
									{colSeq:19},
									{colSeq:20},
									{colSeq:21},
									{colSeq:22},
									{colSeq:23},
									{colSeq:24},
									{colSeq:25}
								]
							]
						},

						body: {
							rows: [
								[
									{key:"agency", align:"center", width:"300"},
									{key:"farmname", align:"center", width:"300"},
									{colSeq:null, formatter:function(){
										return "개체";
									}, align:"center", addClass:""}, 
									{key:"regno", align:"center"},
									{ key: "BM1824_1", align: "center"},
									{ key: "BM1824_2", align: "center"},
									{ key: "BM2113_1", align: "center"},
									{ key: "BM2113_2", align: "center"},
									{ key: "ETH10_1", align: "center"},
									{ key: "ETH10_2", align: "center"},
									{ key: "ETH225_1", align: "center"},
									{ key: "ETH225_2", align: "center"},
									{ key: "ETH3_1", align: "center"},
									{ key: "ETH3_2", align: "center"},
									{ key: "INRA23_1", align: "center"},
									{ key: "INRA23_2", align: "center"},
									{ key: "SPS115_1", align: "center"},
									{ key: "SPS115_2", align: "center"},
									{ key: "TGLA122_1", align: "center"},
									{ key: "TGLA122_2", align: "center"},
									{ key: "TGLA126_1", align: "center"},
									{ key: "TGLA126_2", align: "center"},
									{ key: "TGLA227_1", align: "center"},
									{ key: "TGLA227_2", align: "center"},
									{ key: "TGLA53_1", align: "center"},
									{ key: "TGLA53_2", align: "center"}
								],
								[
									{key:"", align:"center"},
									{key:"", align:"center"},
									{colSeq:null, formatter:function(){
										return "어미";
									}, align:"center", addClass:""}, 
									{key:"mregno", align:"center"},
									{ key: "M_BM1824_1", align: "center"},
									{ key: "M_BM1824_2", align: "center"},
									{ key: "M_BM2113_1", align: "center"},
									{ key: "M_BM2113_2", align: "center"},
									{ key: "M_ETH10_1", align: "center"},
									{ key: "M_ETH10_2", align: "center"},
									{ key: "M_ETH225_1", align: "center"},
									{ key: "M_ETH225_2", align: "center"},
									{ key: "M_ETH3_1", align: "center"},
									{ key: "M_ETH3_2", align: "center"},
									{ key: "M_INRA23_1", align: "center"},
									{ key: "M_INRA23_2", align: "center"},
									{ key: "M_SPS115_1", align: "center"},
									{ key: "M_SPS115_2", align: "center"},
									{ key: "M_TGLA122_1", align: "center"},
									{ key: "M_TGLA122_2", align: "center"},
									{ key: "M_TGLA126_1", align: "center"},
									{ key: "M_TGLA126_2", align: "center"},
									{ key: "M_TGLA227_1", align: "center"},
									{ key: "M_TGLA227_2", align: "center"},
									{ key: "M_TGLA53_1", align: "center"},
									{ key: "M_TGLA53_2", align: "center"}
								],
								[
									{key:"", align:"center"},
									{key:"", align:"center"},
									{colSeq:null, formatter:function(){
										return "아비";
									}, align:"center", addClass:""}, 
									{key:"kpn", align:"center"},
									{ key: "F_BM1824_1", align: "center"},
									{ key: "F_BM1824_2", align: "center"},
									{ key: "F_BM2113_1", align: "center"},
									{ key: "F_BM2113_2", align: "center"},
									{ key: "F_ETH10_1", align: "center"},
									{ key: "F_ETH10_2", align: "center"},
									{ key: "F_ETH225_1", align: "center"},
									{ key: "F_ETH225_2", align: "center"},
									{ key: "F_ETH3_1", align: "center"},
									{ key: "F_ETH3_2", align: "center"},
									{ key: "F_INRA23_1", align: "center"},
									{ key: "F_INRA23_2", align: "center"},
									{ key: "F_SPS115_1", align: "center"},
									{ key: "F_SPS115_2", align: "center"},
									{ key: "F_TGLA122_1", align: "center"},
									{ key: "F_TGLA122_2", align: "center"},
									{ key: "F_TGLA126_1", align: "center"},
									{ key: "F_TGLA126_2", align: "center"},
									{ key: "F_TGLA227_1", align: "center"},
									{ key: "F_TGLA227_2", align: "center"},
									{ key: "F_TGLA53_1", align: "center"},
									{ key: "F_TGLA53_2", align: "center"}
								],
								[
									{key:"", align:"center"},
									{key:"", align:"center"},
									{colSeq:null, formatter:function(){
										return "최종결과";
									}, align:"center", addClass:""}, 
									{key:"result", align:"center"},
									{ key: "", align: "center"},
									{ key: "", align: "center"},
									{ key: "", align: "center"},
									{ key: "", align: "center"},
									{ key: "", align: "center"},
									{ key: "", align: "center"},
									{ key: "", align: "center"},
									{ key: "", align: "center"},
									{ key: "", align: "center"},
									{ key: "", align: "center"},
									{ key: "", align: "center"},
									{ key: "", align: "center"},
									{ key: "", align: "center"},
									{ key: "", align: "center"},
									{ key: "", align: "center"},
									{ key: "", align: "center"},
									{ key: "", align: "center"},
									{ key: "", align: "center"},
									{ key: "", align: "center"},
									{ key: "", align: "center"},
									{ key: "", align: "center"},
									{ key: "", align: "center"}
								]
							]
							/*
							onclick: function () {
								/*
								fnObj.setFormValue({ index: this.index, r: this.r, c: this.c, item: this.item, page: this.page }, "codeForm");
								//toast.push(Object.toJSON({index:this.index, r:this.r, c:this.c, item:this.item, page:this.page}));
									*/
									/*
								myModal.open({
									method:"POST", // 실 서버에서는 POST 를 권장합니다.
									url:"view.html",
									pars:{idx:this.item.idx,Ncode:"<?=$Ncode?>"},
									top:100,
									width:800
								});
							}
							*/
						},
						page: {
							paging: true,
							pageNo: 1,
							pageSize: 15,
							status: { formatter: null }
						}
					});
					
			        fnObj.grid.search();
			    },
			    
			    search: function () {
			    	var pars = "kpn="+$("#kpn").val();
					myGrid.setList({
                        ajaxUrl: "sub04_2_list.html", ajaxPars: ""+pars,
                        onLoad: function(){
                            //myGrid.click(1);
                            myGrid.setFocus(1);
                        }
                    }); //서버에서 받아오는 방식으로 구현할때.
					return;
			    }
			}
	    };
	jQuery(document.body).ready(function() {
        fnObj.pageStart();
    });
		</script>

이렇게 하였을때 fixedColSeq 설정부분만 valign속성이 적용되지 않았습니다

**Comment by KimJM** [comment]
![screen shot 2015-04-01 at 3 52 38 pm](https://cloud.githubusercontent.com/assets/5627281/6936053/e7497d00-d888-11e4-853f-5c3ff565dbf8.png)
올려주신 소스 그대로 적용 후 저는 valign가 이런식으로 나옵니다만, 
혹시 캐시 삭제 후 라이브러리를 최신으로 다시 받아보시겠습니까??

**Comment by beginnerkht** [comment]
바쁘신와중에 빠른 답변 정말 감사드립니다.

상기 문제는 말씀하신 최신라이브러리 교체로 해결하였습니다!!

**Comment by KimJM** [comment]
:thumbsup: ㅎㅎ 즐프입니다!!
