### ISSUE TITLE
panel 안에 axgrid, axinput, axselect를 넣엇을 경우 collapse시 화면 깨짐 현상

### ISSUE THREAD

**Issue by narsisya** [axisj-com/axisj#507]
panel body에 collapse 설정을 넣고 화면을 초기 로딩햇을 경우 input의 경우는 number로 바인드 햇을때
위/아래 화살표가 패널 상단에. select 객체가 패널 상단에 표시됩니다. 

브라우저의 크기를 변경하면 input의 위/아래 화살표는 전혀 이동 없구 select 객체는 원래위치를 찾아가긴 합니다만 해결 방법 없을까요?

그리고 panel body 선언시 처음부터 collapse를 선언하면 grid의 헤더가 사라집니다.
일단 body 선언 후에 로딩 후에 collapse 처리하면 그때는 그리드의 헤더가 정상적으로 보입니다.

**Comment by tom-axisj** [comment]
```
$(window).resize();
```
해주면 리사이즈 이벤트가 발생되었다고 인식이 되어서 자리가 맞아질 겁니다.

**Comment by narsisya** [comment]
감사합니다 ^^;
