### ISSUE TITLE
Safari 5.1.7 에서 dev.axisj.com 접속 시, 스크립트 오류

### ISSUE THREAD

**Issue by aaboo** [axisj-com/axisj#508]
수고가 많으십니다~

제 노트북/PC(window7)과 아이폰6(iOS) 환경에서 safari 브라우저로 접속을 하여 보았더랬습니다.

![untitled-2](https://cloud.githubusercontent.com/assets/3850967/6955611/fce30392-d91a-11e4-8b31-eadeb4f3a686.jpg)

그러나... 
![untitled-1](https://cloud.githubusercontent.com/assets/3850967/6955612/ff56e8be-d91a-11e4-9c4f-66ce8203fc01.jpg)

그래서, axj.min.js 로 첨부된 아이들이 사파리에서 정상작동하지 않는 것 같습니다.

safari 를 뭘 손봐줘야 하나요?

**Comment by hyunjun19** [comment]
사파리 잘못이 아닙니다.
지금 올라가 있는 소스에 문제가 있네요.
바로 조치하겠습니다.

**Comment by groovedk** [comment]
네 바로 조치해 주세요 :100:

**Comment by aaboo** [comment]
지금은 잘 되네요. dev 브렌치에 있는 axj.min.js 파일을 쓰면 되는 거겠죠?
근데 그 파일하나만 다운받는 방법을 혹시 아시는 분 있으면 멘트 달아주시길...

**Comment by hyunjun19** [comment]
https://github.com/axisj-com/axisj/blob/master/dist/AXJ.min.js 여기에서 `Raw`를 클릭하세요.

![image](https://cloud.githubusercontent.com/assets/421863/6957324/72d2c2f4-d934-11e4-8ce9-fb4de4ec7b9a.png)

**Comment by aaboo** [comment]
와 감사합니다. ㅠㅠ
그런 방법이 있었군요
