### ISSUE TITLE
그리드 체크박스 버그입니다.

### ISSUE THREAD

**Issue by david80** [axisj-com/axisj#512]
![2](https://cloud.githubusercontent.com/assets/11273651/6961095/3073de5a-d963-11e4-9c3b-e08f46ddc52a.png)

그리드에서 비활성화된 체크박스가 전체체크박스를 눌렀을경우 안되어야 되는데 

그리드에서 비활성화된 체크박스가 있는 상태에서 아래로 스크롤을 비활성화된 체크박스가 안보일때 까지 스크롤을 내리거나 올린다음 전체체크를 하고나서 다시 스크롤을 내리거나 올리면 비활성화된 체크박스가 체크가 되어져 있습니다. 반대로 체크박스를 풀때도 마찬가지로 풀려져 있습니다.

**Comment by tom-axisj** [comment]
disabled될 체크박스의 __checked 속성부여를 안하도록 수정하였습니다.
dataSync 와 관련성은 없을 것 같지만 테스트 해봐야 알겠네요.

**Comment by david80** [comment]
테스트 해보니 잘 되네요~ dataSync 와는 상관없는듯해요
