### ISSUE TITLE
bind Switch 사용상 문의

### ISSUE THREAD

**Issue by wann2** [axisj-com/axisj#514]
< script src="/bower/axisj/dist/AXJ.min.js" > < / script >
< script src="/bower/axisj/libpro/AXInputPro.js" > < / script >
...
< input type="text" id="flagHide" value="123456" style="width:80px;height:25px;border:0px none;" >
< script
$("#flagHide").bindSwitch({on:"차단하기", off:"차단취소", onChange:function() {
    console.log(this.value);
}});
< / script >

1) 위와같이 사용하면 아래처럼 동그라미안에 이상한 글자가 찍힙니다. 깨끗하게 나오게 하려면 어떻게 해야 하나요?

![-2](https://cloud.githubusercontent.com/assets/8732515/6977992/47e968e2-da04-11e4-9681-8e9cbfcd5fa0.gif)

2) 그리고 onchange 이벤트에서 input의 value인 '123456' 값을 가져오려면 어떻게 해야되나요?

**Comment by tom-axisj** [comment]
1) 저 파란 글씨가 비치는 것은 css문제 인데요. 이 문제는 실제 페이지를 보지 않으면 원인을 찾기 어렵습니다.
콘솔에서 스위치 핸들의 css정보를 알려주세요.

![2015-04-03 3 22 33](https://cloud.githubusercontent.com/assets/5884902/6978845/472bf5e4-da15-11e4-89dc-1cc9ccb5a437.png)

2) onchange에서 스위치 적용전 value는 가져올 수 없습니다. ui가 실행되면서 기존값과 on, off값을 비교해서 처리 하기 때문입니다.

**Comment by wann2** [comment]
프로그램 구조상 onchange에서 스위치 적용전 value값을 넘기지 못하는 부분과
onchange에 따라 DB에 저장하고, 나중에 DB에서 값을 불러와 setInputValue를 이용하여 bind switch default값을 변경시키려고 했는데 F5(refresh)할 때마다 onchange가 자동 실행되는 바람에
결국은 bind switch 대신 2 종류의 button을 사용하는 프로그램으로 바꿨습니다.
조언을 해주셔서 감사합니다.
