### ISSUE TITLE
AXGrid 에서 radio box 문의 드립니다.

### ISSUE THREAD

**Issue by doyeonK** [axisj-com/axisj#522]
http://dev.axisj.com/samples/AXGrid/inline-edit.html 
의 샘플 화면에는 radio 가 row 단위로 사용 할수 있게끔 되어 있는데요...

![radio](https://cloud.githubusercontent.com/assets/11867881/7063335/c9527af0-dee0-11e4-9e5f-12a4142d8716.png)

위의 그림과 같이 가로칼럼으로 radio 박스로 구현할려고 하려고 하는데 어떻게 해야 할까요?

**Comment by tom-axisj** [comment]
현재로선 어렵겠습니다.
