### ISSUE TITLE
ajax 기능 문의 (remote sort, remote paging)

### ISSUE THREAD

**Issue by ddangggoma** [axisj-com/axisj#524]
ajax 관련 기능에 관하여 문의 드립니다.
remote sort와 remote paging시에 이벤트를 감지하여 별도의 서버 요청을 통해 가져온 데이터를 바인드 하고자 합니다. (axisj의 ajaxUrl옵션 을 통한 서버 요청 작업이 여의치 않는 상황)
이를테면 아래와 같이 onchange에서 별도 서버 요청을 통해 가져온 data를 bind 하는 식으로 가능할까요???
```
page:{
    paging:true,
    pageNo:1,
    pageSize:100,
    onchange: function(pageNo){
        myGrid.listLoadingDisplay();
        // 블라블라 작업 처리....
        // ajax와 같은 비동기 효과를 주기 위해 setTimeout으로 대체
        // 서버에서 가져온 데이터 처리...
        setTimeout(function(){
            myGrid.setList([ {no:14, title:"AXGrid 세번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:129500, amount:1},
                {no:15, title:"AXGrid 두번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:12300, amount:7},
                {no:16, title:"AXGrid 세번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:12000, amount:5},
                {no:17, title:"AXGrid 세번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:13000, amount:4},
                {no:18, title:"AXGrid 세번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:3000, amount:3},
                {no:19, title:"AXGrid 세번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:123000, amount:2},
                {no:20, title:"AXGrid 세번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:129500, amount:1}]);
        }, 1000);
    }
}
```

**Comment by hyunjun19** [comment]
질문이... `setList` 메서드에서 ajaxUrl을 설정한 상태에서 페이징 이벤트가 일어나는 경우만 별도의 데이터로 처리하고 싶으신 건가요?

가능하시면 스크립트 소스 전체를 올려주세요. 질문의 의도를 정확히 파악하기가 힘드네요.

**Comment by ddangggoma** [comment]
죄송합니다. 특정 코드를 가지고 있진 않습니다. 현재 제가 구현하고자 하는 내용이 구현 가능한지 검토를 하고 있는 도중이라 sample 코드를 조금씩 수정하여 테스트 하고 있습니다.

현재 제가 하고 싶은 내용은...
page가 교체 되었을 경우나 정렬이 변경되었을 경우 서버에서 데이터를 다시 가져오는 내용에 대하여 제가 작업을 처리하고자 합니다.
page가 바뀌었을 경우 콜백 함수가 호출 되어 제가 바뀐 값을 통해 작업을 처리하고 ajax를 통해 data를 받아와 테이블의 데이터를 바꾸고자 합니다.
현재에는 onchange 이벤트도 콜백이지만 이를 통해 데이터를 바꿀수가 없어 보였는데 맞나요? 그리고 정렬이 변경 되었을 경우에는 별도 콜백 함수를 찾을 수 없엇습니다.

**Comment by hyunjun19** [comment]
보여지는 데이터를 바꾸고자 하신다면 formatter를 사용하세요.

```js
colGroup : [
	{key:"no", label:"번호", width:"50", align:"right"},
	...
	{key:"cost", label:"금액", width:"100", align:"right", formatter:function(){
		return (this.item.price.number() * this.item.amount.number()).money();
	}},
	{key:"desc", label:"비고", width:"200"}
];
```
http://dev.axisj.com/samples/AXGrid/index.html

**Comment by ddangggoma** [comment]
감사합니다. 하지만 제가 의도한대로 하자면 foramtter로는 무리가 있습니다.
ajax 요청을 통해 값을 가져온 값을 가지고 특정 내용을 만들어야 합니다.
그리고 ajax 또한 특정 작업을 위해 함수를 랩핑하여 사용하고 있습니다. 그래서 page가 일어났을경우 특정 콜백 함수가 호출된다면 그 함수내에서 ajax 요청을 하고 가져온 데이터를 가공하여 출력하고자 합니다. 하지만 onchange 함수는 그러한 방법으로 구현이 가능한지.. 그리고 정렬시에도 이러한 콜백 함수가 존재하는지 문의 드립니다.

**Comment by hyunjun19** [comment]
현재 그런 기능은 없습니다.

꼭 구현하셔야 한다면 소스를 참고하셔서 아래 메서드들을 overwrite 해서 사용하셔야 할 것 같습니다.

http://jdoc.axisj.com/AXGrid.html#ajaxGetList
http://jdoc.axisj.com/AXGrid.html#sortList

차선책으로는 setList 메서드에 ajaxUrl을 설정하지 않고 직접 ajax로 데이터를 가져와서 ` myGrid.setList({Array});` 방식으로 사용하실 수도 있습니다. 다만 이 방법은 페이징 사용이 불가능합니다.
