### ISSUE TITLE
AXupload5 질문있습니다.

### ISSUE THREAD

**Issue by khj8506** [axisj-com/axisj#525]
안녕하세요 axupload5를 사용해서 asp업로드로 잘 사용하고 있는데요..

제가 초보인데요...

안드로이드 4.4.2 버전 webview에서 filechoose가 되지 않는 이슈때문에 http방식으로 upload를 따로하고

자바스크립트로 setuploadedList를 불러 큐에 썸네일도 보여줬습니다.

하지만 1개일때는 잘 삭제가 되지만 1개 이상일때에는 마지막에 업로드한 파일만 삭제가 됩니다.

선택 삭제도 안되고요...큐에 있는 x버튼도 안눌립니다.

왜 그런지 알수 있을까요??

**Comment by tom-axisj** [comment]
이건 안드로이드 4.4.2에서 체크를 해봐야 가능한데요. 지금 사용하시는 webview도 제가 확인이 안되는 상황이구요.
크롬브라우저에 폰을 연결해서 디버깅을 해보셔야 할 것 같습니다.
도움이 못되어 죄송합니다.
