### ISSUE TITLE
그리드 키 이벤트 버그

### ISSUE THREAD

**Issue by david80** [axisj-com/axisj#529]
![localhost_20150413_144749](https://cloud.githubusercontent.com/assets/11273651/7110435/279ef3c8-e1ec-11e4-9452-4d52b7a2f26d.jpg)

입력박스에 커서가 가있는데 화살표 키를 누르면 그리드에 있는 커서가 움직입니다.
오른쪽에 입력박스를 클릭한다음 커서를 움직일려고 했더니 그리드에 있는 커서가 움직입니다.

**Comment by tom-axisj** [comment]
패치되었습니다.
