### ISSUE TITLE
grid 데이터 질문드립니다.

### ISSUE THREAD

**Issue by solarware-lee** [axisj-com/axisj#530]
ajax를 통해서 ibatis에서 쿼리를 조회해서 그걸 grid에서 뿌려주는 방식으로
개발을 하고있는데

혹시 쿼리결과를 xml로 저장하여 그 xml을 그리드에서 읽어오는 게 가능할까요?

**Comment by hyunjun19** [comment]
액시스제이는 JSON 형식만 지원하고 있습니다.

**Comment by tom-axisj** [comment]
https://github.com/buglabs/node-xml2json 이런식으로 오픈소스들이 있습니다.

키워드 xml to json 데이터 받으신 후에 json으로 컨버트 하시고 사용하시면 되겠습니다.
저희가 xml를 지원한다고 해도 결론적으로 같은 작업을 수행하도록 내부에 패킹을 하는 것이니 성능이 같다고 보시면 되겠습니다.

**Comment by solarware-lee** [comment]
@tom-axisj @hyunjun19 두분들 답변 감사드립니다. 바쁘신데 죄송합니다. 이전에 질문드렸던 그리드 rowspan쪽 답변은 언제쯤 알수있을까요?
