### ISSUE TITLE
dialog onclose 이벤트가 있나요?

### ISSUE THREAD

**Issue by davidwin3** [axisj-com/axisj#532]
dialog push로 띄웠을때 esc키로 다이얼로그를 닫았을때 이벤트가 발생하는지
궁금합니다. 

너무 잘쓰고 있습니다. 감사합니다.

**Comment by tom-axisj** [comment]
```
dialog.push({
body:'<b>Warning</b> Application Call dialog push', 
type:'Warning', 
onclose:function(){alert('close');}
});
```
처럼 처리 할 수 있도록 패치 하였습니다.

**Comment by davidwin3** [comment]
빠른 패치 정말 감시드려요~
2015년 4월 14일 (화) 오전 10:53, Thomas <notifications@github.com>님이 작성:
