### ISSUE TITLE
grid를 ajaxUrl 로 로딩할 때, empty of list 잠깐 나타나심

### ISSUE THREAD

**Issue by aaboo** [axisj-com/axisj#533]
```
var AXGridComp = new AXGrid();
AXGridComp.setList({
	ajaxUrl:"/admin/comp/read"
	,method:"post"
});
```
위와 같이 grid에 리스트를 JSON으로 가져오고자 할 경우, 
렌더링이 되기 전에 잠깐 "empty of list" 가 나타났다가, 정상적으로 리스트가 렌더링 됩니다.

AXConfig.AXGrid.emptyListMSG = "empty of list";
요것을 바꿀 수도 없는 노릇이고, 

아예 안나오게 하거나, "Loading..." 이런 것으로 대체하거나 하는 방법이 있을 것 같은데요.
과음으로... 머리가 안돌아 갑니다.

**Comment by hyunjun19** [comment]
제가 크롬에서 테스트 해본 결과는 아래와 같이 정상적으로 로딩 표시가 됩니다.
테스트 해보신 브라우저 환경이 어떻게 되나요?

![image](https://cloud.githubusercontent.com/assets/421863/7172416/a67e6650-e422-11e4-934e-9185127a72a0.png)

**Comment by aaboo** [comment]
위의 사이트를 로컬에 맞추어 돌려보니, 
로딩이미지가 빙글빙글 잘도 돌아갑니다.
따라서, 저의 경우는 브라우저 문제로 보이진 않구요. 

다만, 제가 Single Page Application 방식으로 개발을 하는 관계로, 
템플릿을 ajax로 불러와서 뿌려주거든요.
그래서 그런것 같습니다.
 
그래서 아래처럼 꼼수를 부려 보았어요.
```
setTimeout(function(){
	fnObj.pageStart();
}, 500);
```

이젠 잘 돌아갑니다. ^^
