### ISSUE TITLE
[ IE ] AXSearch inputText에서 엔터 입력시 IE에서는 onChange 이벤트가 발생하지 않습니다.

### ISSUE THREAD

**Issue by hyunjun19** [axisj-com/axisj#534]
AXSearch inputText에서 엔터 입력시 IE에서는 onChange 이벤트가 발생하지 않습니다.

크롬이나 파폭은 onChange 이벤트가 정상적으로 발생함.
IE만 onChange에 대해서 다르게 해석하는 듯...

IE에서 예외 처리 추가 예정...

**Comment by hyunjun19** [comment]
분명히 IE8에서 해당 문제가 발생하는걸 확인했는데 집에서 테스트한 환경은 문제가 없음.
환경을 좀 더 상세히 체크하면서 계속 테스트해야겠음... : (

![image](https://cloud.githubusercontent.com/assets/421863/7211945/6d791e3e-e59b-11e4-9598-0e90ae924a5a.png)

**Comment by hyunjun19** [comment]
IE8 버전에 따라서 매우 골치아픈 현상이 발생하고 있음
로딩도 되고 돔 랜더링도 된거 같은데 안보임... : (

![image](https://cloud.githubusercontent.com/assets/421863/7221938/57adfbc2-e73c-11e4-9492-75386b47f17b.png)

**Comment by hyunjun19** [comment]
개발자 도구에서 문서모드를 `쿼크 모드`로 변경했다가 다시 `Internet Explorer 8 표준(8)(페이지 기존)`으로 선택했더니 정상적으로 보이게 되었음.
사이트 내용이 안보이는 현상도 더 이상 나타나지 않음...

원인도 모르겠고...안보이는 증상은 일단 GG

![image](https://cloud.githubusercontent.com/assets/421863/7222022/7c02255a-e73e-11e4-9728-4554efb7ea88.png)

**Comment by hyunjun19** [comment]
재현이 어렵고 마이너한 문제이기 때문에 일단 이슈 종료

**Comment by groovedk** [comment]
:sweat_smile:
