### ISSUE TITLE
setList() 질문드립니다.

### ISSUE THREAD

**Issue by ryoueunsun** [axisj-com/axisj#537]
한동안 업뎃 안하고 있다가 오랫만에 업뎃했더니...
기존에 setList()방식과 달라진거 같아서 문의 드립니다.

현재까지 나온 최종버젼으로 업데이트 해서 사용하려면
setList()방식을 바꿔야 되는것인지요?

현재 사용하고 있는 소스 같이 올려봅니다.

	    var fnObj = {
		    pageStart: function(){
		        fnObj.searchInit();
		        fnObj.grid.init();
		    },
		    pageResize: function(){

		    },
		    searchInit: function(){
		    	mySearch.setConfig({
			    	targetID:"AXSearchTarget",
					theme : "AXSearch",
					rows:[
						{display:true, addClass:"", style:"", list:[
							{label:"검색어", labelWidth:"70", type:"selectBox", width:"100", key:"gubn", addClass:"", valueBoxStyle:"", value:"",
								options:[{optionValue:"OffName", optionText:"회사명"}, {optionValue:"Email", optionText:"이메일주소"}],
								AXBind:{
									type:"select", config:{
										onChange:function(){
										//아래 2개의 값을 사용 하실 수 있습니다.
										//dialog.push(Object.toJSON(this));
										//dialog.push(changedValue);			
										}
									}
								}
							},
							
							{label:"", labelWidth:"100", type:"inputText", width:"100", key:"SearchVal", addClass:"", valueBoxStyle:"", value:"",
								onChange: function(changedValue){
									//아래 2개의 값을 사용 하실 수 있습니다.
									//dialog.push(Object.toJSON(this));
									//dialog.push(changedValue);
								}
							},
							{label:"", labelWidth:"", type:"button", width:"80", key:"button", addClass:"", valueBoxStyle:"padding-left:0px;padding-right:5px;", value:"검색하기",
								onclick: function(){
									//AXUtil.alert(this);
									fnObj.grid.search();
									axdom("#" + mySearch.getItemId("button2")).attr("style", "visibility:visible;");
								}
							},

							{label:"", labelWidth:"", type:"button", width:"80", key:"button2", addClass:" Blue", valueBoxStyle:"padding-left:0px;padding-right:5px;visibility:hidden;", value:"전체목록",
								onclick: function(){
									var url = "customer_company_dam_list.asp";  
									jv(location).attr('href',url);
								}
							}
						]}
					]
				});
		    },
		    
		    grid: {
				init: function () {
			        myGrid.setConfig({
			            targetID: "AXGridTarget",
			            theme: "AXGrid",
						mediaQuery: {mx:{min:0, max:600}, dx:{min:600}},
						//viewMode: "grid", // ["grid","icon","mobile"]
						// 브라우저 사이즈에 따른 changeGridView 설정
						colGroup: [				            
			                {key:"no", label:"번호", width:"60", align:"center", formatter:"checkbox"},
							{key:"OffName", label:"고객사이름", width:"200"},
							{key:"Email", label:"고객EmailID", width:"200"},
							{key:"Del", label:"사용여부", width:"110", align:"center"},
							{key:"regDate", label:"등록일", width:"110", align:"center"}
			            ],
						body: {
			                onclick: function () {

								myModal.open({
									method:"post", // 실 서버에서는 POST 를 권장합니다.
									url:"damdang_pop.asp",
									pars:{idx:this.item.no},
									top:100,
									width:500
								});
								//alert(this.item.OffID);
								//window.location.href="customer_company_write.asp?OffID="+this.item.OffID
								//var url = "customer_company_write.asp?u_idx="+this.item.no;  
								//jv(location).attr('href',url);
			                }
			            },
			            page: {
			                paging: true,
			                pageNo: 1,
			                pageSize: 100,
			                status: { formatter: null }
			            }
			        });
	
			        fnObj.grid.search();
			    },
				
			    search: function () {
			    	var pars = mySearch.getParam();
					
					myGrid.setList({
                        ajaxUrl: "loadGridMem.asp", ajaxPars: "m=list&t=dam&"+pars,
                        onLoad: function(){
                            //myGrid.click(1);
                            //myGrid.setFocus(1);
                        }
                    }); //서버에서 받아오는 방식으로 구현할때.
					
					return false;
										
			    },
				
				remove: function(){
					var checkedList = myGrid.getCheckedList(0);
					if(checkedList.length == 0){
						alert("선택된 목록이 없습니다. 삭제하시려는 목록을 체크하세요");	
						return;
					}
					if(!confirm("정말 삭제 하시겠습니까?")) return;
					
					mask.open();
					var url = "삭제프로세스 URL";
					var pas = [];
					$.each(checkedList, function(){
						pas.push("idx="+this.idx);
					});
					var pars = pas.join("&") + "&method=D"
					new AXReq(url, {debug:false, pars:pars, onsucc:function(res){
							if(res.result == AXUtil.ajaxOkCode){
								toast.push("삭제 되었습니다.");
								fnObj.grid.search();
							}else{
								AXUtil.alert(res);
							}
							mask.close();
						},
						onerr:null
					});	
				}
			}

	    };

**Comment by KimJM** [comment]
setList 방식에 대해서는 변경 사항이 없는 것으로 알고 있습니다. 
어떤 문제가 발생하시나요?
http://jdoc.axisj.com/AXGrid.html#setList

**Comment by ryoueunsun** [comment]
검색버튼을 누르지 않아도 setlist가 바인딩되게끔 되어있었는데
현재는 검색 버튼을 눌러야지만 grid에 setlist가 바인딩되고 있습니다.

fnObj.grid.search(); 이 부분이 무시되는듯 보여서요.
그래서
 pageStart: function(){
            fnObj.searchInit();
            fnObj.grid.init();
            fnObj.grid.search();  <--
        },

이렇게 수정하여도 이 부분이 호출되지 않아보입니다.

**Comment by hyunjun19** [comment]
해당 문제는 다른 부분의 문제로 보여집니다.
혹시 콘솔에 오류나 다른 메시지가 발생하지 않나요?

**Comment by ryoueunsun** [comment]
아... $ 재선언해서 사용하고 있었는데 그 부분에서 충돌나서 그랬던것 같습니다.
현재 무리 없이 잘 나오네요.
바보 같은 ㅠㅠ
항상 콘솔창 잘 살펴보아야겠습니다.

빠른 답변 감사합니다~
