### ISSUE TITLE
div 팝업에서 뒤에 있는 그리드 커서 키이벤트에 의해 같이 되는 버그

### ISSUE THREAD

**Issue by david80** [axisj-com/axisj#538]
selectbox 을 키로 위아래 조절하면 뒤에 가려져있는 그리드에 있는 키이벤트가 움직입니다.

![3](https://cloud.githubusercontent.com/assets/11273651/7194687/7d71e09e-e4ee-11e4-89e4-96ca2b4c6583.png)
콤보박스에 있는 노란색 반전색깔 되어있는 부분을 화살표키로 위아래 움직이면 뒤에 있는 그리드의 노란색 행도 같이 움직입니다.

그리고 opendiv로 열었는데도 뒤에 있는 그리드 행이 키이벤트에 의해 움직이네요

**Comment by tom-axisj** [comment]
패치 되었습니다.

**Comment by david80** [comment]
'''javascript

<div style="display:none">    
    <div id="modalContent" style="padding:20px 5px;">     
        <div class="ax-popup">
            <div class="ax-unit center" style="padding:5px;text-align:center">
				<h1>원물재고이동</h1>
            </div>                            
            <form name="divWriteForm" id="divWriteForm" method="post" onsubmit="return false;" >
            <input type="hidden" name="act_tp_wr" id="act_tp_wr" value="C" />
            <input type="hidden" name="idx_wr" id="idx_wr" value="" />
            <div class="ax-rwd-table">
                <div class="item-group" style="">
				    <div class="item">
					    <div class="item-lable">
						    <span class="th" style="min-width:100px;">번호</span>
						    <span class="td inputText" style="" title="">
                                 <input type="text" name="no" id="no" class="AXInput" tabindex="1" readonly="true" />
						    </span>
					    </div>
				    </div>
                    <div class="item-clear"></div>
                    <div class="item">
					    <div class="item-lable">
						    <span class="th" style="min-width:100px;">수매번호</span>
						    <span class="td inputText" style="" title="">
                                 <input type="text" name="po_no" id="po_no" class="AXInput" tabindex="2" readonly="true" />
						    </span>
					    </div>
				    </div>
				    <div class="item-clear"></div>
                    <div class="group-clear"></div>
	            </div>
                <div class="item-group" style="">
				    <div class="item">
					    <div class="item-lable">
						    <span class="th" style="min-width:100px;">거래처명</span>
						    <span class="td inputText" style="" title="">
                                 <input type="text" name="cust_nm" id="cust_nm" class="AXInput" tabindex="3" readonly="true" />
						    </span>
					    </div>
				    </div>
                    <div class="item-clear"></div>
                    <div class="item">
					    <div class="item-lable">
						    <span class="th" style="min-width:100px;">상품</span>
						    <span class="td inputText" style="" title="">
                                <input type="text" name="goods_nm" id="goods_nm" class="AXInput" tabindex="4" readonly="true" />
						    </span>
					    </div>
				    </div>
				    <div class="item-clear"></div>
                    <div class="group-clear"></div>
	            </div>
                <div class="item-group" style="">
				    <div class="item">
					    <div class="item-lable">
						    <span class="th" style="min-width:100px;">크기</span>
						    <span class="td inputText" style="" title="">
                                <input type="text" name="size_nm" id="size_nm" class="AXInput W100" tabindex="5" readonly="true" />
						    </span>
					    </div>
				    </div>
                    <div class="item-clear"></div>
                    <div class="item">
					    <div class="item-lable">
						    <span class="th" style="min-width:100px;">품질</span>
						    <span class="td inputText" style="" title="">
                                <input type="text" name="grade_nm" id="grade_nm" class="AXInput W100" tabindex="6" readonly="true" />
						    </span>
					    </div>
				    </div>
                    <div class="item-clear"></div>
                    <div class="item">
					    <div class="item-lable">
						    <span class="th" style="min-width:100px;">혼합율</span>
						    <span class="td inputText" style="" title="">
                                <input type="text" name="selection_nm" id="selection_nm" class="AXInput W100" tabindex="7" readonly="true" />
						    </span>
					    </div>
				    </div>
                    <div class="item-clear"></div>
                    <div class="group-clear"></div>
	            </div>
                <div class="item-group" style="">
                    <div class="item">
					    <div class="item-lable">
						    <span class="th" style="min-width:100px;">저장고</span>
						    <span class="td inputText" style="" title="">
                                <input type="text" name="storage_nm" id="storage_nm" class="AXInput" tabindex="8" readonly="true" />
                                <input type="text" name="st_rowcol" id="st_rowcol" class="AXInput W100" tabindex="9" readonly="true" />
						    </span>
					    </div>
				    </div>
                    <div class="item-clear"></div>
                    <div class="group-clear"></div>
	            </div>
                <div class="item-group" style="">
				    <div class="item">
					    <div class="item-lable">
						    <span class="th" style="min-width:100px;">재고수량</span>
						    <span class="td inputText" style="" title="">
                                <input type="text" name="stock_qty" id="stock_qty" class="AXInput W100" tabindex="10" readonly="true" />
						    </span>
					    </div>
				    </div>
				    <div class="item-clear"></div>
                    <div class="item secondItem">
					    <div class="item-lable">
						    <span class="th" style="min-width:100px;">재고중량</span>
						    <span class="td inputText" style="" title="">
                                <input type="text" name="stock_wgt" id="stock_wgt" class="AXInput W100" tabindex="11" readonly="true" />
						    </span>
					    </div>
				    </div>
                    <div class="item-clear"></div>
                    <div class="item">
					    <div class="item-lable">
						    <span class="th" style="min-width:100px;">변경수량</span>
						    <span class="td inputText" style="" title="">
                                <input type="text" name="stock_qty_real" id="stock_qty_real" class="AXInput W100" tabindex="12" readonly="true" />
						    </span>
					    </div>
				    </div>
				    <div class="item-clear"></div>
                    <div class="item secondItem">
					    <div class="item-lable">
						    <span class="th" style="min-width:100px;">변경중량</span>
						    <span class="td inputText" style="" title="">
                                <input type="text" name="stock_wgt_real" id="stock_wgt_real" class="AXInput W100" tabindex="13" readonly="true" />
						    </span>
					    </div>
				    </div>
                    <div class="item-clear"></div>
                    <div class="group-clear"></div>
	            </div>
            </div>
            <hr />
            <div class="ax-rwd-table">
                 <div class="item-group" style="">
				    <div class="item">
					    <div class="item-lable">
						    <span class="th" style="min-width:100px;">이동수량</span>
						    <span class="td inputText" style="border-style:dashed; border-width:1px; border-color:red" title="">
                                <input type="text" name="stock_qty_adj" id="stock_qty_adj" title="이동수량" placeholder="이동수량" class="AXInput W100" tabindex="14" onclick="this.select();" />
						    </span>
					    </div>
				    </div>
				    <div class="item-clear"></div>
                    <div class="item">
					    <div class="item-lable">
						    <span class="th" style="min-width:100px;">이동중량</span>
						    <span class="td inputText" style="" title="">
                                <input type="text" name="stock_wgt_adj" id="stock_wgt_adj" title="이동중량" placeholder="이동중량" class="AXInput W100" tabindex="15" readonly="true" />
						    </span>
					    </div>
				    </div>
				    <div class="item-clear"></div>
                    <div class="item">
					    <div class="item-lable">
						    <span class="th" style="min-width:100px;">이동저장고</span>
						    <span class="td inputText" style="border-style:dashed; border-width:1px; border-color:red" title="">
                                <select name="adj_storage_no" id="adj_storage_no" tabindex="16" class="AXSelect W200"></select>
                                <input type="text" name="adj_st_rowcol" id="adj_st_rowcol" title="이동저장고행열" placeholder="이동저장고행열" tabindex="17" class="AXInput W120" />
						    </span>
					    </div>
				    </div>
				    <div class="item-clear"></div>
                    <div class="group-clear"></div>
	            </div>
                <div class="item-group" style="">
				    <div class="item fullWidth">
					    <div class="item-lable">
						    <span class="th" style="min-width:100px;">이동내역</span>
						    <span class="td inputText" style="border-style:dashed; border-width:1px; border-color:red" title="">
                                <input type="text" name="adj_bigo" id="adj_bigo" class="AXInput" tabindex="18" />
						    </span>
					    </div>
				    </div>
				    <div class="item-clear"></div>
				    <div class="group-clear"></div>
			    </div>        
                <div class="item-group" style="">
				    <div class="item fullWidth">
					    <div class="item-lable">
                            <p class="desc">적용을 하시면 원물재고목록에 가반영이 되며 <span style="color:red">[재고이동처리]</span>를 하셔야 합니다.</p>
                        </div>
                    </div>
                    <div class="item-clear"></div>
				    <div class="group-clear"></div>
                </div>
            </div>
            </form>
            <div class="ax-unit center" style="padding:5px;text-align:center">
                <button type="button" class="AXButton" onclick="fnObj.item.submit();">적 용</button>
                <button type="button" class="AXButton" onclick="fnObj.item.close();">취 소</button>
            </div>                
        </div>             
    </div>
</div>

'''
'''javascript
        grid: {
            target: new AXGrid(),
            get: function(){ return this.target; },
            bind: function() {
                this.target.setConfig({
                    targetID: "page-grid-box",
                    theme: "AXGrid",
                    fitToWidth: true,
                    sort: false,
                    mediaQuery: {
                        mx: { min: 0, max: 767 },
                        dx: { min: 767 }
                    },
                    colGroup: [
                        {
                            key: "no",
                            label: "선택",
                            width: "40",
                            align: "center",
                            formatter: "checkbox",
                            checked: function () {
                                return (this.item.__checked && this.item.__checked["0"]);
                            }
                        },                                                                                                  //0
                        {
                            key: "no", label: "번호", width: "60", align: "center", formatter: function () {
                                return (this.item.no);
                            }
                        },                                                                                                 //1
                        { key: "cust_nm", label: "거래처명", width: "120", align: "left", formatter: "dec" },              //2
                        {
                            key: "po_no", label: "수매번호", width: "110", align: "center", formatter: function () {
                                return "<u>" + this.item.po_no + "</u>";
                            }
                        },                                                                                                 //3
                        { key: "goods_nm", label: "상품", width: "120", align: "left", formatter: "dec" },                 //4
                        { key: "size_nm", label: "크기", width: "50", align: "center", formatter: "dec" },                 //5
                        { key: "grade_nm", label: "품질", width: "40", align: "center", formatter: "dec" },                //6
                        { key: "selection_nm", label: "혼합율", width: "50", align: "center", formatter: "dec" },          //7
                        { key: "storage_nm", label: "저장고", width: "100", align: "left", formatter: "dec" },             //8
                        { key: "st_rowcol", label: "행열", width: "40", align: "center", formatter: "dec" },               //9
                        { key: "stock_qty", label: "재고수량", width: "60", align: "right", formatter: "money" },          //10
                        { key: "stock_wgt", label: "재고중량", width: "70", align: "right", formatter: "money" },          //11
                        { key: "stock_qty_real", label: "변경수량", width: "70", align: "center", formatter: "money"},     //12
                        { key: "stock_wgt_real", label: "변경중량", width: "70", align: "right", formatter: "money" },     //13
                        {
                            key: "stock_qty_adj", label: "이동수량", width: "70", align: "right", formatter: function () {
                                return "<u>" + this.item.stock_qty_adj.money() + "</u>";
                            }
                        },                                                                                                  //14
                        { key: "stock_wgt_adj", label: "이동중량", width: "70", align: "right", formatter: "money" },       //15
                        { key: "adj_bigo",label: "이동내역",width: "90",align: "left",formatter: "dec"},                    //16
                        { key: "adj_storage_nm", label: "이동저장고", width: "150", align: "left", formatter: "dec" },       //17
                        { key: "adj_st_rowcol", label: "이동저장고행열", width: "100", align: "left", formatter: "dec" }    //18
                    ],
                    body: {
                        onclick: function () {

                            if (this.c == 3 || this.c == 14) {
                                fnObj.item.edit(this.index, this.item);
                            }

                        },
                        oncheck: function () {
                            
                            //체크박스 했을경우 addClass 색깔 나오게 하기 위해~

                            //데이터 싱크를 맞춰줌!!  onchangeScroll 이벤트를 내부적으로 다시 태움
                            //fnObj.grid.get().bigDataSyncApply(true); 메서드 이름 축소 기능개선 --> myGrid.dataSync(); 
                            //myGrid.dataSync(); 를 호출하면 그리드 리스트의 데이터를 수정 후 태그를 업데이트 하도록 변경!!
                            fnObj.grid.target.dataSync(true);
                        },
					    addClass: function(){

					        return (this.item.___checked && this.item.___checked["0"]) ? "blue" : "white";

                            /*
					        if (this.item.check_yn == "Y") {
					            return "blue";
					        } else {
					            return "white";
					        }
                            */
                            
					    },
                        onchangeScroll: function(){

                            
                        }
                    },                
                    page: { paging: false, status: { formatter: null } }
                });
            },
'''

'''javascript
item: {
            target: null,
            get: function() { return this.target; },
            bind: function() {
                this.target = fnObj.modal.target;
            },
            open: function(act_tp, idx, Obj) {
                var pars = "";
                this.target.openDiv({
                    modalID: "modalDiv01",
                    targetID: "modalContent",
                    pars: pars,
                    top: 100, width: 900,
                    closeByEscKey: true
                });

                $("#adj_storage_no").unbindSelect();
                $("#adj_st_rowcol").unbindInput();

                $("#adj_storage_no").bindSelect({
                    ajaxUrl: "/WPBase/Common/UI/FindCombo.aspx/SelectStorageToFind",
                    ajaxPars: "",
                    isspace: false,
                    isspaceTitle: "==선택==",
                    onChange: function (ogj, IsPostBack) {
                        var value = (this.optionValue || "");

                        //IsPostBack옵션
                        //trace("IsPostBack===="+IsPostBack);
                        if (typeof IsPostBack == "undefined") {
                            if (value != "") {
                                $("#adj_st_rowcol").val("");
                                $("#adj_st_rowcol").bindSelector({
                                    direction: "bottom",
                                    appendable: true,
                                    optionPrintLength: 200,
                                    ajaxUrl: "/WPBase/Common/UI/FindCombo.aspx/SelectStorageRowColToFind",
                                    ajaxPars: "storage_no=" + value,
                                    onChange: function () {
                                        //trace(this);
                                    }
                                });
                            }
                        }
                    },
                    onLoad: function () {
                        //trace(this);
                        //trace(this.options[0].optionValue);
                        $("#adj_st_rowcol").bindSelector({
                            direction: "bottom",
                            appendable: true,
                            optionPrintLength: 200,
                            ajaxUrl: "/WPBase/Common/UI/FindCombo.aspx/SelectStorageRowColToFind",
                            ajaxPars: "storage_no=" + this.options[0].optionValue,
                            onChange: function () {
                                //trace(this);
                            }
                        });


                        $("#stock_qty_adj").bindMoney({
                            min: 0,
                            max: 900000000,
                            onchange: function () {
                                //trace(this);
                                fnObj.item.calc_form();
                            }
                        });

                    }
                });

                //document.divWriteForm.code_nm_wr.focus();

                if (act_tp == "U" && Obj != null) {

                    $("#idx_wr").val(idx);  //Item Index 
                    $("#no").val(Obj.no);
                    $("#cust_nm").val(Obj.cust_nm.dec());
                    $("#po_no").val(Obj.po_no);
                    
                    $("#goods_nm").val(Obj.goods_nm.dec());
                    $("#size_nm").val(Obj.size_nm.dec());
                    $("#grade_nm").val(Obj.grade_nm.dec());
                    $("#selection_nm").val(Obj.selection_nm.dec());
                    $("#storage_nm").val(Obj.storage_nm.dec());
                    $("#st_rowcol").val(Obj.st_rowcol.dec());

                    $("#stock_qty").val(Obj.stock_qty.money());
                    $("#stock_wgt").val(Obj.stock_wgt.money());
                    $("#stock_qty_real").val(Obj.stock_qty_real.money());
                    $("#stock_wgt_real").val(Obj.stock_wgt_real.money());
                    
                    
                    $("#stock_qty_adj").val(Obj.stock_qty_adj.money());
                    $("#stock_wgt_adj").val(Obj.stock_wgt_adj.money());

                    $("#adj_storage_no").bindSelectSetValue(Obj.adj_storage_no);
                    $("#adj_st_rowcol").val(Obj.adj_st_rowcol);
                    $("#adj_bigo").val(Obj.adj_bigo.dec());
                    
                    /*
                    $("#act_tp_wr").val(act_tp);
                    $("#code_cd_wr").val(Obj.code_cd);
                    $("#group_cd_wr").bindSelectDisabled(true);
                    $("#group_cd_wr").bindSelectSetValue(Obj.code_cd.left(2));
                    $("#code_nm_wr").val((Obj.code_nm || "").dec());
                    $("#code_eng_nm_wr").val((Obj.code_eng_nm || "").dec());
                    $("#descr_wr").val((Obj.descr || "").dec());
                    $("#sys_yn_wr").bindSelectSetValue(Obj.sys_yn);
                    if (Obj.sys_yn == "N") $("#btnDel").css("display", "");
                    */
                }

            },
            edit: function(idx, Obj) {
                if (Obj != null) {
                    fnObj.item.open("U", idx, Obj);
                }
            }
}
'''
SCRIPT7002: XMLHttpRequest: 네트워크 오류 0x800c0007, 요청한 리소스가 사용할 수 있는 데이터가 없습니다.
에러가 나구요
여전히 opendiv로 열였는데도 뒤에 있는 그리드행이 움직입니다.
div는 같은 페이지에 div객체로 숨긴처리된걸 호출합니다.

**Comment by tom-axisj** [comment]
body에 마스크가 씌워지면 키입력 이벤트가 발생되지 않도록 변경 하였습니다.
레이어 팝업일 때는 이벤트제어가 참 어렵네요.
그리드에 엘리먼트에 포커스를 주려면 A, input, select등의 아이템이 있어야 포커스를 줄수 있는데요.
그리드에 포커스주는 방법을 근본적으로 해결하기 전까진 조금 레이어 처리시 어색할 수 있겠습니다.

언제나 그렇지만 또 해결이 될 것입니다.
