### ISSUE TITLE
그리드 값 넣기 질문입니다.(질문이 자꾸 늘어가네요...ㅠ)

### ISSUE THREAD

**Issue by solarware-lee** [axisj-com/axisj#545]
inline-edit에서 
function에서 임의로
myGrid.list[0].abc = "AAA"; 라고 줄경우

```
{
  key:"abc", label:"test", width:"70",
editor: {
                type: "text"
              }
}
```
이렇게  되잇을경우 값은 들어가는데 화면에서는 보여지지않고
마우스로 클릭을 해야 값이 들어가게됩니다.

```
function fixPjtNo(){
	myGrid.list[0].abc = "AAA";
}
```

이런식으로 밖에서 function으로 값줬을때 값은 들어가지만 화면에는 보이지 않는 현상인데
다른 메소드나 그런게 있나요? api에서 set쪽은 이것저것 다해봣는데 안되더라구요.. ㅠ

**Comment by hyunjun19** [comment]
`myGrid.printList()` 메서드를 호출해 보세요.

http://jdoc.axisj.com/AXGrid.html#printList

**Comment by solarware-lee** [comment]
@hyunjun19 오오 이런기능이 있었네요 ㅎㅎ 감사합니다!

**Comment by hyunjun19** [comment]
아래 메서드를 사용하시면 `printList` 메서드를 사용하실 필요가 없습니다.
http://jdoc.axisj.com/AXGrid.html#updateItem
