### ISSUE TITLE
질문좀 AxGrid colGroup : key  혹시 색깔이나 굶은글씨로 표시할수있는옵션이있나요?

### ISSUE THREAD

**Issue by yongjun0213** [axisj-com/axisj#547]
질문좀 AxGrid colGroup : key  혹시 색깔이나 굶은글씨로 표시할수있는옵션이있나요?

**Comment by hyunjun19** [comment]
아래 그림에서 오렌지 박스 안의 글씨를 말하시는 건가요?
Key는 보여지는 내용이 아닙니다.

![image](https://cloud.githubusercontent.com/assets/421863/7405068/495fe8ca-ef28-11e4-911b-002ac50a30a8.png)

**Comment by yongjun0213** [comment]
네엡 저기 제목들이요!

**Comment by hyunjun19** [comment]
`label`을 그냥 HTML로 작성하시면 됩니다.

```js
...
    {key:"writer",  label:"<span style='font-weight:bold;color:red;'>작성자</span>", width:"100"},
...
```

**Comment by yongjun0213** [comment]
앗 감사합니다 ㅠ_ ㅠ

**Comment by pji114** [comment]
HTML로 저기 타이틀을 굵게는 할수 있는데..그렇게 하니 저 타이틀을 클릭했을때 정렬이 안되네요;;
이건 방법이 없을까요?
