### ISSUE TITLE
dialog.push 함수에 모달로 띄울수 있는 옵션은 없나요?

### ISSUE THREAD

**Issue by davidwin3** [axisj-com/axisj#548]
AXModal이 있어서 어떨지 모르겠습니다만..

dialog.push의 유용함을 벗어날수가 없네요ㅜㅡ

혹시 모달로 띄울수 있는 옵션이 있다면 천기누설 부탁드리고
없다면 만들어주시면 정말 감사하겠습니다 

p.s. 꼭 도네이션해야되는 프로젝트입니다. 저도 노력해보겠습니다.

**Comment by tom-axisj** [comment]
modal을 쓰세요~

**Comment by davidwin3** [comment]
넵!^^
