### ISSUE TITLE
AXModal openDiv close가 잘 안되네요

### ISSUE THREAD

**Issue by davidwin3** [axisj-com/axisj#549]
<div style="display: none">
    <div id="noteDiv" style="height:300px">
      <table class="AXFormTable">
        <colgroup>
         <col width="30%">
         <col width="">
        </colgroup>
        <tr>
          <th>내용</th>
          <td><textarea id="txnote" name="txnote" cols="30" rows="20"></textarea></td>
        </tr>
        <tr>
          <td colspan="2"><button type="button" class="AXButton Grean W100"
              onclick="fnObj.notewrite()">작성완료</button></td>
        </tr>
      </table>
    </div>
  </div>
이건 div창 만들 html입니다

var myModal = new AXModal();
myModal.openDiv( {
          modalID: "modal02",
          targetID:"noteDiv",
          width: 600,
          closeByEscKey: true,
          verticalAlign: true
      });

이렇게 띄웠을때 

myModal.close(), myModal.remove() 모두 잘 안되네요
mac이라 캡쳐가 안되네요 ㅠ

**Comment by tom-axisj** [comment]
```js
myModal.close('modal02');
```

div 모달을 닫으려면 modalID값을 인자로 넘겨줘야 합니다.

**Comment by davidwin3** [comment]
앗 그렇군요 감사합니다~
