### ISSUE TITLE
AXGrid에서 콤보박스 관련

### ISSUE THREAD

**Issue by JangJaeHyung** [axisj-com/axisj#552]
안녕하세요, 문의사항이 있습니다.

AXGrid에서 콤보박스를 사용하는데요, DB에서 조회된 값을 콤보박스에 리스트로 넣고싶은데,

방법을 잘 몰라 문의드립니다.

ㅠㅠ

**Comment by hyunjun19** [comment]
https://github.com/axisj-com/axisj/blob/master/samples/AXGrid/inline-edit.html#L94

여기 예제를 참고하세요.

**Comment by JangJaeHyung** [comment]
![1](https://cloud.githubusercontent.com/assets/12267830/7489801/ba85c758-f415-11e4-8c73-6dfbe7675a5a.JPG)
위 그림처럼 그리드안의 콤보박스를 사용하고있는데, 콤보박스리스트의 값을 DB에서 불러와서 뿌려주는 방법이 없을까요? 현재는 아래와 같이 코딩되어있습니다. ㅠㅠ
![2](https://cloud.githubusercontent.com/assets/12267830/7489849/0224a87c-f416-11e4-9081-67a9d9af75f9.JPG)

**Comment by hyunjun19** [comment]
서버 언어는 뭘 사용하시나요?

PHP, Java, ASP ??

최대한 자세하게 설명을 해주세요.

**Comment by JangJaeHyung** [comment]
아, 죄송합니다.^^;;

언어는 자바입니다.(JSP)
DB는 mysql을 사용하고있습니다.

제가 하고싶은(?) 내용은 DB에서 쿼리조회된 내용을 AXGrid안의 콤보박스에 list로 넣고 싶습니다.

질문이 너무 어리바리하죠? ㅠㅠ 죄송합니다.

**Comment by hyunjun19** [comment]
방법은 여러가지가 있습니다만 서버에서 `options`의 내용을 JSON 문자열로 만들어서 JSP에 넣는 방법을 추천합니다.

```jsp
...
        options: ${col2Options}
...
```

JSON 문자열로 만드는 방법은 http://json.org 여기에서 적당한 라이브러리를 선택해서 사용하시면 됩니다.

만약 잘 모르시겠다면 현재 사용하시는 프레임워크를 알려주세요. 스프링 프레임워크나 스트럿츠 아니면 그냥 JSP에서 `<% ... %>` 이렇게 사용하신다던가...

**Comment by JangJaeHyung** [comment]
따로사용하는 프레임워크는 없고 그냥JSP에서  <% ... %> 태그로 사용하고있습니다.

**Comment by hyunjun19** [comment]
아무래도 문답이 길어질거 같은 예감이 드네요.

자바는 한 가지 기술을 구현하는데에도 여러가지 방법과 기술이 있습니다. 그래서 이런 포괄적인 질문에는 그냥 간단하게 '이거 사용하세요~'라는 식으로 답변을 드릴 수가 없습니다. ㅠㅠ

그리고 저도 질문을...
1. JSP에서 [모델1 방식](http://seinarin.tistory.com/18)을 사용하고 계신가요?
2. 현재 java에서 List를  JSON 문자열로 변환하는 방법을 사용하고 계신가요?

가능하시다면 JSP 전체 소스를 올려주세요.
