### ISSUE TITLE
AXTab질문

### ISSUE THREAD

**Issue by hajinhajin** [axisj-com/axisj#553]
![1](https://cloud.githubusercontent.com/assets/12285758/7507255/24fe3dee-f4a8-11e4-99c3-105cef4b1718.JPG)

안녕하세요, 위 그림처럼 탭을 이용하여 화면전환을 구현하고 싶은데, 

![2](https://cloud.githubusercontent.com/assets/12285758/7507271/54da0156-f4a8-11e4-9e2c-fa57b435f910.JPG)

onchange에서 어떤식으로 호출을 해야할까요?

첫번째탭 : 맨위사진
두번째탭 : 그리드2개

**Comment by groovedk** [comment]
a tag에 tab스타일만 적용한거면 링크대로 이동할 것이고
위 소스를 적용하신거면 onchange 에 탭내용을 담고있는 컨테이너를(보통 div를 사용하시겠지요) show / hide 해주시면 될 것 같네요.

**Comment by hajinhajin** [comment]
네 감사합니다.

div show/hide로 처리 완료되었습니다.^^
