### ISSUE TITLE
AXGrid Select 에디터 관련하여 문의드립니다.

### ISSUE THREAD

**Issue by manoi83** [axisj-com/axisj#555]
안녕하세요.

공개해주신 소스를 너무나 감사한 마음으로 쓰고 있는 개발자입니다.

사용중에 AXGrid Select 관련하여 몇가지 문의사항이 있어 질문드립니다.

1. AXGrid의 getList 함수를 통해 C, U 값만 가져오도록 설정해서 DB에 저장하려고 하는데

   Select 로 설정된 항목은 Value가 아닌 Text를 가져오도록 되어 있어

   Value 를 가져올 수 있도록 하는 방법이 있는지 궁금하여 문의드립니다.

ex) 다음과 같이 설정되어 있는 경우 함수 호출 시 "첫번째" 텍스트를 가져오는데 "1"을 가져올 수 있는 방법
   {key:"Col1",
     editor:{
        type:"select",
        options:[
                     {optionValue:"1", optionText:"첫번째"},
                     {optionValue:"2", optionText:"두번째"}
        ]
      }
   }

2. pushList 함수로 행추가 시 기본값 입력하도록 하는데요.
   
    위의 예시와 같이 Select 항목이 정의된 경우 pushList로 값입력 시 "1"을 입력하여 

    "첫번째"에 해당하는 항목이 선택되도록 하는 방법이 있는지 문의드립니다.

검토 후 답변 주시면 감사합니다.^^

**Comment by tom-axisj** [comment]
몇가지 방법이 있습니다.

```js
{key:"useYn", label:"사용여부", width:"70", align:"center",
    formatter:function(){
        return (this.value == "Y") ? "사용" :"미사용";
    },
    editor:{
        type:"select", value:"itemValue",
        options:[
            {optionValue:"Y", optionText:"사용"},
            {optionValue:"N", optionText:"미사용"}
        ],
        beforeUpdate: function(val){ // 수정이 처리된 후
            // 수정이 된 후 액션.
            //console.log(val);
            return val.optionValue; //(val.optionValue == "true");
        }
    }
}
```
> beforUpdate를 이용하여 선택된 값을 바꿔치기 하는 방법
`console.log(this)`를 beforUpdate 안에 찍어보면 좀더 자세한 정보를 얻을 수 있습니다.


다음은 그리드 데이터를 Object로 처리하고
```js
[
{
    no:3,
    string: "AXGrid 첫번째 줄 입니다.",
    combobox: 3,
    combobox2: {CD:1, NM:"김기영"},
    date: "2013-01-18",
    money: 1709401,
    number: 10,
    checkbox: 1,
    radio: 1,
    finder: "선택"
}
]
```
colGroup 에서 formatter 로 표시 데이터를 바꾸기
```js
{
    key:"combobox2", label:"combobox2", width:"100",
    formatter: function(val){
        if(Object.isObject(this.value)){
            return this.value.NM;
        }else{
            return this.value;
        }
    },
    editor: {
        type: "AXSelect",
        config: {
            reserveKeys: {
                options: "list",
                optionValue: "CD",
                optionText: "NM"
            },
            ajaxUrl: "selectData-01.php",
            ajaxPars: "",
            onchange: function(){
                // inline editor 에 선언한 onchange함수는 AXGrid내부에서 사용하는 onchange 함수로 변경되어 사용할 수 없습니다.
            }
        },
        beforeUpdate: function(val){ // 수정이 되기전 value를 처리 할 수 있음.
            // 선택된 값은
            console.log(val);
            return val;
        },
        afterUpdate: function(val){ // 수정이 처리된 후
            // 수정이 된 후 액션.
            //console.log(this);
        }
    }
},
```

**Comment by manoi83** [comment]
답변 주셔서 감사합니다.^^

먼저 두번째 항목은 처리가 되었습니다.

첫번째 항목은 말씀하신대로 할 경우 Select 항목이 변경 또는 추가 되는경우 
매번 formmater에 추가로 코딩해야하는 부분이 있어 다른방법을 강구해봐야 할거 같습니다.

다시 한번 빠른 답변 해주셔서 감사합니다!!
