### ISSUE TITLE
AXUpload5 한글깨짐

### ISSUE THREAD

**Issue by gooya6609** [axisj-com/axisj#556]
업로드 컴포넌트를 사용하는데,
파일 Upload 이후

		response.write "[{"
		response.write "name:'"&enc(iFileTitle)&"', "
		response.write "type:'"&enc(FileExt)&"', "
		response.write "saveName:'"&enc(TempFilename)&"', "
		response.write "fileSize:'"&FileSize&"', "
		response.write "uploadedPath:'"&enc(folderName)&"', "
		response.write "thumbUrl:'"&enc("")&"', "
		response.write "iBoardNum:'"&enc(iNum)&"'"
		response.write "}]"

이런식으로 결과를 찍을 떄 한글이 깨져서 찍히게 됩니다.
어떻게 해결해야 될까요?

**Comment by hyunjun19** [comment]
한글이 깨지는 문제는 주로 서버단 환경(인코딩) 문제입니다.
해당 문제는 환경 확인이 불가능해서 뭐라 답변하기가 어렵네요.

**Comment by groovedk** [comment]
응원을 해드립니다!
화이팅 :fire:

**Comment by tom-axisj** [comment]
:+1: 
:open_hands:
