### ISSUE TITLE
달력이 이상하게 행동합니다.

### ISSUE THREAD

**Issue by sparkkong** [axisj-com/axisj#557]
아래 내용을 보면 2015년 1월을 선택했는데 실제 text박스에는 2014년 1월이 선택됩니다.
![image](https://cloud.githubusercontent.com/assets/6268169/7531364/e7585438-f593-11e4-98c0-afa6d4574865.png)

달력을 열어서 1월을 선택한 다음, OK버튼을 누르고, 
다시 열어서 클릭해보면 이런현상이 발생합니다.

왜 이런지 확인해 주실 수 있을까요?

selectType은 "m" 입니다.

감사합니다.

**Comment by hyunjun19** [comment]
음... 버그 같습니다. 조만간 조치를 취하겠습니다.

**Comment by hyunjun19** [comment]
#503 딱 이 버그네요...;;
시간이 걸릴 수도...

**Comment by sparkkong** [comment]
아직 버그픽스가 안되고 있는거보니..어려운건가 봐요..ㅠㅜ

**Comment by hyunjun19** [comment]
01dd69d8ba5bb41aeed2f055baa421ab24b44d48 버그 패치되었습니다.

해당 버그 패치는 현재는 dev 브런치에만 적용되어 있습니다.
정식 릴리즈는 한 달에 한 번씩 되고 있으니 서비스 중이 아니시라면 기다렸다가 정식 릴리즈 버전을 사용하시면 됩니다.

**Comment by sparkkong** [comment]
아 확인해보니 문제없습니다~~
정말정말 감사합니다^^

**Comment by sparkkong** [comment]
아 그리고, 정식릴리즈에 반영될 수 있다면 아래 기능들도 있으면 좋을 것 같습니다.
1. 아이콘을 클릭하지 않고 textbox를 클릭해도 달력이 뜰수있는기능.
2. OK버튼을 클릭하지 않아도 날짜를 선택하면 콜백을 주는 기능.
3. OK, START, END 등의 TEXT를 지정할 수 있는기능.

AxCarendar만큼 강력한 달력은 없는것 같은데 위 기능들이 좀 아쉬운 부분입니다.
항상 감사합니다!

**Comment by hyunjun19** [comment]
추가 기능들도 검토해 보겠습니다. =)

**Comment by hyunjun19** [comment]
해결되었으면 이슈를 Close 해주세요.

오른쪽 상단에 별을 눌러 주시면 개발자들에게 큰 힘이 됩니다. =)
