### ISSUE TITLE
파일업로드 질문있습니다.

### ISSUE THREAD

**Issue by boxkie** [axisj-com/axisj#558]
확장자 제한의 경우

아래의 데이터를
image/gif | image/jpeg | image/bmp | image/png

file_types:"${fileExtT}",  //  *.*  | audio/* | video/* | image/* | MIME_type (accept)

위와 같은 형식으로 집어 넣었는데 

![2015-05-08 19 18 59](https://cloud.githubusercontent.com/assets/10544177/7534617/277d851a-f5b7-11e4-82de-0440205e6642.PNG)

이렇게 오류 나옵니다.

해결방법을 좀 알수 있을까요?

그리고 axisJ 공식 홈페이지 AXUpload5 에서 이미지가 아닌 파일을 올렸을때

아무런 경고창이 나타나지 않게 되는데 경고창을 띄울 수 있는 방법이 궁금합니다.

아 추가적으로 위의 이미지는 파일을 업로드할 겨우 나타나는 오류 입니다.
prototype 오류는 충돌 오류 이므로 무시하셔도 무방할듯합니다.

**Comment by tom-axisj** [comment]
http://www.sitepoint.com/web-foundations/mime-types-complete-list/

여기를 참고하시구요.

이미지만 올리려면 `image/*` 해야겠습니다. 나머지는 참고해서 정의하세요. 확장자명 `.jpg` 같은걸 상상하시면 안되겠습니다.

**Comment by boxkie** [comment]
.jpg 가 아니라 아래 처럼 넣어서 오류가 나고있습니다...

file_types:"image/gif | image/jpeg | image/bmp | image/png",

일단 이렇게 적어준 방식이 맞는지 아닌지 궁금합니다.

**Comment by hyunjun19** [comment]
```
upload 할 파일타입( *.* | audio/* | video/* | image/* | MIME_type (accept) )
```
https://github.com/axisj-com/axisj/blob/master/lib/AXUpload5.js#L1207 여기를 참고해 주세요. API가 http://jdoc.axisj.com/AXConfig.html#AXUpload5 API 사이트에 아직 반영이 안되어 있네요.

**Comment by boxkie** [comment]
그럼 PDF 문서나 HWP 문서는 
application/*
인가보네요.
세부적으로는 안되는가보네요 알겠습니다.
감사합니다.
