### ISSUE TITLE
크롬브라우저에서 트리에서 아이콘 깨지는 문제..

### ISSUE THREAD

**Issue by david80** [axisj-com/axisj#561]
크롬브라우저에서 트리에서 아이콘 깨지는 문제..
![default](https://cloud.githubusercontent.com/assets/11273651/7605574/0c1392e6-f98c-11e4-8177-59bd9ebd6807.png)

**Comment by hyunjun19** [comment]
인스펙터에서 HTML을 복사해서 올려주세요.

아래 그림처럼 HTML 노드를 선택해서 `Ctrl + C`, `Ctrl + V` 하시면 됩니다.

![image](https://cloud.githubusercontent.com/assets/421863/7605935/6e5f8722-f98f-11e4-9cb3-fa8277d3b8d7.png)

**Comment by david80** [comment]
<div class="bodyNode bodyTdText" style="padding-left:50.25px;" align="left" id="ax-aside-page-tree_AX_bodyText_AX_0_AX_0_AX_10"><a class="bodyNodeIndent" id="ax-aside-page-tree_AX_bodyNodeIndent_AX_0_AX_0_AX_10" style="left:12.25px;"></a><a class="bodyNodeIcon userHtml" id="ax-aside-page-tree_AX_bodyNodeIcon_AX_0_AX_0_AX_10" style="left:32.25px;"><i class="axi axi-folder-open"></i></a>공지사항정보</div>

**Comment by david80** [comment]
원인 해결했네요 .wwf 확장자가 iis7 세팅 마미타입에 없었네요.. 추가해주니 잘 됩니다.
