### ISSUE TITLE
TagSelector 삭제 표시가 깨져서 나옵니다.

### ISSUE THREAD

**Issue by hyunjun19** [axisj-com/axisj#563]
`TagSelector` 삭제 표시가 깨져서 나옵니다.

![image](https://cloud.githubusercontent.com/assets/421863/7625969/71ad2b4a-fa3a-11e4-8f1e-1c6dfefdd327.png)

**Comment by tom-axisj** [comment]
axicon 추가

**Comment by hyunjun19** [comment]
잘 나옵니다. :+1:
