### ISSUE TITLE
그리드 소계 버그

### ISSUE THREAD

**Issue by david80** [axisj-com/axisj#564]
스크롤 움직일때 소계 값이 바뀝니다.
그리고 소계의 가격 합산값이 이상하네요..

![1 2](https://cloud.githubusercontent.com/assets/11273651/7626568/4fe25ed4-fa46-11e4-96b7-ac2c8d1fe573.png)

**Comment by hyunjun19** [comment]
대용량 데이터 처리를 위한 동적으로 필요한 행만 그리는 기능과 샘플코드의 합계를 구하는 로직이 상충되서 발생하는 버그 입니다.

아래 샘플 처럼 소계 데이터를 정적으로 구하셔야 합니다.

https://github.com/axisj-com/axisj/commit/a8f592f
