### ISSUE TITLE
소계부분에서 머지한 컬럼 옆으로 소계기능이 되는지 궁금하네요

### ISSUE THREAD

**Issue by david80** [axisj-com/axisj#565]
![11111](https://cloud.githubusercontent.com/assets/11273651/7627220/c80532b6-fa4f-11e4-93a6-406119d8a9a0.jpg)

생산자별로 소계를 하고 싶은데 머지한상태에서는 깨지더라구요,

**Comment by hyunjun19** [comment]
컬럼 옆으로 소계를 넣는 기능은 없습니다만 아래처럼 하면 구현은 가능할것 같습니다.

소계값은 서버에서 구해서 오셔야 합니다.
데이터를 아래처럼 서버에서 가져오신후 소계 컬럼도 머지셀에 추가해 주세요.

여러 컬럼을 머지셀 설정시 연속된 컬럼으로 설정하셔야 합니다.
좋은 예) `mergeCells: [3, 4, 5], // 인덱스 3, 4 셀을 머지하지만 앞의 셀이 머지 되었을 때만 다음셀을 병합합니다.`
나쁜 예) `mergeCells: [3, 4, 6],`

```js
[
    ...
    { '생산자':'박상국(곽순희)', '소계':58578, '품명':'마사리(밤고구마)' },
    { '생산자':'박상국(곽순희)', '소계':58578, '품명':'밤고구마(일반)' },
    { '생산자':'박상국(곽순희)', '소계':58578, '품명':'하루까(찰랑고구마)' },
    ...
]
```

그리고 가능할지 모르겠지만 http://localhost/axisj/samples/AXGrid/fixedColSeq.html 여기를 참고하셔서 컬럼을 고정시키면 더 좋을 것 같습니다. 하지만 소계와 컬럼 고정을 같이 써본적이 없어서 100% 가능할지 모르겠네요. ^^;;
