### ISSUE TITLE
AXUpload5 크로스 도메인 지원 관련해서 문의 드립니다.

### ISSUE THREAD

**Issue by DaeHyeon-Kim** [axisj-com/axisj#567]
크로스 도메인 관련으로 문의 드립니다.

예를 들어 업로드하는 메인 서버가 http://a.co.kr 이고 파일 업로드를 http://b.co.kr 라는 도메인의 서버로 업로드를 하려고 합니다.

flash_url : "http://b.co.kr/jsp/axisj/lib/swfupload.swf",
flash9_url : "http://b.co.kr/jsp/axisj/lib/swfupload_fp9.swf",
uploadUrl:"http://b.co.kr/jsp/FileUpload.jsp",
deleteUrl:"http://b.co.kr/jsp/FileDelete.jsp",

위에 처럼 URL을 설정 후 실제로 테스트를 진행해 본 결과 IE9에서는 정상적으로 파일이 올라가지만
삭제 스크립트가 먹히지 않고 스크립트 오류도 나지 않습니다.

크롬에서는 multipart/form-data로 넘어가지 않아 서버에 오류가 발생하고,
아래와 같이 콘솔에 오류가 발생합니다.

XMLHttpRequest cannot load http://b.co.kr/jsp/FileUpload.jsp. The 'Access-Control-Allow-Origin' header has a value 'http://b.co.kr' that is not equal to the supplied origin. Origin 'http://a.co.kr' is therefore not allowed access.

해결책이 없는지 문의 드립니다.

**Comment by hyunjun19** [comment]
CORS로 검색을 하시거나 아래 링크를 참고하세요.
크로스 도메인은 UI 컴포넌트로 지원할 수 있는 문제가 아닙니다.

https://breadmj.wordpress.com/2013/08/21/implement-cors-using-spring-mvc/

아니면 간단하게 http://a.co.kr에 파일을 업로드하고  FTP로 http://b.co.kr에 전송하세요.

**Comment by DaeHyeon-Kim** [comment]
답변 감사합니다.
가까운 지역의 서버로 업로드 하도록 개발 중 이라서 FTP는 안될 것 같아
CORS로 검색해서 찾아보았습니다. 톰캣 web.xml에 필터를 추가하니 정상적으로 돌아가네요.
  <filter>
	  <filter-name>CorsFilter</filter-name>
	  <filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
	</filter>
  <filter-mapping>
	  <filter-name>CorsFilter</filter-name>
	  <url-pattern>/*</url-pattern>
  </filter-mapping>

IE11, 크롬에서는 문제 없이 돌아가는 것을 확인하였습니다.
그런데 문제는 IE9에서 문제이더군요.
파일 업로드 및 리턴 값을 제대로 받아오지만 올라간 파일이 삭제가 되지 않습니다. 
콘솔에 오류 표시도 나오지 않고요.
크로스 도메인 문제가 아닌 스크립트 상 문제인 거 같기도 합니다.
메인서버에서는 잘 삭제가 되지만 b.co.kr로 변경하면 삭제가 되지 않네요.

**Comment by DaeHyeon-Kim** [comment]
감사합니다. CORS 로 검색해보니 web.xml에 필터 추가 하는 게 있네요. 추가하니까 바로 적용됩니다.

**Comment by hyunjun19** [comment]
간단하게 해결되었다니 다행입니다. :+1: 

오른쪽 상단에 별을 눌러 주시면 개발자들에게 큰 힘이 됩니다. =)
