### ISSUE TITLE
AxGrid관련 문의 입니다. 

### ISSUE THREAD

**Issue by leeYongchang** [axisj-com/axisj#568]
AxGrid관련하여 문의 드릴게 있어서 글을 적습니다. 

웹페이지에서 AxGrid를 2개 실행 할 경우 선택한 row가 각각 있을 경우 방향키로 이동 시 두개의 그리드 모두가 선택 row가 변경이 되고 있습니다. 

key이벤트를 막거나 변경을  할려면 어떻게 하는지 알고 싶어 글을 올립니다.

**Comment by tom-axisj** [comment]
금일중에 패치될 예정입니다.

**Comment by tom-axisj** [comment]
처리됬습니다. 소스 받는 방법은 아시나요? dev 브랜치 코드를 받으셔야 합니다.

**Comment by leeYongchang** [comment]
고맙습니다.

**Comment by hyunjun19** [comment]
해결되었으면 이슈를 Close 해주세요.

오른쪽 상단에 별을 눌러 주시면 개발자들에게 큰 힘이 됩니다. =)

**Comment by leeYongchang** [comment]
키이벤트는 정상적으로 됩니다. (고맙습니다.)
그런데 그리드 합계를 출력 시 화면이 깨지는 현상이 있는 것같습니다.

**Comment by tom-axisj** [comment]
@leeYongchang 감사합니다. 문제점을 알려주시는 것은 너무 감사하지만 그냥 현상이 있는 것 같다는 글을 남겨주시면 아무것도 수정할 수 없습니다. 어떤 코드를 실행했더니 에러가 있다고 알려주셔야 고칠수가 있습니다.
감사합니다.
