### ISSUE TITLE
그리드에 인풋박스 입력 안되는 문제..

### ISSUE THREAD

**Issue by david80** [axisj-com/axisj#571]
![localhost_20150518_160245](https://cloud.githubusercontent.com/assets/11273651/7675780/5fcb1aaa-fd77-11e4-9fbe-1b9bd6dcc1ee.jpg)
라이브러리를 최신으로 받아서 업데이트 했더니 그리드안의 인풋박스 입력이 안됩니다.
dev 브런치 된걸로 받아서 업데이트 했습니다.
axutil 도 안먹더군요.

**Comment by tom-axisj** [comment]
http://dev.axisj.com/samples/AXGrid/misc.html 기능의 이상이 없어 보입니다.

**Comment by david80** [comment]
IE7 에서 이상 반응 하네요 class 및 axutil 자바스크립트 오류발생
