### ISSUE TITLE
AXUpload5 IE9 파일 업로드 오류 후 처리 질문

### ISSUE THREAD

**Issue by DaeHyeon-Kim** [axisj-com/axisj#574]
안녕하세요.
AXUpload5에서 IE9로 업로드 할 때 오류 후 처리에 대해서 질문이 있습니다.
HTML5로 동작하는 IE10~11, 크롬, 파이어 폭스 에서는 오류가 발생하면 alert창으로 오류를 통지해 주고 목록에서 파일이 제거됩니다.
그런데 플래시로 동작하는 IE9에서는 업로드 되다가 멈추기만 하고 오류 후 처리가 안되어 있더군요.
HTML5에서 동작하는 것과 동일한 처리를 하게 할 수 있는 방법이 있나요?

**Comment by hyunjun19** [comment]
https://github.com/axisj-com/axisj/issues/559 여기를 참고하세요.
아직 정식 릴리즈에는 반영되지 않은 상태입니다.

**Comment by DaeHyeon-Kim** [comment]
답변 감사합니다. 
오류 발생 시 errorType이 -200으로 떨어지네요. 
일단 처리는 정상적으로 됩니다.
