### ISSUE TITLE
AXGrid 체크박스 checked,disabled 질문입니다

### ISSUE THREAD

**Issue by menser** [axisj-com/axisj#575]
안녕하세요

개발중에 AXGrid 체크박스의 checked,disabled 속성을 사용해볼려고 하는데요

두가지의 속성을 따로 사용하면 이상이 없는데

같이 사용해서  리턴값이 둘다 true로 들어오면 리스트가 제대로 

불러와지지 않는 현상이 발생하고있습니다

제가 뭔가를 잘못하고 있는건지 원래 같이 사용이 되지 않는건지 궁금합니다

아래와 같이 설정했을 경우입니다
       colGroup : [
                            {key:"no", label:"checkbox", width:"50", align:"center", formatter:"checkbox",
                                disabled:function(){
                                	return true;
                                },
	                        checked:function(){
	                        	return true;
	                    	}
                            }
                        ]

**Comment by tom-axisj** [comment]
disabled가 되면 checked가 작동하지 않도록 되어 있습니다. 제 기억으로~

**Comment by menser** [comment]
아 그런가요 

그럼 둘중에 하나만 사용하는걸로 개발해야겠네요 

감사합니다~!
