### ISSUE TITLE
AXGrid 에서 getExcelFormat 할때 foot 이 있으면 에러가 발생합니다. 

### ISSUE THREAD

**Issue by young-tae** [axisj-com/axisj#577]
getExcelFormat 할때  foot가 없으면 잘되는데 
foot이 있으면 아래와 같은 에러 발생하고 있습니다. 

Uncaught ReferenceError: filter is not defined(anonymous function) 
@ AXGrid.js:8657AXUtil.each 
@ AXJ.min.js:1Class.create.getExcelFootDataSet 
@ AXGrid.js:8655Class.create.getExcelFormat 
@ AXGrid.js:8755

getExcelFootDataSet 이 메소드 안에 
 if(filter && !filter.call(CH)){ 

정의 되지 않은 filter가 있어서 그런것 같습니다. 

테스트 사항
아래 페이지에서  
http://dev.axisj.com/samples/AXGrid/headfoot.html 

코드 실행할때 발생합니다. ->myGrid.getExcelFormat("html")

**Comment by tom-axisj** [comment]
실수가 있었습니다. 찾아주셔서 감사합니다. 수정코드 커밋했는데요. 문제가 있으면 바로 조치 하겠습니다.

**Comment by young-tae** [comment]
네 감사합니다.  ^^
