### ISSUE TITLE
모달팝업을 열었더니 AXUUtil 오류가 납니다.

### ISSUE THREAD

**Issue by david80** [axisj-com/axisj#579]
최신 라이브러리로 업데이트 했더니.. 
모달팝업 열었을때 이런에러가 나네요
```
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" /> 
```
였을때 인식을 못하는거 같아요

![1](https://cloud.githubusercontent.com/assets/11273651/7716000/99b8b5f4-fec8-11e4-92ae-9875ed7c8348.png)

**Comment by hyunjun19** [comment]
재현이 잘 안되네요.
AXJ.all.js 파일의 제일 첫 부분에 있는 버전과 릴리즈 날짜를 알려주세요.
그리고 테스트한 브라우저 버전도 알려주세요.

**Comment by tom-axisj** [comment]
제가 패치 했습니다. 두분다 감사합니다.

**Comment by hyunjun19** [comment]
:+1:
