### ISSUE TITLE
AXUpload5 Single 파일 업로드 로드 문제로 질문드립니다.

### ISSUE THREAD

**Issue by DaeHyeon-Kim** [axisj-com/axisj#580]
AXUpload5 Single 파일 업로드에서 서버에서 가져온 값이 들어가지 않고 progress bar 만 표시되는 현상이 있어 질문 드립니다.

//==============================File Load 부분======================
new AXReq(fileListLoadUrl, {pars:fileListLoadParam, onsucc:function(res){
					window.console.log(res);
					
					var primary = res.primaryFile;
					var secondary = res.secondaryFile;
					
					window.console.log(primary);
					window.console.log(secondary);
					
					primaryUpload.setUploadedList(primary);
					secondaryUpload.setUploadedList(secondary);
					/* if(!res.error){
						primaryUpload.setUploadedList(res.primaryFile);
						secondaryUpload.setUploadedList(res.secondaryFile);
					}else{
						alert(res.msg.dec());
					} */
					
				}});
//===============================return 되는 jsonData ============================

{ 
primaryFile : {id : 'AXUpload_Single', name : 'Readme.txt', type : '', saveName : 'Readme.txt', fileSize : '1570', uploadedPath : '/Windchill/servlet/AttachmentsDownloadDirectionServlet?oid=VR:wt.doc.WTDocument:130083&cioids=wt.content.ApplicationData:130088&role=primary', thumbUrl : '', roleType : 'primary', cacheId : '' },

secondaryFile : [{id : 'AXUpload_AX_0', name : '11.txt', type : '', saveName : '11.txt', fileSize : '17', uploadedPath : '/Windchill/servlet/AttachmentsDownloadDirectionServlet?oid=VR:wt.doc.WTDocument:130083&cioids=wt.content.ApplicationData:130090&role=secondary', thumbUrl : '', roleType : 'secondary', cacheId : '' },{id : 'AXUpload_AX_1', name : 'form 인증 변경.txt', type : '', saveName : 'form 인증 변경.txt', fileSize : '61', uploadedPath : '/Windchill/servlet/AttachmentsDownloadDirectionServlet?oid=VR:wt.doc.WTDocument:130083&cioids=wt.content.ApplicationData:130092&role=secondary', thumbUrl : '', roleType : 'secondary', cacheId : '' },{id : 'AXUpload_AX_2', name : '1.txt', type : '', saveName : '1.txt', fileSize : '229', uploadedPath : '/Windchill/servlet/AttachmentsDownloadDirectionServlet?oid=VR:wt.doc.WTDocument:130083&cioids=wt.content.ApplicationData:130094&role=secondary', thumbUrl : '', roleType : 'secondary', cacheId : '' }]

}

primary파일을 배열 형식 primaryFile : [ { id : ..... }] 으로 감싸도 적용되지 않아 위와 같이 처리를 해본 결과 multi 업로드는 잘 올라가는 반면 single 업로드에서 progress bar만  표시되는 현상이 생기고 있습니다. 데이터는 제대로 받아오고 있습니다. 어디가 문제인지 검토 부탁 드립니다.

**Comment by tom-axisj** [comment]
setUploadedList 에는 Array, Object 모두 처리 할 수 있게 되어있습니다. 
버그가 있었습니다만 덕분에 해결 되었습니다. 감사합니다.
dev브랜치를 다운받아 사용하세요.

**Comment by DaeHyeon-Kim** [comment]
답변 감사합니다 브렌치 받아서 적용하니까 정상적으로 동작하네요.
