### ISSUE TITLE
window가 줄어드는 경우 parentWidth가 17px 씩 작게 계산됨

### ISSUE THREAD

**Issue by hyunjun19** [axisj-com/axisj#585]
항상은 아니지만 아래 그림처럼 parentWidth가 17px 씩 작게 나와서 오른쪽이 비는 현상이 자주 발생함.
resize 이벤트 발생할 때 부터 parentWidth가 17px 씩 작게 나옴.

![image](https://cloud.githubusercontent.com/assets/421863/7790420/22bc35cc-02c2-11e5-87ae-cd75d052c4ab.png)

**Comment by tom-axisj** [comment]
컨테이너의 너비를 고정시켜야
안넘어 가겠네염

**Comment by tom-axisj** [comment]
아 그리고 split를 쓰는 경우엔 html, body 가 overflow:hidden 이어야

**Comment by hyunjun19** [comment]
아... 17px이면 스크롤 길이인듯...
