### ISSUE TITLE
AXUpload5 IE8 파일 업로드 관련 질문 드립니다.

### ISSUE THREAD

**Issue by DaeHyeon-Kim** [axisj-com/axisj#587]
AXUpload IE8 버전에서 파일 업로드를 하려고 했습니다.
버전 : 8.0.7600.16385

데모에서도 일어나고 있는 현상이라 확인 차 질문 드립니다.
AXUpload5에서 파일 올리기를 클릭 시 파일 선택 창이 나타나지 않고 아무런 반응이 없습니다.
IE 8에서 파일 업로드가 가능하게 하려면 따로 설정해야 하는 것이 있는 건가요?
또한 제가 알기로는 IE7까지 지원이 된다고 들었는데 맞는지 답변 부탁 드립니다.

**Comment by hyunjun19** [comment]
해당 PC에 플래시 플레이어가 설치되어 있는지 확인 부탁드립니다.

**Comment by DaeHyeon-Kim** [comment]
아...안 깔려있었네요... 답변 감사합니다. 
브라우저 지원은 IE 7까지 되는 게 맞는 건가요?

**Comment by hyunjun19** [comment]
네 IE7+ 입니다. =)

**Comment by DaeHyeon-Kim** [comment]
그렇군요. 감사합니다.
